### ISSUE TITLE
Scrutiny detected shelf as failed? [BUG]

### ISSUE THREAD

**Issue by KenwoodFox** [AnalogJ/scrutiny#106]
**Describe the bug**
Scrutiny seems to have listed a shelf controller as failed?

**Expected behavior**
A shelf controller is not smart enabled and should not be shown.

**Screenshots**
https://kitsunehosting.net/nextcloud/index.php/s/WcAEqewEANqzstH/preview

**Comment by AnalogJ** [comment]
Hey,
Under the hood Scrutiny uses `smartctl` for device detection and data retrieval. Unfortunately `smartctl` will occassionally detect virtual devices and attempt to retrieve data from them, which explains what you're seeing. 

You can override `smartctl`'s device detection by creating a [`collector.yaml` file](https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml).

I hope that helps fix your issue, feel free to re-open if not.
