### ISSUE TITLE
[BUG] Containers require root - /scrutiny/ directories in containers are owned as root:root

### ISSUE THREAD

**Issue by jamesread** [AnalogJ/scrutiny#109]
**Describe the bug**
On some Kubernetes platforms (eg, OpenShift), and in some situations, users will prefer to run containers as non-root. The `/scrutiny/*` directories are owned as `root:root`, so this will cause failures when trying to do things like create the initial database. 

**Expected behavior**
Consider making `/scrutiny/*` directories world writeable within the container? Containers should not require root. 

**Screenshots**
Running as user 100086...blah blah. 

![image](https://user-images.githubusercontent.com/2025715/96477808-d66a0500-122e-11eb-9a2d-74dc961e0176.png)

![image](https://user-images.githubusercontent.com/2025715/96477841-e1249a00-122e-11eb-8179-d70cce62686c.png)

**Log Files**

```
Trying to connect to database stored: /scrutiny/config/scrutiny.db

2020/10/19 16:03:15 [35m/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/sqlite3.go:17
[0m[31m[error] [0mfailed to initialize database, got error unable to open database file: no such file or directory
panic: Failed to connect to database!

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.DatabaseMiddleware(0xf6b7c0, 0xc0000b4ca8, 0xf70840, 0xc0003cc460, 0xf6cd40)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/sqlite3.go:22 +0x5ab

```

**Comment by AnalogJ** [comment]
Thanks for helping me debug this James! I’m traveling right now, but I’ll get this fixed ASAP! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AnalogJ** [comment]
Hey @jamesread 
I merged a fix that should allow Scrutiny to be run as a non-root user. It's going through the Docker Hub CI now.
