### ISSUE TITLE
StartTLS certificate errors with SMTP

### ISSUE THREAD

**Issue by RandomGithubUsername** [AnalogJ/scrutiny#111]
I'm using AWS's Simple Email Service as STMP server and I get these errors when I test the notification:
`time="2020-10-21T21:00:32Z" level=error msg="[error enabling StartTLS: x509: certificate signed by unknown authority]"
time="2020-10-21T21:00:32Z" level=error msg="One or more notifications failed to send successfully. See logs for more information."
time="2020-10-21T21:00:32Z" level=error msg="An error occurred while sending test notification error enabling StartTLS: x509: certificate signed by unknown authority"`

SMTP server: `email-smtp.us-east-1.amazonaws.com:587`

This same config (SMTP server and my credentials) are used with my other projects as-well so there is nothing wrong with my credentials itself.

I'm running the web as docker container (image: `analogj/scrutiny:web`)

**Comment by AnalogJ** [comment]
Ah, this is similar to the issue I fixed in the omnibus image a while ago. Basically the root CA certificates are not installed in the docker image

```
RUN apt-get update && apt-get install -y smartmontools=7.0-0ubuntu1~ubuntu18.04.1 ca-certificates curl && update-ca-certificates
```

I’m traveling right now, but I’ll make that fix ASAP. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RandomGithubUsername** [comment]
I manually updated/installed those directly inside the container (as temp fix) and email notifications are working now! Thank you!

**Comment by AnalogJ** [comment]
Hey @RandomGithubUsername I made a fix to ensure that ca-certificates are correctly installed in the web container. Sorry about that!
