### ISSUE TITLE
[FEAT] Option to choose the webui port

### ISSUE THREAD

**Issue by Ansem93** [AnalogJ/scrutiny#112]
Since the port 8080 is used by many services it would be better to let the user choose it. 
Also the default port should be different for the same reason. There is the risk that some other services will use it already.

**Comment by AnalogJ** [comment]
This is already possible via the config file when doing a manual install, and via the port mapping when using Docker. That should cover your use case.

I’m going to close this issue for now, but feel free to reopen it if you need more information.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
