### ISSUE TITLE
[BUG] Failed to start webapp binary on armv7l (arm32)

### ISSUE THREAD

**Issue by Zorlin** [AnalogJ/scrutiny#114]
**Describe the bug**
Running Scrutiny 0.3.1 webapp binary doesn't work.

**Log Files**

```
root@clyde:~# /opt/scrutiny/bin/scrutiny-web-linux start --config /opt/scrutiny/config/scrutiny.yaml
2020/10/25 17:21:48 No configuration file found at /scrutiny/config/scrutiny.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                       linux.arm-0.3.1

Start the scrutiny server
2020/10/25 17:21:48 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

Trying to connect to database stored: /opt/scrutiny/config/scrutiny.db

2020/10/25 17:21:48 /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/sqlite3.go:17
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
panic: Failed to connect to database!

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.DatabaseMiddleware(0x8bc468, 0x123c6d0, 0x8beb38, 0x1282700, 0x8bce50)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/sqlite3.go:22 +0x450
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0x123ca30, 0x8beb38, 0x1282700, 0x14)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0x88
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0x123ca30, 0x0, 0x0)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:90 +0x1e4
main.main.func2(0x1239400, 0x4, 0x6)
        /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x144
github.com/urfave/cli/v2.(*Command).Run(0x1258fc0, 0x1239280, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x3c0
github.com/urfave/cli/v2.(*App).RunContext(0x1294000, 0x8b69a0, 0x108e010, 0x107a100, 0x4, 0x4, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x5c0
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x5f8```

**Comment by Zorlin** [comment]
It works fine when I build it myself.

Collector also works fine across arm32 and arm64.

**Comment by AnalogJ** [comment]
Apologies, I'm in the middle of moving, and it took me an unexpectedly long time to get my build system working again. 

I just released a new set of binaries with a proper crosss-compiler: https://github.com/AnalogJ/scrutiny/releases/tag/0.3.5

Can you try the `arm` versions in that release @Zorlin ? 
Thanks!

**Comment by Zorlin** [comment]
I'll have a go some time soon. I've got arm64/aarch64 *and* armv7l hardware now, so I'll make sure both work.

**Comment by Zorlin** [comment]
I haven't gotten to this yet. I will soon, hopefully!

**Comment by Zorlin** [comment]
Hi @AnalogJ :)

I've tested 0.3.5 out, and it works perfectly (at least on arm7 32-bit). I haven't tested arm64/aarch64 just yet, I'll probably do that tomorrow evening.

On a related note, I've updated my [Scrutiny Ansible Playbook](https://github.com/Zorlin/scrutiny-playbook) so that it uses v0.3.5. 

On top of that I've made a special "Ansible role" that automatically sets up smartmontools 7+ :) It will install it from packages if an appropriate version is available, otherwise it will compile it from source and install it. The role works with Ubuntu 16.04, Ubuntu 18.04, Ubuntu 20.04, CentOS 6, CentOS 7, CentOS 8, Debian 9 and Debian 10.

As a result of that rewrite, Scrutiny's collector can now run on all of those platforms (CentOS 6 not tested yet), which makes this playbook much more useful to users.

It's worth nothing that you can't get smartmontools v7+ on CentOS 8 just yet without resorting to any of the following:

* Installing an EL7 package (which is fine but a bit of a hack)
* Compiling and installing from source
* Paying for a getpagespeed subscription and installing it from their repo

Now there's a better option ... when you run the Scrutiny playbook it will automatically take care of that for you. CentOS 8 compatibility!

I'd like to see the playbook in the README at some point - it's much easier and quicker to set things up with the playbook than it is manually. I'd be happy to give you access to the repo if you'd like it, too.

**Comment by AnalogJ** [comment]
Hey @Zorlin 
Thanks for testing this out for me. 
I'm more than happy to reference your playbook for users attempting to install Scrutiny manually. Can you create a PR that adds instructions for your playbook in the `docs` folder?

**Comment by Zorlin** [comment]
Excellent, sure. I think it hugely improves manual installation. Docker is still a great option but yeah 👍 
Only big thing left is a Cron issue I think you're already aware of.

**Comment by AnalogJ** [comment]
Closing this issue, as ARM support seems to be working. If that's incorrect please comment below and I can re-open this issue.
