### ISSUE TITLE
A simplier way to bind in devices

### ISSUE THREAD

**Issue by trapexit** [AnalogJ/scrutiny#117]
/dev/sd* are ephemeral names and hard coding them in Docker is not ideal. I've poked around a bit and not seen anything to make this easier but perhaps replacing or augmenting smartctl --scan with something more bespoke. Maybe allow bind mounting the host /dev into the container somewhere and then crawling the path for devices?

**Comment by AnalogJ** [comment]
Hey @trapexit 
yeah, I'm not a fan of the `/dev/sd*` mounting. However, under the hood Scrutiny uses WWN to uniquely identify drives, so it *shouldn't* matter if the device file assignment changes. 

I did use a `/dev` folder bind mount previously, and it does work (and should continue to work).

**Comment by ptr727** [comment]
Would also like to see an easier way of device discovery, or why specify them at all vs. just discovering them?
As for sd* notation, I use ZFS and ata* notation, so sd* is not used in any deterministic config.

**Comment by AnalogJ** [comment]
The reason you have to specify them is that the docker `--device` parameter doesn't natively support wildcards, so you cant do `--device /dev/sd*` or `--device /dev/ata*`. Even though Scrutiny doesn't actually use the device by those names, they are still necessary (unless you do a straight `-v /dev:/dev` bind mount).

**Comment by AnalogJ** [comment]
I'm going to close this for now as a non-issue. But if someone has a better way for passing all hard disk devices into the container (other than `-v /dev:/dev`, which should already be documented in the README), I'm happy to take another look at this.
