### ISSUE TITLE
Solaris/OmniOS CE Support[FEAT]

### ISSUE THREAD

**Issue by artbird309** [AnalogJ/scrutiny#120]
**Is your feature request related to a problem? Please describe.**
My NAS is running on OmniOS CE (https://omniosce.org/) which is a fork of Solaris then I run Napp-it (https://napp-it.org/index_en.html) on top as a GUI. I would like to run the collector on it to pull data from my drives.

**Describe the solution you'd like**
A collector build that would support Solaris/OmniOS CE.

**Additional context**
I tested it out on my NAS and I just get Killed when I run the collector.
```
users@nas:~/scrutiny$ ./scrutiny\-collector\-metrics\-linux\-amd64 run --api-endpoint "http://localhost:8080"
Killed
users@nas:~/scrutiny$ ./scrutiny\-collector\-metrics\-linux\-amd64
Killed

```

**Comment by AnalogJ** [comment]
Hey @artbird309 is this something that you're still interested in?
I've completely re-vamped my build system (no longer need CGO or multi-arch compliation) so it should be really easy for me to support solaris -- but I have no way of testing the final binary, so I'd need your help.

**Comment by artbird309** [comment]
@AnalogJ yes I am still interested, I am able to test on my system.

**Comment by AnalogJ** [comment]
@artbird309 I tried to add a build for Solaris, but unfortunately one of the libraries I depend on (https://gitlab.com/cznic/sqlite) does not support it. Sorry
