### ISSUE TITLE
[FEAT] Allow specifying the collector's API endpoint in the collector's config file

### ISSUE THREAD

**Issue by djmattyg007** [AnalogJ/scrutiny#124]
**Is your feature request related to a problem? Please describe.**
Not being able to specify the API endpoint in the collector's config file makes things unnecessarily difficult for people looking to package this software for a Linux distribution.

**Describe the solution you'd like**
It should be possible to specify the API endpoint in the config file, along with all of the other settings.

**Additional context**
I don't think it's possible to specify the log file in the config file either. While this is less of a pressing issue, it would still be nice for the sake of consistency.

**Comment by AnalogJ** [comment]
Hey @djmattyg007 

This should definitely be possible. I have a couple of other things I want to fix first, but I'll try to pick this up when I have some time.
