### ISSUE TITLE
[FEAT] Make fonts self-hostable

### ISSUE THREAD

**Issue by djmattyg007** [AnalogJ/scrutiny#125]
**Is your feature request related to a problem? Please describe.**
Right now, if you don't have internet access for some reason, the custom fonts used in the web dashboard won't work. This isn't great for a self-hostable piece of software.

**Describe the solution you'd like**
As per this blog post, there is now essentially zero benefit to using Google Fonts assets directly:

https://wicki.io/posts/2020-11-goodbye-google-fonts/

Therefore, ideally the fonts would just be self-hosted. For those running the dashboard behind a HTTP/2 proxy (like Nginx), the loading performance should improve. It will also make this usable in offline scenarios.

**Comment by AnalogJ** [comment]
Hey @djmattyg007 that's a good idea. Any chance you'd be willing to take on this work and open a PR?

**Comment by djmattyg007** [comment]
Absolutely! I'll let you know how I go with it.

**Comment by djmattyg007** [comment]
Is the Roboto font actually used? The only `font-family` property I could see that included it also includes `Inter`. `Inter` is specified with a higher precedence than `Roboto`, and `Inter` is already self-hosted, so I don't think `Roboto` actually gets used at all.

**Comment by Wdavery** [comment]
Would like to give this a boost. I just experienced a prolonged power outage, and when I did get power back to my server, I was without internet for many days. My go-to drive health monitor is Scrutiny, so not being able to use it offline was a bummer. 
Would love to see this fully usable without an internet connection.

**Comment by AnalogJ** [comment]
fixed in v0.4.8 🎉
