### ISSUE TITLE
[FEAT] Default path for config file in non-docker collector installation

### ISSUE THREAD

**Issue by Klem7ens** [AnalogJ/scrutiny#128]
**Describe the solution you'd like**
When manually installing  collector without a docker it's still looking for config file in /scrutiny/config/. In instruction for manual install collector you suggest putting it in /opt/scrutiny/bin/ maybe config should be checked in /opt/scrutiny/config/ dir?

**Comment by djmattyg007** [comment]
It shouldn't check for a default location at all if `--config` if supplied on the command line.

**Comment by AnalogJ** [comment]
Hey @Klem7ens 
as @djmattyg007 mentioned, just use the `--config` flag. 
I'm going to close this issue for now, but if you still need help, feel free to reopen.

**Comment by djmattyg007** [comment]
Sorry I think my comment might have been misunderstood. It is still checking `/scrutiny/config` even when `--config` is supplied on the command line.

**Comment by Klem7ens** [comment]
:) Sorry for my lack of knowledge English and Github proceudre. At first didn't understood what @djmattyg007 wrote, but checked that `--config` realy works (where to find list of all possible parameters for command line?). Second didn't wrote that `--config` solves "my problem". Third if you use `--config` you still get message:
`2020/12/14 06:25:08 No configuration file found at /scrutiny/config/collector.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                        linux.amd64-0.3.5

2020/12/14 06:25:08 Loading configuration file: /opt/scrutiny/bin/collector.yaml`
