### ISSUE TITLE
[BUG] SMTP Notifications - Mailgun Username Format Not Supported

### ISSUE THREAD

**Issue by andrew-from-toronto** [AnalogJ/scrutiny#129]
**Describe the bug**
SMTP Notifications - Username with @ symbol not supported. Mailgun only offers SMTP auth with usernames of the format `<app name>@<domain>`. I also tried URL encoding the @ however still didn't get any success.

**Expected behavior**
Would expect someway to encode those symbols into the notification string format so that the notifications can work as expected.

I wasn't able to dig up any logs for the SMTP notification either, if there's someway I can provide more info in that way please let me know.

**Comment by AnalogJ** [comment]
Hey @andrew-from-toronto 
I use the [shoutrrr](https://github.com/containrrr/shoutrrr) project for most of my notification handling, including smtp. This definitely sounds like a problem, but unfortunately, I don't think it's something I can fix on my side. Can you open up an issue with them?

**Comment by andrew-from-toronto** [comment]
Thanks, I was able to figure this out finally. URL encode is the answer for anyone else who may end up here.
