### ISSUE TITLE
[BUG] system log flooding

### ISSUE THREAD

**Issue by deathtrip** [AnalogJ/scrutiny#133]
**Describe the bug**
Scrutiny sends far too many messages to the system log. Using systemd's journald i get about 3000(!!!) lines for every check of the SMART data. 
One reason for this is that the data is sent to the journal in json format, but even in a standard format, it would be too much.

I set all the environment variables to disable debugging, changed the log level to "ERROR" in the config file, but still it's the same amount of messages.

**Expected behavior**
Send only the SMART parameter name and it's value to the system log, one per line, or an option to disable it entirely.

**Comment by uchagani** [comment]
whoa is this 3000/per disk?

**Comment by deathtrip** [comment]
No, i have 2 disks on that system.
