### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by dhasial** [AnalogJ/scrutiny#134]
**Is your feature request related to a problem? Please describe.**
I often change the disks in my system and it ends up being a bit of a pain in the ass to `lsblk -f`, and then copy and paste the output to scrutiny, after manually restarting it. 

So - I wrote a tiny script to parse the output of lsblk, grep out the relevant parts (any drives matching the /dev/sd* pattern), make an array from it, and then pass that a variable which is then read as an argument whenever I run scrutiny.

The script to find the matching disks is:
```
#!/bin/zsh
array=(`lsblk --nodeps -n -o name | grep 'sd*'`);

	for i in ${array[@]}
	do
		echo "--device=/dev/$i"
	done
```

And the scrutiny-launching script with the variable is:
```
#!/bin/sh
PATH="$PATH":/home/user/scripts/theabovescript.sh
docker run -it -p 8080:8080 \
-v /run/udev:/run/udev:ro \
--cap-add SYS_RAWIO \
--cap-add SYS_ADMIN \
$(/home/user/theabovescript.sh) \
--name scrutiny \
--restart=unless-stopped \
analogj/scrutiny
```

If you want to change the devices the first script greps out to something other than /dev/sdX, you should change the part after grep to include an appropriate pattern to match them. Hope someone gets use out of this!

**Comment by AnalogJ** [comment]
if you really don't want to do this, you could just bind-mount your `/dev` folder.

I'm not a huge fan of that because of the security implications, but it's an option:

```
docker run -it --rm -p 8080:8080 \
-v /run/udev:/run/udev:ro \
-v /dev/disk:/dev/disk \
--name scrutiny \
--privileged analogj/scrutiny
```
