### ISSUE TITLE
[FEAT] ARM Docker images

### ISSUE THREAD

**Issue by bachya** [AnalogJ/scrutiny#137]
**Is your feature request related to a problem? Please describe.**
Currently, Docker Hub only has `amd64`-based images. These images don't work on ARM-based processors, like those inside Raspberry Pis w/ attached drives, so users are left to build their own.

**Describe the solution you'd like**
It would be great if Docker Hub could have multi-arch images (ideally, images that are automatically published to Docker Hub as a GitHub Action).

**Additional context**
An example GitHub Action from one of my projects that produces multi-arch Docker images: https://github.com/bachya/ecowitt2mqtt/blob/dev/.github/workflows/publish_to_docker_hub.yaml

**Comment by mrhotio** [comment]
you can use `hotio/scrutiny` in the meantime
