### ISSUE TITLE
[BUG] Docker image not updated since 27 Dec

### ISSUE THREAD

**Issue by spupuz** [AnalogJ/scrutiny#140]
Hello there sorry for the dumb question i'm not receiving any update on docker image since 27/12/2020 is it normal? thanks in advance.

**Comment by AnalogJ** [comment]
Hey @spupuz yeah, I haven't had time to work on Scrutiny much the last couple of weeks, real life got in the way. I still use scrutiny myself, and there's a lot of features I want to add. I'll be more active in mid-Feb once my personal obligations are complete.
