### ISSUE TITLE
[FEAT] Support device names changing

### ISSUE THREAD

**Issue by djmattyg007** [AnalogJ/scrutiny#144]
**Is your feature request related to a problem? Please describe.**
I added a new disk to my system, and the device names changed. What was `/dev/sda` is now `/dev/sdb`. The new disk is now `/dev/sda`.

To try to mitigate this going forward, I changed the configuration to use persistent device aliases in `/dev/disk/by-id`. Unfortunately it appears scrutiny doesn't really know how to handle this.

**Describe the solution you'd like**
A way of identifying disks that isn't just their current device name (ie. `/dev/sda`). These device names are not stable. SMART doesn't seem to have any issues recognising devices using their persistent device names, so Scrutiny shouldn't have any issues either.

**Additional context**
I've attached a screenshot from the dashboard that shows what it looks like when using persistent device names.

![image](https://user-images.githubusercontent.com/489338/107221070-3d722a80-6a67-11eb-8f1a-f623df54931a.png)

**Comment by sereeds** [comment]
I was able to add my disks by id.. I think you also need to specify the type..
devices:
  - device: /dev/disk/by-uuid/1751e8d5-f09e-4961-9946-c2d84e1a313c
    type: 'ata'

**Comment by AnalogJ** [comment]
Scrutiny internally references disks by UUID, so you don't have to worry about history/data being lost if the disk name changes. However, you are correct, the UI will show the device names (which can change). 

I think its a good idea to expose the UUID as another field in the details page. I'll keep this open as a feature request.

**Comment by AnalogJ** [comment]
fixed in `v0.4.7` 🎉 

We now support displaying disks with a user select-able identifier:
- Scrutiny Name
- UUID
- WWN
- Device Serial ID
- Device Label

This should no longer be an issue. 

https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#wwn-vs-device-name
