### ISSUE TITLE
[FEAT] Option to disable TLS for Gotify notifications

### ISSUE THREAD

**Issue by ZuluForce** [AnalogJ/scrutiny#146]
**Is your feature request related to a problem? Please describe.**
I have gotify setup on my LAN and since it's only used locally I don't have a certificate for it. Notifications to gotify fail.

**Describe the solution you'd like**
It appears a `DisableTLS` option was introduced into shoutrrr but is not set by scrutiny. My preferred solution would either be through an attribute on the gotify url or another config property in scrutiny.

https://github.com/containrrr/shoutrrr/pull/116

**Comment by artivis** [comment]
If anyone passing by: `gotify://gotify-host/token?disableTLS=yes`
