### ISSUE TITLE
[FEAT] Group drives in UI by system

### ISSUE THREAD

**Issue by claysam75** [AnalogJ/scrutiny#151]
**Describe the solution you'd like**
I pull metrics from three different systems into one scrutiny ui instance, so I have multiple instances of SDA, SDB, SDC etc. To be able to either group drives together by system or even to just be able to label each drive with a friendly name would make it far easier to distinguish each drive in a meaningful way.

**Comment by AnalogJ** [comment]
This functionality is now available. Included in v0.4.7 🎉 

<img width="685" alt="Screen Shot 2022-05-23 at 8 56 14 AM" src="https://user-images.githubusercontent.com/891875/170295975-d31c8059-1578-493f-95da-e793ba564ff9.png">


When provided, the `host-id` is automatically used in the UI to group together disks on the same system. 

The `host-id` is passed from the collector to the web-api when SMART device data is uploaded. There's 3 ways you can set the `host-id`:

- using the collector config file: https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml#L19-L22
- using the `--host-id` collector CLI argument: https://github.com/AnalogJ/scrutiny/blob/master/collector/cmd/collector-metrics/collector-metrics.go#L180-L185
- using the `COLLECTOR_HOST_ID` environemental variable.
