### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Reinitialized** [AnalogJ/scrutiny#156]
I'm in love with the idea and concept of the Scrutiny project, but am concerned in regards to it's upkeep and implementation of additional features. It seems there's been no code contribution nor response to comments since around November 5th of 2020, which is quite a while ago. 

The purpose of this issue is to determine if indeed the original owner has abandoned the project, and what can be done to continue its lifecycle and implementation of features, as I'd love to see this project grow into the powerful tool it showing to be.

**Comment by FingerlessGlov3s** [comment]
I too have been wondering if the project has been abandoned. If AnalogJ can confirm this is the case we can look to appoint a new owner or project organisation.

**Comment by exptom** [comment]
I was also thinking the same. It would be great to keep this project moving forward.

**Comment by Reinitialized** [comment]
I think a fair timeline to determine this project has indeed been abandoned would be 30 days, in which to my understanding of the MIT license, as long as we maintain copyright and license we can fork and organize this project.

**Comment by AnalogJ** [comment]
Hey,
Unfortunately I've been busy with other commitments, so haven't been able to spend much time on Scrutiny in the last couple of months. 

Thankfully thats finally coming to an end and I expect to be able to spend time on Scrutiny soon. On another note, I'm happy to accept PR's if there are bug fixes/features you'd like to contribute :)

**Comment by Reinitialized** [comment]
Glad to hear! Unfortunately, I'm not too familiar with Go, but I may give things a shot.

**Comment by joe-eklund** [comment]
I was wondering the same thing. Glad to hear @AnalogJ hasn't forgotten about us. :)

**Comment by djmattyg007** [comment]
> I think a fair timeline to determine this project has indeed been abandoned would be 30 days

Seriously? Do you not have any commitments in life? Do you have any idea how much pressure you put the maintainer under when you make comments like this?
