### ISSUE TITLE
[BUG] WebUI is slow when collecting SMART data quite regularly

### ISSUE THREAD

**Issue by FingerlessGlov3s** [AnalogJ/scrutiny#158]
**Describe the bug**
I run the scrutiny collector on some servers, and report their disks to scrutiny webui, and is configured with email alerting.
The collectors on each server run every 15 minutes (well was, now its hourly because of this issue), the frequency is so often, this way I'm alerted sooner rather than later to any disk failures or changes in SMART status.

Scrutiny webui now has data for 21 disks, where the oldest data is from the 1st Jan. When I go to load the WebUI it takes rather along time to finish displaying the page, I believe its due to the graph at the bottom and the web browser trying to plot every disk temp, its ever collected, which is a lot since its being collected every 15 minutes for quite a number of drives.

If I load a specific disk, then the pages load instantly, so its just the dashboard which has the issue.

Webui is running in docker on a VM with 4 cores of a Intel Xeon E-2236 CPU @ 3.40GHz.

Loading webui on Brave Browser, 32GB Ram, i9-9900k

**Expected behavior**
WebUI to load at a reasonable speed, and the temperature graph to have scaling or averages out the collected data over a period of time, then ability to go granular is required. Even keeping it simple for now with 3/4 modes

Average graph like this.
1 Year - Daily
6 months - 12 hour
3 months - 3 hour 
1 month - 1 hour
10 days -  30 minutes
48 hours - 5 minutes

**Screenshots**
Network log from Chromium based browser, showing page taking 55 seconds roughly to load.
![image](https://user-images.githubusercontent.com/3495647/114757244-838f8700-9d53-11eb-9ff0-594ee65f33b2.png)

**Log Files**
If related to missing devices or SMART data, please run the `collector` in DEBUG mode, and attach the log file.

Not directly SMART data related, but how often we input in to the database.

**Comment by AnalogJ** [comment]
yeah, scrutiny needs to be optimized to better handle timeseries data. I plan on migrating to a different database solution (and doing better querying for UI results), but I haven't had time to get around to it yet. Sorry about that.

**Comment by FingerlessGlov3s** [comment]
No rush, currently this issue isn't a main concern there's other bugs which need fixing first, I don't mind waiting since I only go in there once in a blue moon.

For me I'd like to see these two issues fixed first, when you get time.
https://github.com/AnalogJ/scrutiny/issues/135 Multiple notifications not sending correctly.
https://github.com/AnalogJ/scrutiny/issues/152 FreeBSD build missing from releases, last seen on 0.3.1

**Comment by Flaxee** [comment]
While waiting for the new database solution, is there any way to disable the temperature graph or logging of temperature completely?
For me it's not really required to see the temperature in Scrutiny (at least not on the dashboard), so if there's a way to disable the collector to send temperatures at all it would be fine for me.

**Comment by AnalogJ** [comment]
This should no longer be a problem with the v0.4.0 release -- which migrated the database to InfluxDB (with automatic down-sampling).
