### ISSUE TITLE
[BUG]Unable to send notify through smtp, got EOF as response

### ISSUE THREAD

**Issue by WizardMeow** [AnalogJ/scrutiny#160]
**Describe the bug**
I attempt to send an email as notify, and it response EOF
After read the code I found the project use a outdated version of shoutrrr - [1da53231b0](https://github.com/containrrr/shoutrrr/tree/1da53231b05aa18a18a58422d72f71d11b4c11ad)
In there I found my problem is: 
my email service provider only support port 465(SSL), and in this version of shoutrrr, it only support plain port or port with StartTLS. 
In this case, even use gmail you must use 587 Port(StartTLS) and 465 Port(SSL) will failed.
https://stackoverflow.com/questions/57063411/go-smtp-unable-to-send-email-through-gmail-getting-eof
In latest version of shoutrrr, everything in good.

**Comment by ghost** [comment]
Ha, I still remember asking the Shoutrrr devs to implement this feature because of Scrutiny: https://github.com/containrrr/shoutrrr/issues/68
