### ISSUE TITLE
"exec user process caused: exec format error" when running the collector

### ISSUE THREAD

**Issue by Draxter** [AnalogJ/scrutiny#166]
I am trying to run the collector variant of scrutiny as per the example in your documentation:

`docker run -it --rm \
-v /run/udev:/run/udev:ro \
--cap-add SYS_RAWIO \
--device=/dev/sda \
--device=/dev/sdb \
-e SCRUTINY_API_ENDPOINT=http://10.10.0.21:8080 \
--name scrutiny-collector \
analogj/scrutiny:collector`

which results in the following error from docker: "exec user process caused: exec format error"

Docker version: 20.10.6
image: scrutiny:collector
Image digest: 4afdd870ac34

**Comment by joe-eklund** [comment]
I have seen this error before on other projects and it was fixed by adding ` #!/bin/bash` to the entrypoint sh file as the very first line. @Draxter Are you able to clone the repo, add that to the top of the `scrutiny/docker/entrypoint-collector.sh` file, then do a docker build to try out the fix?

**Comment by AnalogJ** [comment]
This could also be related to a binary architecture mismatch. 
Is your server running on an ARM processor or a BSD flavor of Linux?

**Comment by Draxter** [comment]
@AnalogJ Running on a x86_64 CPU on Centos 8 Linux.

**Comment by AnalogJ** [comment]
crap. I just pulled the latest image, and I see the same issue
I wonder if something changed in my build/CI

**Comment by AnalogJ** [comment]
@joe-eklund  was totally right, I was missing a shebang in my entrypoint.

**Comment by AnalogJ** [comment]
this should be fixed now. Closing.
