### ISSUE TITLE
[FEAT] Use WAL mode for sqlite db

### ISSUE THREAD

**Issue by zilexa** [AnalogJ/scrutiny#172]
A minor improvement:
Instead of DELETE mode, use WAL mode. This is better for btrfs, EXT4 etc. 
See here: 
https://wiki.tnonline.net/w/Blog/SQLite_Performance_on_Btrfs

A user can do this manually now by following the instructions on that page, via `PRAGMA journal_mode=WAL;`.

**Comment by AnalogJ** [comment]
I'm actually in the middle of a partial rewrite to move the metrics collection to an InfluxDB. 

While the SQLite db will still be around for device metadata, the meat of the application data will live in InfluxDB. 

I'll definitely take a look at the WAL optimization for SQLite, but if you have any OS-agnostic optimizations for InfluxDB, I'm all ears.

**Comment by zilexa** [comment]
I think InfluxDB is already optimized for modern filesystems like BtrFS, it uses WAL mode when it makes sense, as far as I understand from the documentation. But I am no expert. 
For SQLite, WAL mode is basically THE choice unless you use EXT2 or FAT32.

**Comment by PrplHaz4** [comment]
For me, adding a heavy dependency like InfluxDB erodes a bit at the value proposition of this app (but my deployment is very small).

@AnalogJ Any insight into how many drives/months of data were the breaking point of SQLite?

**Comment by zilexa** [comment]
I also hope you allow users to choose db type and InfluxDB is optional.
There is no performance improvement unless you go over 20K-30K or perhaps even 100k.

**Comment by AnalogJ** [comment]
Closing this issue now that Scrutiny has migrated to InfluxDB.
