### ISSUE TITLE
[FEAT] InfluxDB Timeseries DB

### ISSUE THREAD

**Issue by AnalogJ** [AnalogJ/scrutiny#173]
https://github.com/CrossEngage/disk-health-checker/blob/master/smartctl.go

**Comment by beaussan** [comment]
What is the progress on this? I'm seeing the warning in the Readme about it, but I wonder how close to completion is it?

**Comment by AnalogJ** [comment]
the `influxdb` branch is still a work in progress. I have that branch working on my personal server.

**Comment by AnalogJ** [comment]
Closing, the `influxdb` branch has been merged for a while. Released as `v0.4.x`
