### ISSUE TITLE
[BUG] Slack notifications appear to be broken

### ISSUE THREAD

**Issue by millermarkj** [AnalogJ/scrutiny#179]
**Describe the bug**
Slack notifications appear to be broken. 

When attempting to send slack notifications, they consistently fail:

```
# curl -X POST http://localhost:8080/api/health/notify
{"errors":["thumb_url is not a valid config key [color title]"],"success":false}
```

This is after figuring out how to enable them, which could use a bit more documentation. After digging around, I was able to determine that scrutiny is using shoutrrr for notifications. The documentation for slack notifications on shoutrrr is equally non-existent and I've opened an issue with them about it.

Nevertheless, slack should be configured using webhooks: https://api.slack.com/messaging/webhooks

A properly formatted slack connection string would look something like 

    slack://A1B234CDE/Z12345Y123Q/ABCD1lmnoPqr0tuVwXYz

Unfortunately, this doesn't work. Slack notifications all fail. 

```
scrutiny    | time="2021-05-11T08:12:46-04:00" level=error msg="One or more errors occurred while sending notifications for slack://[redacted]:"
scrutiny    | time="2021-05-11T08:12:46-04:00" level=error msg="[thumb_url is not a valid config key [color title]]"
scrutiny    | time="2021-05-11T08:12:48-04:00" level=error msg="One or more notifications failed to send successfully. See logs for more information."
scrutiny    | time="2021-05-11T08:12:48-04:00" level=error msg="An error occurred while sending test notification thumb_url is not a valid config key [color title]"
scrutiny    | time="2021-05-11T08:12:48-04:00" level=error msg="172.21.0.7 - e89333b767f0 [11/May/2021:08:12:48 -0400] \"POST /api/health/notify\" 500 80 \"\" \"curl/7.65.1-DEV\" (2111ms)" clientIP=172.21.0.7 hostname=e89333b767f0 latency=2111 method=POST path=/api/health/notify referer= respLength=80 statusCode=500 userAgent=curl/7.65.1-DEV
```

**Comment by AnalogJ** [comment]
Thanks, this looks like a simple fix:

https://github.com/AnalogJ/scrutiny/blob/fc3d6a33e30185ed147e676aa5d6c0f64b813c00/webapp/backend/pkg/notify/notify.go#L261

I think just deleting that line will fix the issue.

**Comment by mriffle** [comment]
This issue still exists in the latest release on Docker Hub.
