### ISSUE TITLE
[FEAT] Notification if a hard drive status has not been updated recently

### ISSUE THREAD

**Issue by joe-eklund** [AnalogJ/scrutiny#181]
**Is your feature request related to a problem? Please describe.**
I use a hub / spoke model to report the status of two machines' drives. Today I noticed one of machine's drives hadn't been updated in a couple weeks.

**Describe the solution you'd like**
If a drive's S.M.A.R.T. status has not been updated for something like 24 hours (or maybe this is customizable), send a notification saying the drive status is out of date.

**Comment by AnalogJ** [comment]
So I intially thought that this would make sense to implement within Scrutiny, but I'm reconsidering now. 

Scrutiny has a couple of different deployment modes and building in a heartbeat/cron system for the webserver would make it more complicated than I'd like. 

I think the best option for users is to integrate the collector with a (cloud or self-hosted) monitoring system like [`healthchecks.io`](https://healthchecks.io/). 

I'm going to close this as `wontfix` for now, but happy to discuss further & potentially reopen if there's more interest.
