### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by djmattyg007** [AnalogJ/scrutiny#184]
Please add a changelog so people can have confidence in knowing what has changed when they upgrade.

I recommend following the Keep A Changelog standard:

https://keepachangelog.com/

**Comment by AnalogJ** [comment]
great idea! Once this influxDB migration work is complete, the commits/changes should be more controlled

**Comment by AnalogJ** [comment]
I'm not quite following the "Keep A Changelog" standard, but new releases now have a pretty descriptive list of changes
