### ISSUE TITLE
Issue with Adapec RAID not pulling all S.M.A.R.T. stats

### ISSUE THREAD

**Issue by mcesnik** [AnalogJ/scrutiny#189]
So this isn't so much a problem with `smartctl` as it is with Adaptec. I am creating this issue instead of a PR because the solution is a bit of a hack and I just want to provide insight and leave it at that.

**NB** - Since this solution uses Python (as I do not know Go) you will need to create your own Dockerfile.

First I need to create a  wrapper to `smartctl` that would go into `/scrutiny/bin`. You also need the `arcconf` binary to be in the `/scrutiny/bin`.

```
#!/usr/bin/python3

import os
import sys
import json
import xml.etree.ElementTree as ET

arcconf = "/scrutiny/bin/arcconf getsmartstats 1"
smartctl = "/usr/sbin/smartctl"

smart_stats = {
    1: "Raw_Read_Error_Rate",
    3: "Spin_Up_Time",
    4: "Start_Stop_Count",
    5: "Reallocated_Sector_Ct",
    7: "Seek_Error_Rate",
    9: "Power_On_Hours",
    10: "Spin_Retry_Count",
    11: "Calibration_Retry_Count",
    12: "Power_Cycle_Count",
    192: "Power-Off_Retract_Count",
    193: "Load_Cycle_Count",
    194: "Temperature_Celsius",
    196: "Reallocated_Event_Count",
    197: "Current_Pending_Sector",
    198: "Offline_Uncorrectable",
    199: "UDMA_CRC_Error_Count",
    200: "Multi_Zone_Error_Rate"
}

if __name__ == "__main__":
    # Run smartctl and load the Json into memory
    cmd = "%s %s" % (smartctl, " ".join(sys.argv[1:]))
    output = json.loads("".join( [ i.strip() for i in os.popen(cmd).readlines() ] ))

    # Check to see if this device is actually for aacraid and do this 'extra' work if so
    aacraid = [arg for arg in sys.argv if arg.startswith("aac")]

    if any(aacraid):
        # Get the device id 
        id = int(aacraid[0].split(",")[3])

        # Call arcconf getsmartstats for controller 1 and then get the XML we care about...
        stats = [dev for dev in ET.fromstring("".join([i.strip() for i in os.popen(arcconf).readlines() if i[0] == "<"][0:-2])) if int(dev.attrib["id"]) == id ][0]

        # Now get the attributes for the device we extracted
        attributes = [ (int(stat.attrib["id"], 16), stat.attrib["normalizedCurrent"], stat.attrib["normalizedWorst"], stat.attrib["rawValue"]) for stat in stats ]

        # Write the ata_smart_attributes (I have no idea if these matter for a SCSI or not)
        output["ata_smart_attributes"] = {
          "revision": 16,
          "table": [ {
                      "id": attribute[0],
                      "name": smart_stats[attribute[0]],
                      "current": int(attribute[1]),
                      "worst": int(attribute[2]),
                      "raw": { "value": int(attribute[3]), "string": attribute[3] }
                     } for attribute in attributes if attribute[0] in smart_stats ]
        }

        # And write these additional properties too (scrutiny uses these for sure)
        output["temperature"] = { "current": [ int(a[3]) for a in attributes if a[0] == 194 ][0] }
        output["power_on_time"] = { "hours": [ int(a[3]) for a in attributes if a[0] == 9 ][0] }
        output["power_cycle_count"] = [ int(a[3]) for a in attributes if a[0] == 12 ][0]

    # Dump the whole thing to stdout just like smartctl
    print(json.dumps(output, indent=4))
```

For reference, this my Dockerfile

```
FROM analogj/scrutiny

EXPOSE 8080

RUN apt -y update && apt -y upgrade
RUN apt -y install tzdata python3

COPY arcconf /scrutiny/bin
RUN chmod 755 /scrutiny/bin/arcconf

COPY smartctl /scrutiny/bin
RUN chmod 755 /scrutiny/bin/smartctl
```

After building a new image using `docker build` you can create a container as per the standard documentation but before you do add the following to a `collector.yaml` and include that in the `/scrutiny/config` as a volume mount.

```
devices:
  - device: /dev/sd-
    type:
      - aacraid,0,0,0
      - aacraid,0,0,1
      - ... the rest of your drives here
```
I hope this helps someone save some time if they are using some legacy Adaptec cards like me :-)

**Comment by mcesnik** [comment]
Also, I noticed that although $TZ is supposed to be supported the tzdata package is not installed.

**Comment by AnalogJ** [comment]
@mcesnik Appreciate your patience and thanks for the helpful python script. 
 
The `beta` branch (and `beta-*` images) support a new collector config file option: [`commands.metrics_smartctl_bin`](https://github.com/AnalogJ/scrutiny/blob/beta/example.collector.yaml#L76)
which can be use to customize the smartctl binary path.

I'll also add this to the documentation section. 

Thanks again!

**Comment by AnalogJ** [comment]
though, I am curious why is this necessary? `smartctl` is supposed to support Adaptec raid devices natively. Whats the output of commands like: [`smartctl -a -d "aacraid,0,0,1" /dev/sda`](https://serverfault.com/a/935006)

**Comment by mcesnik** [comment]
Hey @AnalogJ been a while, not sure why I never got any notifications of your reply but here is the output of `smartctl` 
```
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.15.0-176-generic] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               WDC
Product:              WD2002FAEX-0
Revision:             05.0
Compliance:           SPC-3
User Capacity:        2,000,398,934,016 bytes [2.00 TB]
Logical block size:   512 bytes
Serial number:        WD-XXXXXXXXXXX
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Sat May  2 09:10:55 2026 EDT
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Disabled or Not Supported

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Error Counter logging not supported

Device does not support Self Test logging
```

As you can see the temperatures report as 0 but when using `arcconf getsmartstats` it actually pulls those values

```
	<PhysicalDriveSmartStats channel="0" id="2" nonSpinning="false" isDescriptionAvailable="true" >
		<Attribute id="0x01" name="Read Error Rate" normalizedCurrent="200" normalizedWorst="200" thresholdValue="51" rawValue="1" Status="OK" />
		<Attribute id="0x03" name="Spin-Up Time in millisecs" normalizedCurrent="253" normalizedWorst="253" thresholdValue="21" rawValue="8791" Status="OK" />
		<Attribute id="0x04" name="Start/Stop Count" normalizedCurrent="79" normalizedWorst="79" thresholdValue="0" rawValue="21934" Status="OK" />
		<Attribute id="0x05" name="Reallocated Sectors Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="140" rawValue="0" Status="OK" />
		<Attribute id="0x07" name="Seek Error Rate" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
		<Attribute id="0x09" name="Power-On Hours" normalizedCurrent="1" normalizedWorst="1" thresholdValue="0" rawValue="92491" Status="OK" />
		<Attribute id="0x0A" name="Spin Retry Count" normalizedCurrent="100" normalizedWorst="100" thresholdValue="0" rawValue="0" Status="OK" />
		<Attribute id="0x0B" name="Recalibration Retries" normalizedCurrent="100" normalizedWorst="100" thresholdValue="0" rawValue="0" Status="OK" />
		<Attribute id="0x0C" name="Power Cycle Count" normalizedCurrent="100" normalizedWorst="100" thresholdValue="0" rawValue="394" Status="OK" />
		<Attribute id="0xC0" name="Power-off Retract Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="384" Status="OK" />
		<Attribute id="0xC1" name="Load/Unload Cycle Count" normalizedCurrent="193" normalizedWorst="193" thresholdValue="0" rawValue="21549" Status="OK" />
		<Attribute id="0xC2" name="Current Internal Temperature" normalizedCurrent="120" normalizedWorst="100" thresholdValue="0" rawValue="32" Status="OK" />
		<Attribute id="0xC4" name="Reallocation Event Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
		<Attribute id="0xC5" name="Current Pending Sector Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
		<Attribute id="0xC6" name="Uncorrectable Sector Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
		<Attribute id="0xC7" name="UltraDMA CRC Error Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
		<Attribute id="0xC8" name="Multi-Zone Error Rate" normalizedCurrent="200" normalizedWorst="199" thresholdValue="0" rawValue="9" Status="OK" />
	</PhysicalDriveSmartStats>
```

**Comment by kaysond** [comment]
> Hey [@AnalogJ](https://github.com/AnalogJ) been a while, not sure why I never got any notifications of your reply but here is the output of `smartctl`
> 
> ```
> smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.15.0-176-generic] (local build)
> Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org
> 
> === START OF INFORMATION SECTION ===
> Vendor:               WDC
> Product:              WD2002FAEX-0
> Revision:             05.0
> Compliance:           SPC-3
> User Capacity:        2,000,398,934,016 bytes [2.00 TB]
> Logical block size:   512 bytes
> Serial number:        WD-XXXXXXXXXXX
> Device type:          disk
> Transport protocol:   SAS (SPL-3)
> Local Time is:        Sat May  2 09:10:55 2026 EDT
> SMART support is:     Available - device has SMART capability.
> SMART support is:     Enabled
> Temperature Warning:  Disabled or Not Supported
> 
> === START OF READ SMART DATA SECTION ===
> SMART Health Status: OK
> Current Drive Temperature:     0 C
> Drive Trip Temperature:        0 C
> 
> Error Counter logging not supported
> 
> Device does not support Self Test logging
> ```
> 
> As you can see the temperatures report as 0 but when using `arcconf getsmartstats` it actually pulls those values
> 
> ```
> 	<PhysicalDriveSmartStats channel="0" id="2" nonSpinning="false" isDescriptionAvailable="true" >
> 		<Attribute id="0x01" name="Read Error Rate" normalizedCurrent="200" normalizedWorst="200" thresholdValue="51" rawValue="1" Status="OK" />
> 		<Attribute id="0x03" name="Spin-Up Time in millisecs" normalizedCurrent="253" normalizedWorst="253" thresholdValue="21" rawValue="8791" Status="OK" />
> 		<Attribute id="0x04" name="Start/Stop Count" normalizedCurrent="79" normalizedWorst="79" thresholdValue="0" rawValue="21934" Status="OK" />
> 		<Attribute id="0x05" name="Reallocated Sectors Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="140" rawValue="0" Status="OK" />
> 		<Attribute id="0x07" name="Seek Error Rate" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
> 		<Attribute id="0x09" name="Power-On Hours" normalizedCurrent="1" normalizedWorst="1" thresholdValue="0" rawValue="92491" Status="OK" />
> 		<Attribute id="0x0A" name="Spin Retry Count" normalizedCurrent="100" normalizedWorst="100" thresholdValue="0" rawValue="0" Status="OK" />
> 		<Attribute id="0x0B" name="Recalibration Retries" normalizedCurrent="100" normalizedWorst="100" thresholdValue="0" rawValue="0" Status="OK" />
> 		<Attribute id="0x0C" name="Power Cycle Count" normalizedCurrent="100" normalizedWorst="100" thresholdValue="0" rawValue="394" Status="OK" />
> 		<Attribute id="0xC0" name="Power-off Retract Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="384" Status="OK" />
> 		<Attribute id="0xC1" name="Load/Unload Cycle Count" normalizedCurrent="193" normalizedWorst="193" thresholdValue="0" rawValue="21549" Status="OK" />
> 		<Attribute id="0xC2" name="Current Internal Temperature" normalizedCurrent="120" normalizedWorst="100" thresholdValue="0" rawValue="32" Status="OK" />
> 		<Attribute id="0xC4" name="Reallocation Event Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
> 		<Attribute id="0xC5" name="Current Pending Sector Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
> 		<Attribute id="0xC6" name="Uncorrectable Sector Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
> 		<Attribute id="0xC7" name="UltraDMA CRC Error Count" normalizedCurrent="200" normalizedWorst="200" thresholdValue="0" rawValue="0" Status="OK" />
> 		<Attribute id="0xC8" name="Multi-Zone Error Rate" normalizedCurrent="200" normalizedWorst="199" thresholdValue="0" rawValue="9" Status="OK" />
> 	</PhysicalDriveSmartStats>
> ```

Please try the latest version and if you're still having a problem open a new issue triage discussion here: https://github.com/AnalogJ/scrutiny/discussions/new?category=issue-triage
