### ISSUE TITLE
 Add OS specific packages (for popular NAS/Home Server)

### ISSUE THREAD

**Issue by AnalogJ** [AnalogJ/scrutiny#19]
- [ ] freenas/truenas
- [ ] unraid
- [ ] ESXI
- [ ] Proxmox
- [ ] Synology
- [ ] LXC container
- [ ] OMV
- [ ] Amahi
- [ ] QNAP

**Comment by TheCatLady** [comment]
QNAP is pretty popular too! :)  Though personally I'd probably choose to just run a container.

**Comment by ronron555** [comment]
+1 for QNAP, I have a QNAP TS-431x2 NAS and would like to see instructions :)
tomorrow I will try to use the arm32 binaries on it

**Comment by AnalogJ** [comment]
I'll add QNAP to the list.

**Comment by AnalogJ** [comment]
closing this, as I'm tracking support & installation guides in https://github.com/AnalogJ/scrutiny/blob/master/docs/SUPPORTED_NAS_OS.md

If you'd like to contribute a guide for your OS of choice, please open a PR 🥳 

Thanks!

**Comment by Anutrix** [comment]
Waiting for guides for either on Proxmox, running on LXC and OMV (OpenMediaVault).|
Thx.
