### ISSUE TITLE
[FEAT] SMART Tests Detailed

### ISSUE THREAD

**Issue by wfarid777** [AnalogJ/scrutiny#193]
My server does automated SMART tests (Short and long) - it would be great to be able to track these live as they are happening.

**Comment by AnalogJ** [comment]
Not a bad idea, but Scrutiny follows a hub & spoke model, where the `collectors` are not directly accessible from the `web` service (for various reasons, including security). So, it'll be hard to get the status of a long-running smartctl test, unless the data is continuously streamed to the `web` service. 

I'll leave this as an open enhancement.

**Comment by AnalogJ** [comment]
closing as a dupe of #12
