### ISSUE TITLE
[BUG] - Sort By is greyed out

### ISSUE THREAD

**Issue by Zerobian** [AnalogJ/scrutiny#194]
"Sort By" in the settings is greyed out for name and label:

![image](https://user-images.githubusercontent.com/73997132/134756336-30bf1f4e-778e-474f-b2fa-14afa7b9ba36.png)

Additional, where can the label be set?

**Comment by AnalogJ** [comment]
not a bug, this functionality is still WIP. No timelines yet unfortunately. I need to finish the refactor for the Database backend first.

**Comment by raulfg3** [comment]
good feature, i'll wait it for a long time.

Any news?

**Comment by AnalogJ** [comment]
fixed in v0.4.7 🎉 

<img width="585" alt="Screen Shot 2022-05-23 at 9 11 31 AM" src="https://user-images.githubusercontent.com/891875/170296128-63770b11-ebe7-4581-9b2f-7ddbcadc9357.png">

**Comment by raulfg3** [comment]
Thanks a lot, i'll wait it a lot, because I prefer order my disk by Name and not by status.


Good work
