### ISSUE TITLE
[BUG] Looking for clarification on when drives are marked as failed

### ISSUE THREAD

**Issue by joe-eklund** [AnalogJ/scrutiny#195]
**Describe the bug**
Can I get some clarification on when drives are marked as failing on the home screen, and as such, would send me an alert?

**Expected behavior**
I have a drive that has increasing realloaction sectors, which is typical of a drive that is on it's way out the door (whether that is today or in a year). Considering I still have it under warranty, I plan on RMAing the drive. Why does Scrutiny not mark this drive as failed overall even though it is failing one of the critical SMART attributes when looking on the detail page?

I have actually never had any drive listed as "failed" on the home page, even though I had some die and ZFS report as faulted. SImilar issue, where there were critical SMART errors that failed on the detailed page, but nothing on the home page and no alert was sent.

I have verified alerts work through discord by sending the test notification and that went through no problem.

The only thing I can think of is that the overall SMART health assessment says: PASSED. Is this what is displayed on the home page? If that is the case, being able to configure alerts and the home page status of PASSED vs FAILED based on any critical SMART attributes failing would be preferable to the overall health of SMART reported through something like smartctl. Often times I want to replace the drive as soon as I see some critical SMART attributes failing. 

Not sure if this is expected behavior or a bug? If expected, I would at least like to get alerts when any critical SMART attribute starts failing.

**Screenshots**

<img width="670" alt="Screen Shot 2021-10-05 at 5 15 01 PM" src="https://user-images.githubusercontent.com/8761687/136121169-523dc0ec-e501-4d21-a60c-dd832cbf34b4.png">

<img width="1019" alt="Screen Shot 2021-10-05 at 5 15 11 PM" src="https://user-images.githubusercontent.com/8761687/136121177-45ddc08d-ddf9-44e7-a5cf-4e1da1cc133b.png">

**Log Files**
N/A

**Comment by AnalogJ** [comment]
this is definitely an issue, but its a dupe of #72

closing to consolidate discussion in one thread.

basically the Dashboard shows the "S.M.A.R.T" status for the disk, while the Details page shows the "Scrutiny" status.
