### ISSUE TITLE
[FEAT] - Notifications on fail/prefail - Email

### ISSUE THREAD

**Issue by ePHDiSK** [AnalogJ/scrutiny#196]
**Is your feature request related to a problem? Please describe.**
Wonderful utility but I would need to check this to know when there is an issue.  

**Describe the solution you'd like**
I would like to have a notification section.  Email would be my main request but there are also other chat options like Discord that can integrate for notifications as well.  It could just be simple like "Check /dev/sdg" or have advanced details like "/dev/sdg 
5 (0x05) | Reallocated Sectors Count - 15 / Threshold is 5" and have the device serial number.  

**Additional context**
Thank you for putting this together.  This is a great visual tool and very fast and simple.

**Comment by AnalogJ** [comment]
notifications already exist using https://github.com/AnalogJ/scrutiny/blob/influxdb/example.scrutiny.yaml#L44-L60

Is that not sufficient?

**Comment by AnalogJ** [comment]
Closing this issue as Scrutiny already supports notifications:
https://github.com/AnalogJ/scrutiny#notifications

Feel free to comment/reopen this issue if you have any further questions.
