### ISSUE TITLE
[BUG] Release binary missing?

### ISSUE THREAD

**Issue by martadinata666** [AnalogJ/scrutiny#198]
**Describe the bug**
Many binary missing at release 0.3.13

**Expected behavior**
Same as release 0.3.12

**Screenshots**
![0312](https://res.cloudinary.com/dedyms/image/upload/v1635157703/issues/0312_djnuqv.png)
![0313](https://res.cloudinary.com/dedyms/image/upload/v1635157703/issues/0313_vcstgm.png)

```

Is collector now using `freebsd` as default?

**Comment by AnalogJ** [comment]
Sorry about that @martadinata666, I was making changes to the release workflow jobs.
