### ISSUE TITLE
Collector endpoint should default to what's defined in the config file

### ISSUE THREAD

**Issue by RealOrangeOne** [AnalogJ/scrutiny#2]
When running the collector with no arguments, it assumes the API is at `localhost:8080`, which when not using the omnibus container, it's not.

It'd be great if this could default to the value from the config file, so it doesn't need to be overriden when calling it manually.

https://github.com/AnalogJ/scrutiny/blob/1def7d334c153fb866bebfe1a37efe3291e3dbab/collector/cmd/collector-metrics/collector-metrics.go#L104

This would probably also remove the need for the environment special case in the background job:

https://github.com/AnalogJ/scrutiny/blob/master/rootfs/scrutiny/jobber/jobber.yaml#L22

**Comment by AnalogJ** [comment]
Looks like I broke a couple things after I moved the Dockerfiles
I’ll have to fix this in the evening. Sorry about that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AnalogJ** [comment]
The idea with the collector container is that it may be on a completely different host than the webapp container. So it wouldn't necessarily have access config file. In addition, the collector is designed to be super simple, without any real configuration -- all it needs to know is the API endpoint.

The API endpoint is configurable by setting `-e SCRUTINY_API_ENDPOINT=` when you start the collector docker image. 

Is the a usecase where that's not sufficient?

**Comment by RealOrangeOne** [comment]
That's fine for the schedule, however if you run the collector manually as instructed, the environment variable isn't used unless you explicitly pass it to the command line

**Comment by AnalogJ** [comment]
Ah good point. I fixed the collector(s) so that they check for the env variable directly, and cleaned up the scheduler config file. 

I also added some documentation to the README for hub/spoke deployment:

```
docker run -it --rm -p 8080:8080 \
--name scrutiny-web \
analogj/scrutiny:web

docker run -it --rm \
-v /run/udev:/run/udev:ro \
-v /dev/disk:/dev/disk \
-e SCRUTINY_API_ENDPOINT=http://SCRUTINY_WEB_IPADDRESS:8080 \
--name scrutiny-collector \
--privileged analogj/scrutiny:collector
```

The new images are still building on Docker Hub, but once that's completely this should work for you.
