### ISSUE TITLE
[BUG] Smartctl errors and no data in interface

### ISSUE THREAD

**Issue by DarkObscurity** [AnalogJ/scrutiny#200]
**Describe the bug**
After setting up the container and running the collector manually, I received multiple errors regarding the Metrics, the error codes where 62 and 64. I also had to run the container privileged to get it to work, and I was curious if this is safe and really necessary.

And a disk is showing up with a question mark in the web interface (See screenshot attached)

Can I fix these errors, or am I doing something wrong?

(I'm running Scrunity on Unraid from linuxserver)

**Expected behavior**
No errors during from the collector and not running the container privileged.

**Screenshots**
![image](https://user-images.githubusercontent.com/29317995/139532636-9aed125f-724d-40dd-a450-d57932aea72b.png)

**Log Files**
If related to missing devices or SMART data, please run the `collector` in DEBUG mode, and attach the log file.

```
docker run -it --rm -p 8080:8080 \
-v /run/udev:/run/udev:ro \
--cap-add SYS_RAWIO \
--device=/dev/sda \
--device=/dev/sdb \
-e DEBUG=true \
-e COLLECTOR_LOG_FILE=/tmp/collector.log \
-e SCRUTINY_LOG_FILE=/tmp/web.log \
--name scrutiny \
analogj/scrutiny

# in another terminal trigger the collector
docker exec scrutiny scrutiny-collector-metrics run

# then use docker cp to copy the log files out of the container.
docker cp scrutiny:/tmp/collector.log collector.log
docker cp scrutiny:/tmp/web.log web.log

```
[collector.log](https://github.com/AnalogJ/scrutiny/files/7446464/collector.log)
[web.log](https://github.com/AnalogJ/scrutiny/files/7446465/web.log)

**Comment by AnalogJ** [comment]
Please see https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md

If those instructions do not solve your issue, feel free to reopen this issue.
