### ISSUE TITLE
[BUG] Collector: pfsense "Command not found."

### ISSUE THREAD

**Issue by BadCo-NZ** [AnalogJ/scrutiny#201]
**Describe the bug**
When running the collector from pfsense shell, as admin or root, after making it exectuable, I get the error "Command not found."
To be fair, I'm not fluent with *BSD, so I'm not sure if this is even possible on pfsense.

**Expected behavior**
Collector should run.

**Screenshots**
NA

**Log Files**
```
[2.5.2-RELEASE][admin@pfsense]/opt/scrutiny/bin: ls -l
total 5
-rwxrwxrwx  1 root  wheel  648 Nov  8 11:08 scrutiny-collector-metrics-freebsd-amd64
```
```
[2.5.2-RELEASE][admin@pfsense]/opt/scrutiny/bin: scrutiny-collector-metrics-freebsd-amd64 
scrutiny-collector-metrics-freebsd-amd64: Command not found.
```
and
```
[2.5.2-RELEASE][admin@pfsense]/opt/scrutiny/bin: su root
# scrutiny-collector-metrics-freebsd-amd64 
su: scrutiny-collector-metrics-freebsd-amd64: not found
```

**Comment by varunsridharan** [comment]
@BadCo-NZ i was able to get it working. 

i just followed the docs and got it working.

**Comment by BadCo-NZ** [comment]
> @BadCo-NZ i was able to get it working.
> 
> i just followed the docs and got it working.

Thanks @varunsridharan. Did you do anything special? Could you describe your steps?

**Comment by varunsridharan** [comment]
@BadCo-NZ sure

I followed the below steps

1. Login to PFSense via SSH using default `admin`
2. Select Option 8 `Shell`
3. run `mkdir -p /opt/scrutiny/bin`
4. Download & upload the FREEBSD file to `/opt/scrutiny/bin`
4. Got to `/opt/scrutiny/bin/` and run `chmod +x scrutiny-collector-metrics-freebsd-amd64`
5. RUN `/opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --api-endpoint "https://endpoint.com" `
***Make sure to change the endpoint url and also make sure the file names match***

And for scheduling i installed Cron package in pfsense webui and configured my custom cron cmd
![image](https://user-images.githubusercontent.com/1884287/141769120-b60b9d5b-de46-470d-8e6a-378c79b3c6af.png)

**Comment by BadCo-NZ** [comment]
> @BadCo-NZ sure
> 
> I followed the below steps
> 
>     1. Login to PFSense via SSH using default `admin`
> 
>     2. Select Option 8 `Shell`
> 
>     3. run `mkdir -p /opt/scrutiny/bin`
> 
>     4. Download & upload the FREEBSD file to `/opt/scrutiny/bin`
> 
>     5. Got to `/opt/scrutiny/bin/` and run `chmod +x scrutiny-collector-metrics-freebsd-amd64`
> 
>     6. RUN `/opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --api-endpoint "https://endpoint.com" `
>        _**Make sure to change the endpoint url and also make sure the file names match**_
> 
> 
> And for scheduling i installed Cron package in pfsense webui and configured my custom cron cmd ![image](https://user-images.githubusercontent.com/1884287/141769120-b60b9d5b-de46-470d-8e6a-378c79b3c6af.png)

Thanks for the detailed write up. Unfortunately that was how I tried it, with no success :(

```
[2.5.2-RELEASE][admin@pfsense]/root: ls -l /opt/scrutiny/bin/
total 5
-rwxrwxrwx  1 root  wheel  648 Nov  8 11:08 scrutiny-collector-metrics-freebsd-amd64
[2.5.2-RELEASE][admin@pfsense]/root: /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://x.x.x.x:8080"
/opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64: Command not found.
```

**Comment by AnalogJ** [comment]
Are you sure you're typing the correct command?

`scrutiny-collector-metrics-freebsd-amd64` vs `scrutiny-collector-metrics-linux-amd64`

**Comment by BadCo-NZ** [comment]
> Are you sure you're typing the correct command?
> 
> `scrutiny-collector-metrics-freebsd-amd64` vs `scrutiny-collector-metrics-linux-amd64`

Ha, okay that time was a lazy copy/paste.

Although this time, I got a different output:

```
[2.5.2-RELEASE][admin@pfsense]/root: /opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --api-endpoint "http://ipaddress:8080"
/opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64: 1: Syntax error: redirection unexpected (expecting word)
```

Keep in mind, I have done this on three linux machines and also a TrueNAS box already, all one after the other. So I might have misquoted my commands, but I definitely have followed the documentation :)

**Comment by varunsridharan** [comment]
> 
> 
> > Are you sure you're typing the correct command?
> > `scrutiny-collector-metrics-freebsd-amd64` vs `scrutiny-collector-metrics-linux-amd64`
> 
> Ha, okay that time was a lazy copy/paste.
> 
> Although this time, I got a different output:
> 
> ```
> [2.5.2-RELEASE][admin@pfsense]/root: /opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --api-endpoint "http://ipaddress:8080"
> /opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64: 1: Syntax error: redirection unexpected (expecting word)
> ```
> 
> Keep in mind, I have done this on three linux machines and also a TrueNAS box already, all one after the other. So I might have misquoted my commands, but I definitely have followed the documentation :)

I got the same error. but i totally blank now on what i did for it. let me retry and keep you updated. !!

**Comment by BadCo-NZ** [comment]
> > > Are you sure you're typing the correct command?
> > > `scrutiny-collector-metrics-freebsd-amd64` vs `scrutiny-collector-metrics-linux-amd64`
> > 
> > 
> > Ha, okay that time was a lazy copy/paste.
> > Although this time, I got a different output:
> > ```
> > [2.5.2-RELEASE][admin@pfsense]/root: /opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --api-endpoint "http://ipaddress:8080"
> > /opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64: 1: Syntax error: redirection unexpected (expecting word)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Keep in mind, I have done this on three linux machines and also a TrueNAS box already, all one after the other. So I might have misquoted my commands, but I definitely have followed the documentation :)
> 
> I got the same error. but i totally blank now on what i did for it. let me retry and keep you updated. !!

And annoyingly there is no CLI history with pfsense shell!

**Comment by martadinata666** [comment]
Here how it did it in my opnsense
```
1. curl -o /usr/local/bin/scrutiny-collector-metrics -L https://github.com/AnalogJ/scrutiny/releases/download/0.3.13/scrutiny-collector-metrics-freebsd-amd64
2. chmod +x /usr/local/bin/scrutiny-collector-metrics
3. pkg install smartmontools
4. /usr/local/bin/scrutiny-collector-metrics run --api-endpoint "http://192.168.0.2:9091"
```
The URL was my scrunity homelab installation address dockerized..

```
oot@OPNsense:/dev # /usr/local/bin/scrutiny-collector-metrics run --api-endpoint "http://192.168.0.2:9091"
2021/11/18 11:05:24 No configuration file found at /scrutiny/config/collector.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                     freebsd.amd64-0.3.12

INFO[0000] Verifying required tools                      type=metrics
INFO[0000] Executing command: smartctl --scan -j         type=metrics
INFO[0000] Sending detected devices to API, for filtering & validation  type=metrics
INFO[0000] Main: Completed                               type=metrics
```

No disk detected.
```
root@OPNsense:/dev # smartctl --scan -j
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      2
    ],
    "svn_revision": "5236",
    "platform_info": "FreeBSD 12.1-RELEASE-p20-HBSD amd64",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "--scan",
      "-j"
    ],
    "exit_status": 0
  }
}
```
Maybe because im on raid zfs or because a virtual machine. 🤔

**Comment by BadCo-NZ** [comment]
@martadinata666 all my servers (Linux and BSD) have ZFS on the host drives and it works fine on them other then pfsense.

@varunsridharan did you happen to remember how you fixed your error?

**Comment by varunsridharan** [comment]
@BadCo-NZ hi there.

Sorry about the delay. i just checked my Putty Logs to find what i did and here is the cmd that i ran 
```
sh /opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --api-endpoint "http://10.0.2.1:4 
9157"
```

in that cmd i have added `sh` in the starting that fixed the issue.

**Comment by BadCo-NZ** [comment]
> @BadCo-NZ hi there.
> 
> Sorry about the delay. i just checked my Putty Logs to find what i did and here is the cmd that i ran
> 
> ```
> sh /opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --api-endpoint "http://10.0.2.1:4 
> 9157"
> ```
> 
> in that cmd i have added `sh` in the starting that fixed the issue.

Thanks, unfortunately I still get the same error :(

**Comment by martadinata666** [comment]
> @martadinata666 all my servers (Linux and BSD) have ZFS on the host drives and it works fine on them other then pfsense.

Well, mine on VM with virtio disk, seems virtio disk doesn't have smartctl feature. 🤷🏼‍♀️

**Comment by BadCo-NZ** [comment]
> > @martadinata666 all my servers (Linux and BSD) have ZFS on the host drives and it works fine on them other then pfsense.
> 
> Well, mine on VM with virtio disk, seems virtio disk doesn't have smartctl feature. 🤷🏼‍♀️

Yeah, that won't work unless you are passing through the drives to the VM. But that would be pointless, just run it on the host. What hypervisor are you using?

**Comment by AnalogJ** [comment]
Hey @BadCo-NZ  apologies for not getting back to you earlier.
Is this still an issue for you with the v0.4.4 release?
I've updated the Manual installation instructions.

**Comment by BadCo-NZ** [comment]
Hi @AnalogJ, I see the BSD version is ready now so I'll give it a crack and report back.

**Comment by AnalogJ** [comment]
Closing this issue, feel free to reopen if you run into any issues.

**Comment by BadCo-NZ** [comment]
> Hey @BadCo-NZ apologies for not getting back to you earlier. Is this still an issue for you with the v0.4.4 release? I've updated the Manual installation instructions.

~~This is currently still an issue with the collector in v0.4.8~~

~~`[2.6.0-RELEASE][admin@pfsense]/opt/scrutiny/bin: scrutiny-collector-metrics-freebsd-amd64 --api-endpoint "https://ipaddress"
scrutiny-collector-metrics-freebsd-amd64: Command not found.
`~~

Cancel that, messed up the command. It works fine

```
[2.6.0-RELEASE][admin@pfsense]/root: /opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --api-endpoint https://scrutiny
2022/05/29 14:22:19 No configuration file found at /opt/scrutiny/config/collector.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                      freebsd.amd64-0.4.8

INFO[0000] Verifying required tools                      type=metrics
INFO[0000] Executing command: smartctl --scan -j         type=metrics
INFO[0000] Executing command: smartctl --info -j -d atacam /dev/ada0  type=metrics
INFO[0000] Using WWN Fallback                            type=metrics
INFO[0000] Executing command: smartctl --info -j -d atacam /dev/ada1  type=metrics
INFO[0000] Using WWN Fallback                            type=metrics
INFO[0000] Executing command: smartctl --info -j -d atacam /dev/ses0  type=metrics
ERRO[0000] Could not retrieve device information for ses0: exit status 2  type=metrics
INFO[0000] Sending detected devices to API, for filtering & validation  type=metrics
INFO[0000] Collecting smartctl results for ada0          type=metrics
INFO[0000] Executing command: smartctl -x -j -d atacam /dev/ada0  type=metrics
INFO[0000] Publishing smartctl results for 1946e3d6a380  type=metrics
INFO[0000] Collecting smartctl results for ada1          type=metrics
INFO[0000] Executing command: smartctl -x -j -d atacam /dev/ada1  type=metrics
INFO[0000] Publishing smartctl results for 1833e1527398  type=metrics
ERRO[0000] no device WWN detected for ses0. Skipping collection for this device (no data association possible).  type=metrics
INFO[0000] Main: Completed                               type=metrics
```

**Comment by AnalogJ** [comment]
Can you confirm that you ran chmod +x on the file first?

**Comment by AnalogJ** [comment]
Oh fantastic! Would you be willing to write a quick how-to guild for installing scrutiny on Pfsense? You can add it to the docs/ directory

**Comment by BadCo-NZ** [comment]
> Oh fantastic! Would you be willing to write a quick how-to guild for installing scrutiny on Pfsense? You can add it to the docs/ directory

Absolutely!
