### ISSUE TITLE
Question: Packaging

### ISSUE THREAD

**Issue by StaticRocket** [AnalogJ/scrutiny#204]
Hey, nice project. I've been looking to package this for some internal stuff but have a few questions:
1. What is the scrutiny-collector-selftest binary for?
2. How is the scrutiny-web-frontend tar generated?
3. Is the scrutiny-web binary you are shipping the same as the scrutiny bin produced by manually building the package?
 
Sorry if number 1 is just a standard go project thing that I'm unaware of. Thanks in advance!

**Comment by AnalogJ** [comment]
1. can be ignored for now. Intended to support #12 
2. The frontend is written in Angular. The tar file is generated as part of the Github Action triggered during a release. See https://github.com/AnalogJ/scrutiny/blob/master/.github/workflows/release-frontend.yaml
3. These 2 binaries that you could manually build (one for the web and one for the collector), but yes you can see the Makefile in the repo that is compiling the binaries that are attached to the release. 

Sorry for the delay getting back to you!
