### ISSUE TITLE
[BUG] Lowercasing device names prevents access to /dev/disk/by-id/* devices which are case sensitive

### ISSUE THREAD

**Issue by jshank** [AnalogJ/scrutiny#207]
**Describe the bug**
In `collector.yaml`, specifying a device using the [deterministic](https://wiki.archlinux.org/title/persistent_block_device_naming) `/dev/disk/by-id/` path, the path is converted to lowercase, preventing smartctl from accessing it. Overall, using /dev/sdx is bad practice since the devices can change during boot.

**Expected behavior**
Devices specified in `collector.yaml` are case sensitive and passed through as-is

**Screenshots**
N/A, it's all in the logs

**Log Files**

collector.yaml
```
<snip>
- device: /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WMC4XXXXX
        type: 'sat'
<snip>
```

Output from running `/scrutiny/bin/scrutiny-collector-metrics run`
```
time="2021-12-06T19:55:26Z" level=info msg="Executing command: smartctl -x -j -d sat /dev/disk/by-id/ata-wdc_wd30efrx-68euzn0_wd-wmc4nxxxxx" type=metrics
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-5.4.0-88-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-x",
      "-j",
      "-d",
      "sat",
      "/dev/disk/by-id/ata-wdc_wd30efrx-68euzn0_wd-wmc4nxxxxx"
    ],
    "messages": [
      {
        "string": "Smartctl open device: /dev/disk/by-id/ata-wdc_wd30efrx-68euzn0_wd-wmc4nxxxxx [SAT] failed: No such device",
        "severity": "error"
      }
    ],
    "exit_status": 2
  }
}
```

Output from running `smartctl -x -j -d sat /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WMC4XXXXX`

```
root@2ddc789fb878:/scrutiny# smartctl -x -j -d sat /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WMCXXXXX
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-5.4.0-88-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-x",
      "-j",
      "-d",
      "sat",
      "/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WMC4XXXXX"
    ],
    "exit_status": 64
  },
  "device": {
    "name": "/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WMC4XXXXX,
    "info_name": "/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WMC4XXXXX [SAT]",
    "type": "sat",
    "protocol": "ATA"
  },
  "model_family": "Western Digital Red",
  "model_name": "WDC WD30EFRX-68EUZN0",
```

**Comment by AnalogJ** [comment]
Hey @jshank 
Thanks for opening this issue.
However, this should be unnecessary. Scrutiny uses WWN disk identifiers under the hood. `--device=/dev/sdX` is only required to pass the device to Docker. 

https://github.com/AnalogJ/scrutiny/blob/influxdb/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#wwn-vs-device-name

I'll close this issue for now, but feel free to reopen if you have any follow up questions.
