### ISSUE TITLE
Apache reverse proxy

### ISSUE THREAD

**Issue by PeterMalkin** [AnalogJ/scrutiny#208]
Is it at all possible to run scrutiny webgui behind apache reverse proxy?
I have spent several days fighting this, but still cant get it to work. Maybe there's a recommended .conf I am missing?

I can access the front end directly no problem.
My website.conf looks like:
```

<VirtualHost *:80>
  Redirect permanent / https://example.com
</VirtualHost>
<VirtualHost _default_:433>
  <Location /scrutiny/>
    ProxyPass http://scrutiny:8080/ retry=0
    ProxyPassReverse http://scrutiny:8080/
    ProxyPreserveHost on
    Require all granted
  </Location>
</VirtualHost>

```
Appreciate any advice you may have

**Comment by AnalogJ** [comment]
reverse proxy + custom path support has now been added. Released in v0.4.1

See https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_REVERSE_PROXY.md for instructions. 

Thanks for your patience.
