### ISSUE TITLE
[BUG] With SuperMicro HBA (Marvell chipset) disks are seen, but no SMART attributes

### ISSUE THREAD

**Issue by zlacelle** [AnalogJ/scrutiny#214]
**Describe the bug**
I have 6 drives on a SuperMicro  AOC-SAS2LP-MV8 card, normal SATA drives. I can see them with my own smartd configuration, but with scrutiny they don't have any SMART attributes (the drives do show up with info, however). My motherboard-attached boot drive shows up fine.

**Expected behavior**
Drives populate with info.

**Log Files**

Attached.

[collector.log](https://github.com/AnalogJ/scrutiny/files/8007299/collector.log)
[web.log](https://github.com/AnalogJ/scrutiny/files/8007300/web.log)

**Comment by AnalogJ** [comment]
Hey @zlacelle please take a look at this troubleshooting doc:
https://github.com/AnalogJ/scrutiny/blob/influxdb/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md

It's only in the `influxdb` branch right now, but it'll be merged to master soon.

**Comment by AnalogJ** [comment]
I'll close this issue for now, but feel free to reopen/comment if you're still running into problems
