### ISSUE TITLE
[BUG] Duplicate dev/sdc en webGUI

### ISSUE THREAD

**Issue by raulfg3** [AnalogJ/scrutiny#218]
I see 2 entries for SDC, initially only one is show.

![image](https://user-images.githubusercontent.com/12611785/159251488-0e273ae0-5e83-433d-bc9c-13f69371d0a5.png)

root@BNAS:~# docker exec scrutiny smartctl --scan -j
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      2
    ],
    "svn_revision": "5155",
    "platform_info": "x86_64-linux-5.15.19-2-pve",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "--scan",
      "-j"
    ],
    "exit_status": 0
  },
  "devices": [
    {
      "name": "/dev/sda",
      "info_name": "/dev/sda",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdb",
      "info_name": "/dev/sdb",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdc",
      "info_name": "/dev/sdc",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdd",
      "info_name": "/dev/sdd",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sde",
      "info_name": "/dev/sde",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdf",
      "info_name": "/dev/sdf",
      "type": "scsi",
      "protocol": "SCSI"
    }
  ]
}

Do you need more info?

**Comment by FingerlessGlov3s** [comment]
I assume its a blank record or something in the database you'll need to delete it out.

Something like this may help you work it out.

Get in to the SQL Database CLI
```
docker exec -it scrutiny bash
apt update && apt install sqlite3 -y
sqlite3 /scrutiny/config/scrutiny.db
```

List all devices (disks)
```
SELECT * FROM devices
```

Once you find the disk serial number or wwn, it maybe its got blank serial number or something.
```
--Serial
DELETE FROM devices WHERE serial_number LIKE 'YOUR_SERIAL_HERE';
--WWN
DELETE FROM devices WHERE wwn LIKE 'YOUR_WWN_HERE';
```

Clear up left over data
```
DELETE FROM smart_ata_attributes WHERE smart_id IN (SELECT id FROM smarts WHERE device_wwn NOT IN (SELECT wwn FROM devices));
DELETE FROM smart_nvme_attributes WHERE smart_id IN (SELECT id FROM smarts WHERE device_wwn NOT IN (SELECT wwn FROM devices));
DELETE FROM smart_scsi_attributes WHERE smart_id IN (SELECT id FROM smarts WHERE device_wwn NOT IN (SELECT wwn FROM devices));
DELETE FROM smarts WHERE device_wwn NOT IN (SELECT wwn FROM devices);
DELETE FROM self_tests WHERE device_wwn NOT IN (SELECT wwn FROM devices);
```

exit li
```
.exit
```

**Comment by raulfg3** [comment]
sorry, scrutiny run on a docker, so not possible to apt or simmilar

![image](https://user-images.githubusercontent.com/12611785/159277655-215b242f-171d-41bd-bcd8-9b7dd6e3ee24.png)

I have no problem to restart container, my idea is to stop container, delete config and restart container.

Is this the correct approach?

**Comment by FingerlessGlov3s** [comment]
you need to install the utility, what OS is your container based on? Then do the below equivalent

`apt update && apt install sqlite3 -y`

**Comment by raulfg3** [comment]
I use : ghcr.io/linuxserver/scrutiny

from here.  https://hub.docker.com/r/linuxserver/scrutiny

not possible to use apt: 
![image](https://user-images.githubusercontent.com/12611785/159296039-121a5a4c-9e20-482a-a462-820387dc0db5.png)


Perhaps sqlite3 must be included on next images 👍 
![image](https://user-images.githubusercontent.com/12611785/159296354-3a003d99-0859-42b3-9cba-2e94d30826c4.png)

**Comment by raulfg3** [comment]
PD: User used on bash console is root, so it's not a permission problem is a limitation of docker image in use.

I can update to latest image if new image contain sqlite3 by default.

But At this point, you can close the bug, I delete the config folder of scrutiny and restart docker, and solve the duplicate /dev/sdc entry ( I lose old data, but not a problem).

**Comment by raulfg3** [comment]
Thanks a lot for faster respose.

**Comment by FingerlessGlov3s** [comment]
Ah the issue is your not using the official docker image `analogj/scrutiny`, hence why my commands don't work.

`apk update  && apk add sqlite`

**Comment by FingerlessGlov3s** [comment]
That's one way of fixing it but I would recommend running the official image but that's up to you 😊
