### ISSUE TITLE
Add BSD collector builds

### ISSUE THREAD

**Issue by BadCo-NZ** [AnalogJ/scrutiny#238]
Hi, great job with the update!

Just wondered if you will be adding BSD collector builds like they were in 0.3?

Thanks

**Comment by AnalogJ** [comment]
:D Yep, once I figure out how I broke that.

**Comment by AnalogJ** [comment]
should be fixed from v0.4.2 onwards. I triggered the release just now, so it may take up-to an hour to finish the builds.

**Comment by BadCo-NZ** [comment]
> should be fixed from v0.4.2 onwards. I triggered the release just now, so it may take up-to an hour to finish the builds.

Thanks @AnalogJ

**Comment by AnalogJ** [comment]
Going to reopen this to track the issue. For some reason the builds are no longer working, even with my fix. I'll have to do some addl analysis.

**Comment by AnalogJ** [comment]
Looks like the webapp is failing with an OOM error when compiling via GH Actions

```
>> go build github.com/influxdata/line-protocol: /usr/local/go/pkg/tool/freebsd_amd64/compile: signal: killed
chmod: /Users/runner/work/scrutiny/scrutiny/dist/scrutiny-web-freebsd-amd64: No such file or directory
/Users/runner/work/scrutiny/scrutiny/dist/scrutiny-web-freebsd-amd64: cannot open `/Users/runner/work/scrutiny/scrutiny/dist/scrutiny-web-freebsd-amd64' (No such file or directory)
```

Not quite sure how I can handle this without moving to a custom (paid) Github Actions agent.

Would it be reasonable to create just the collector binary (without the webapp?)

**Comment by BadCo-NZ** [comment]
For me, I just use the collector on pfsense and TrueNAS (VM) then run the webapp on Docker. So yeah, that would work fine for me.

**Comment by AnalogJ** [comment]
FYI, a freebsd webapp binary is now available with every release. I've migrated to a Go native SQLite library, which means CGO is no longer necessary for compilation.
