### ISSUE TITLE
[BUG]Overview page in docker hub is out of date

### ISSUE THREAD

**Issue by amatriain** [AnalogJ/scrutiny#244]
**Describe the bug**
The overview page for the official omnibus image in docker hub (https://hub.docker.com/r/analogj/scrutiny) is outdated. I've at least identified these problems:

- the path of the configuration files is mentioned as ```/scrutiny/config```, but in the github README it is now ```/opt/scrutiny/config```
- there is no mention of the volume which should be mounted in ```/opt/scrutiny/influxdb``` for influxdb, according to the github README.

**Expected behavior**
Installation instructions should be up to date and reflect recent changes after the introduction of influxdb.

**Comment by AnalogJ** [comment]
Yeah I've moved my scrutiny builds (and most other images) to Github Container Registry now. 
I'll delete my Docker Hub project.
