### ISSUE TITLE
[FEAT] Support influxdb over https

### ISSUE THREAD

**Issue by imlonghao** [AnalogJ/scrutiny#258]
**Is your feature request related to a problem? Please describe.**

My existing influxdb instance is behind a traefik proxy, which add https support for my influxdb connection.

> InfluxData strongly recommends enabling HTTPS, especially if you plan on sending requests to InfluxDB over a network.

https://docs.influxdata.com/influxdb/v2.2/security/enable-tls/

scrutiny is hardcoded to connect to `http` influx endpoint, see https://github.com/AnalogJ/scrutiny/blob/6f283fd/webapp/backend/pkg/database/scrutiny_repository.go#L82

**Describe the solution you'd like**

Add a new option like `web.influxdb.tls` or `web.influxdb.https` in config file

**Additional context**

None.

**Comment by AnalogJ** [comment]
apologies, this should definitely have been supported from day 1. 
I've added a config key for `web.influxdb.scheme`. It's currently defaulted to `http` but you can override to `https`. 

The change has been merged to master, and the docker image will be available in ~1h.

**Comment by AnalogJ** [comment]
included in v0.4.7 🎉
