### ISSUE TITLE
[FEAT] time to show temp history data in webGUI

### ISSUE THREAD

**Issue by raulfg3** [AnalogJ/scrutiny#259]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by raulfg3** [comment]
please finish the WIP of date in webGUI, actually only a week is show and a year or month is a really usefull addition
![Anotación 2022-05-23 105055](https://user-images.githubusercontent.com/12611785/169791881-324b2ee8-58d4-4983-9c90-6b07a299d069.jpg)
.

**Comment by AnalogJ** [comment]
@raulfg3  if you use the beta-omnibus branch, you'll see that the week/month/yearly data is correctly displayed

**Comment by AnalogJ** [comment]
I'll be merging that branch into master soon.

**Comment by AnalogJ** [comment]
fixed in `v0.4.7` 🎉

**Comment by raulfg3** [comment]
> I'll be merging that branch into master soon.

Thanks, I'll wait until be in the master branch.

Good Work.

**Comment by raulfg3** [comment]
> @raulfg3 if you use the beta-omnibus branch, you'll see that the week/month/yearly data is correctly displayed

I use master#28ac3ac version, and scroll show "forever, year, month, and week" as options, but in my install, always show 7 days, no matter what select in webGUI.
![1](https://user-images.githubusercontent.com/12611785/172637578-df51d7e5-321b-4d6b-91da-107176db8632.jpg)
![2 ](https://user-images.githubusercontent.com/12611785/172637585-2e7a8b0b-e5e6-4794-815f-4580cf98b912.jpg)
![3](https://user-images.githubusercontent.com/12611785/172637730-610b4595-5e27-4f77-b688-a0ac6448c634.jpg)

**Comment by raulfg3** [comment]
of course , scrutiny runs for more days that are show in webGUI

**Comment by raulfg3** [comment]
please reopen it, is still have webGUI problems to see correct time.

**Comment by raulfg3** [comment]
What aditional info do you need?.
