### ISSUE TITLE
[FEAT] Example notification script

### ISSUE THREAD

**Issue by alexbunt** [AnalogJ/scrutiny#261]
**Is your feature request related to a problem? Please describe.**
There is no example custom notification script. The README.md states "data provided via environmental variables" - What data? What variables?

**Describe the solution you'd like**
A clear example bash script that highlights what environmental variables are available.

**Comment by AnalogJ** [comment]
Good catch, sorry about that.
I've fixed this in the following commit: 
https://github.com/AnalogJ/scrutiny/commit/d62928aaaee42e19317aba13ee78908130254447

**Comment by alexbunt** [comment]
Ah fantastic! Thank you :)
