### ISSUE TITLE
[BUG] No data for USB external drive

### ISSUE THREAD

**Issue by mhbates** [AnalogJ/scrutiny#266]
**Describe the bug**
Seagate external drive is listed but shows no data. It's a Seagate 14TB Expansion drive.

**Screenshots**
![image](https://user-images.githubusercontent.com/18390027/170830554-d8adce26-7d83-4422-9887-72766e54cef3.png)

**Log Files**
`time="2022-05-28T14:44:40Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sdg" type=metrics
time="2022-05-28T14:44:40Z" level=error msg="Could not retrieve device information for sdg: exit status 2" type=metrics
time="2022-05-28T14:45:43Z" level=error msg="no device WWN detected for sdg. Skipping collection for this device (no data association possible).\n" type=metrics
`

**Comment by AnalogJ** [comment]
@mhbates  can you take a look at this issue: https://github.com/AnalogJ/scrutiny/issues/255

When you run smartctl manually (with the addl flags) does everything work?

```
smartctl /dev/sdg -a -v 1,raw48:54 -v 7,raw48:54
```

**Comment by mhbates** [comment]
@AnalogJ Thanks for the quick response. No, it throws this:

`Read Device Identity failed: scsi error unsupported field in scsi command`
`A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.`

**Comment by AnalogJ** [comment]
Oh, i just noticed that you said it was an external `Seagate 14TB Expansion` drive. 
Have you shucked it, and connected it via a SATA connector? or is it connected via USB?

**Comment by mhbates** [comment]
It's connected via USB. Do these just not support SMART?

**Comment by AnalogJ** [comment]
someone on Reddit with a similar issue mentioned that adding `-T permissive` worked for them. Can you try that?

`smartctl` (which Scrutiny uses under the hood) supports USB drives, but IIRC it doesn't detect them automatically.

**Comment by mhbates** [comment]
Still no luck, see screenshot below. I also found this Reddit thread, which has me thinking that when connected via USB, SMART just won't work: https://www.reddit.com/r/DataHoarder/comments/nc392f/how_can_i_read_the_smart_data_of_a_16_tb_seagate/

![image](https://user-images.githubusercontent.com/18390027/170832831-f03d39d3-cd96-4b96-94d6-b9a2b002d712.png)

**Comment by AnalogJ** [comment]
You may need to play around with different `--device, -d` flag options to figure out which one works for your USB device:

https://webcache.googleusercontent.com/search?q=cache:HSSoogXbzrMJ:https://www.smartmontools.org/wiki/Supported_USB-Devices+&cd=1&hl=en&ct=clnk&gl=us&client=firefox-b-1-d

Try `-d sat -T permissive` and see if that works

**Comment by AnalogJ** [comment]
worst case you can try this:

https://github.com/AnalogJ/scrutiny/blob/beta/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#volume-mount-all-devices-dev---privileged

Its the least secure option, but you can use it to run `smartctl` without any of the restrictions that docker imposes.

**Comment by ViRb3** [comment]
External HDDs support two modes of operation `usb-storage` (old, slower, stable) and `uas` (new, faster, sometimes unstable). On some external HDDs, `uas` mode does not properly pass through SMART information, or even causes hardware issues, so it has been disabled by the kernel. No amount of `smartctl` parameters will fix this, as it is being rejected by the kernel. This is especially true with Seagate HDDs. One solution is to force these devices into `usb-storage` mode, which will incur some performance penalty, but may work well enough for you. More info:
- https://www.smartmontools.org/wiki/Supported_USB-Devices
- https://www.smartmontools.org/wiki/SAT-with-UAS-Linux
- https://forums.raspberrypi.com/viewtopic.php?t=245931
