### ISSUE TITLE
[FEAT] Dark mode Support

### ISSUE THREAD

**Issue by extremelyonline** [AnalogJ/scrutiny#268]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add a dark mode?

**Describe the solution you'd like**
True black dark mode

**Additional context**
Thanks!

**Comment by AnalogJ** [comment]
Just leaving myself a note on this one:

> treo-theme-dark

**Comment by shamoon** [comment]
Ok I give up, I cant find this "treo-theme-dark", what is it? =)
(asking because I could potentially help out with a PR for this, Im pretty comfortable with Angular. Assuming you havent done this already.)

**Comment by AnalogJ** [comment]
haha wasn't trying to send you on a wild goose chase, just wanted to give myself a reminder that this is half-finished. 

the body tag currently looks like:

```
<body class="treo-theme-light treo-splash-screen-hidden">
```

You can enable the dark theme by changing it to:

```
<body class="treo-theme-dark treo-splash-screen-hidden">
```

The dashboard page looks mostly correct, but the settings popups and the details page are unfinished and look like crap :D

**Comment by shamoon** [comment]
Aha! So looks like it needs some CSS cleanup and a toggle button somewhere—doable! Were you envisioning something in the settings popup e.g. saved to the db or a more simple approach is to have a toggle and save the setting to browser `localStorage` (obv downside of that is setting is lost between sessions etc)

**Comment by AnalogJ** [comment]
yeah, I was going to have a toggle save the setting to localstorage, like I already do for `display title` and `sort by`
