### ISSUE TITLE
Home Assistant Integration Support

### ISSUE THREAD

**Issue by jtenniswood** [AnalogJ/scrutiny#273]
I would love to integrate this into home assistant, I have no idea if that’s possible, but wanted to put it out there as a suggestion.

**Comment by AnalogJ** [comment]
I think someone already created a plug-in for it - https://community.home-assistant.io/t/home-assistant-addon-scrutiny-smart-dashboard/295747/34

Only problem is that they use the LSIO docker image, which is locked to the v0.3.x release.

**Comment by AnalogJ** [comment]
closing this issue for now, please reopen/comment if you have any questions.
