### ISSUE TITLE
Discussing correlation vs. causation with BlackBlaze data

### ISSUE THREAD

**Issue by ViRb3** [AnalogJ/scrutiny#275]
I just installed scrutiny and set it up for my 6 external HDDs. Some of them are more than 5 years old, some of them are brand new. I noticed that two of the old disks were marked as failed:

Disk 1:
![Screen Shot 2022-06-02 at 18 04 27](https://user-images.githubusercontent.com/2650170/171684960-a4242e12-04a5-4807-a763-28bdadb1ba1e.png)

Disk 2:
![Screen Shot 2022-06-02 at 18 04 59](https://user-images.githubusercontent.com/2650170/171685027-33e41206-0604-4889-a29d-058ce94d876b.png)

This looks pretty scary, given the high failure rate and its description:

![Screen Shot 2022-06-02 at 18 05 37](https://user-images.githubusercontent.com/2650170/171685146-cd34db15-28f6-4218-99af-57f2a48c6e8d.png)

However, it made me think. Does the failure rate mean that 20% of confirmed failed disks in BlackBlaze's dataset had this attribute at or worse than my value? And does this take into account how many of the healthy disks had this attribute with the same value? Because if we only look at the failed data, we're assuming that correlation is causation, which may be wrong. Ideally, I believe we'd want to report the difference between the healthy and failed disks instead. This may be what you're currently doing, but I have no clue, so please excuse any assumptions I made here.

Thanks a lot!

EDIT: Could you please share the source of the BlackBlaze data?

**Comment by shamoon** [comment]
I totally agree with you ( https://github.com/AnalogJ/scrutiny/issues/187#issuecomment-1125658351 ), see my quote from the BB data (and theres a link there). This is correlation not causation and I think to display it as "Failed" is kind of misleading. At best its a "warning" or a "red flag" that something _might_ happen, not that it has. Thats why BB dont use most of these data points for their decisions about replacing drives, etc.

**Comment by AnalogJ** [comment]
Yeah, as @shamoon mentioned, there's been a lot of concern about how Backblaze data is used within Scrutiny. 

I'm working on some changes to the failure detection such that it'll be configurable in the UI, and you can selectively enable/disable the backblaze based failures and the thresholds.

**Comment by jeroengui** [comment]
Yeah, same issue here. Brand new server grade drive. And the application shows me that the drive is in status "failed"

![image](https://user-images.githubusercontent.com/52084809/172163924-b6df3259-c334-445a-b6d7-1b2355325462.jpeg)

**Comment by AnalogJ** [comment]
Just wanted to give everyone an update on the status of this issue. 

There's currently two tasks I'm working on:

- [x] Update the details page UI to display the smart status separately from the scrutiny status. 
- [x] Create a setting which allows uses to enable/disable Scrutiny analysis. (released in `v0.5.0`)

The first task is partially complete. Here's what it currently looks like:

![Screen Recording 2022-06-09 at 10 50 32 PM](https://user-images.githubusercontent.com/891875/172999594-cba18c9b-d8d4-42c9-abd5-699a94104524.gif)

The Smart status and Scrutiny status are differentiated in the expanding details panel. 

**This is still a prototype. I think it works well, but I'd love to hear your thoughts.**

**Comment by Parlane** [comment]
> Yeah, same issue here. Brand new server grade drive. And the application shows me that the drive is in status "failed"
> 
> ![image](https://user-images.githubusercontent.com/52084809/172163924-b6df3259-c334-445a-b6d7-1b2355325462.jpeg)

Is that a seagate drive ? Probably related to #255 then, and fixed in master to not show failed anymore.

**Comment by AnalogJ** [comment]
Took an incredibly long time, but as of `v0.5.0` this functionality is now available in Scrutiny! 🥳 

<img width="996" alt="Screen Shot 2022-08-04 at 8 33 58 AM" src="https://user-images.githubusercontent.com/891875/182887802-f9b8f04e-88dd-4568-a8f2-a83fdb212042.png">

On the dashboard settings panel, you can now change the "Device Status - Thresholds" between `Smart`, `Scrutiny` and `Both`. By default this is set to `Both`. 

When changed to `Smart` - only the output of `smartctl` is relevant, all other Scrutiny/Backblaze detected failures/warnings are ignored (in notifications & UI). 

The description and UI for this functionality may be enhanced in the coming releases, but it is functional and working. 
I'd appreciate it if you could pull down the latest image, test it out and provide any feedback you may have!

Appreciate everyone's patience - this has been a long time coming.
