### ISSUE TITLE
[BUG] PMpanic: failed to check influxdb setup status - parse "://:": missing protocol scheme with Default configs

### ISSUE THREAD

**Issue by flargargoyl** [AnalogJ/scrutiny#290]
**Describe the bug**
Using Omni image, startup cycles on PMpanic: failed to check influxdb setup status - parse "://:": missing protocol scheme with default config files.

I have tried master-omnibus, beta-omnibus, several direct versions back (i think 4.6 was the las one i tired) and i`m _still_ getting the same error.

**Expected behavior**
Config files by default should include method and location of the database to connect to. I am unaware which exact config files should have this scheme in what exact way defined, and example config files in git did not help me to figure that part out.

My compose file:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:beta-omnibus
    container_name: scrutiny
    hostname: scrutiny.${DEPLOYMENT_LOCATION}
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO #necessary to allow smartctl permission to query your device SMART data.
    environment:
      <<: *default-environment
      SCRUTINY_API_ENDPOINT: http://localhost:8080
      SCRUTINY_WEB: true
      SCRUTINY_COLLECTOR: true
      UMASK: 002
    volumes:
      - ${DOCKERDIR}/scrutiny:/opt/scrutiny/config
      - /run/udev:/run/udev:ro
      - ${DOCKERDIR}/influxdb:/opt/scrutiny/influxdb
    networks:
      - t2_proxy
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
    labels:
      - "traefik.enable=true"
      - "traefik.enable=true"
   ## HTTP Routers
      - "traefik.http.routers.scrutiny-rtr.entrypoints=https,http"
      - "traefik.http.routers.scrutiny-rtr.rule=Host(`scrutiny.$DOMAINNAME`)"
      - "traefik.http.routers.scrutiny-rtr.tls=true"
      - "traefik.http.routers.scrutiny-rtr.tls.options=myTLSOptions@file"
   ## Middlewares
      - "traefik.http.routers.scrutiny-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
   ## HTTP Services
      - "traefik.http.routers.scrutiny-rtr.service=scrutiny-svc"
      - "traefik.http.services.scrutiny-svc.loadbalancer.server.port=8080"
      
Note: mounted volumes mount fine, and are available inside the container, with correct access rights; 
volume influxdb has some files in it after the container start
volume config is empty, and logs suggest it`ll use "default" config.
Suggestion: simplify location of configuration files into one reasonable space; name configuration files in a way they represent what`s exactly they are configuring; show the location of "default" config so we can copy it and use as a template to build a custom config file instead of reffering to git for the example

**Log Files**
today at 12:49:30 PM[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
today at 12:49:30 PM[s6-init] ensuring user provided files have correct perms...exited 0.
today at 12:49:30 PM[fix-attrs.d] applying ownership & permissions fixes...
today at 12:49:30 PM[fix-attrs.d] done.
today at 12:49:30 PM[cont-init.d] executing container initialization scripts...
today at 12:49:30 PM[cont-init.d] 01-timezone: executing... 
today at 12:49:30 PM[cont-init.d] 01-timezone: exited 0.
today at 12:49:30 PM[cont-init.d] 50-cron-config: executing... 
today at 12:49:30 PM[cont-init.d] 50-cron-config: exited 0.
today at 12:49:30 PM[cont-init.d] done.
today at 12:49:30 PM[services.d] starting services
today at 12:49:30 PMstarting cron
today at 12:49:30 PMwaiting for influxdb
today at 12:49:30 PMwaiting for scrutiny service to start
today at 12:49:30 PMinfluxdb config file already exists. skipping.
today at 12:49:30 PMstarting influxdb
today at 12:49:30 PM[services.d] done.
today at 12:49:30 PMinfluxdb not ready
today at 12:49:30 PMscrutiny api not ready
today at 12:49:30 PMts=2022-06-08T09:49:30.812246Z lvl=info msg="Welcome to InfluxDB" log_id=0axgL~F0000 version=v2.2.0 commit=a2f8538837 build_date=2022-04-06T17:36:40Z
today at 12:49:30 PMts=2022-06-08T09:49:30.917621Z lvl=info msg="Resources opened" log_id=0axgL~F0000 service=bolt path=/opt/scrutiny/influxdb/influxd.bolt
today at 12:49:30 PMts=2022-06-08T09:49:30.917778Z lvl=info msg="Resources opened" log_id=0axgL~F0000 service=sqlite path=/opt/scrutiny/influxdb/influxd.sqlite
today at 12:49:31 PMts=2022-06-08T09:49:31.201413Z lvl=info msg="Checking InfluxDB metadata for prior version." log_id=0axgL~F0000 bolt_path=/opt/scrutiny/influxdb/influxd.bolt
today at 12:49:31 PMts=2022-06-08T09:49:31.201610Z lvl=info msg="Using data dir" log_id=0axgL~F0000 service=storage-engine service=store path=/opt/scrutiny/influxdb/engine/data
today at 12:49:31 PMts=2022-06-08T09:49:31.201652Z lvl=info msg="Compaction settings" log_id=0axgL~F0000 service=storage-engine service=store max_concurrent_compactions=2 throughput_bytes_per_second=50331648 throughput_bytes_per_second_burst=50331648
today at 12:49:31 PMts=2022-06-08T09:49:31.201666Z lvl=info msg="Open store (start)" log_id=0axgL~F0000 service=storage-engine service=store op_name=tsdb_open op_event=start
today at 12:49:31 PMts=2022-06-08T09:49:31.201751Z lvl=info msg="Open store (end)" log_id=0axgL~F0000 service=storage-engine service=store op_name=tsdb_open op_event=end op_elapsed=0.086ms
today at 12:49:31 PMts=2022-06-08T09:49:31.201790Z lvl=info msg="Starting retention policy enforcement service" log_id=0axgL~F0000 service=retention check_interval=30m
today at 12:49:31 PMts=2022-06-08T09:49:31.201806Z lvl=info msg="Starting precreation service" log_id=0axgL~F0000 service=shard-precreation check_interval=10m advance_period=30m
today at 12:49:31 PMts=2022-06-08T09:49:31.202683Z lvl=info msg="Starting query controller" log_id=0axgL~F0000 service=storage-reads concurrency_quota=1024 initial_memory_bytes_quota_per_query=9223372036854775807 memory_bytes_quota_per_query=9223372036854775807 max_memory_bytes=0 queue_size=1024
today at 12:49:31 PMts=2022-06-08T09:49:31.411209Z lvl=info msg="Configuring InfluxQL statement executor (zeros indicate unlimited)." log_id=0axgL~F0000 max_select_point=0 max_select_series=0 max_select_buckets=0
today at 12:49:31 PMts=2022-06-08T09:49:31.499060Z lvl=info msg=Listening log_id=0axgL~F0000 service=tcp-listener transport=http addr=:8086 port=8086
today at 12:49:35 PMstarting scrutiny
today at 12:49:35 PMscrutiny api not ready
today at 12:49:35 PM2022/06/08 12:49:35 No configuration file found at /opt/scrutiny/config/scrutiny.yaml. Using Defaults.
today at 12:49:35 PM
today at 12:49:35 PM ___   ___  ____  __  __  ____  ____  _  _  _  _
today at 12:49:35 PM/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
today at 12:49:35 PM\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
today at 12:49:35 PM(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
today at 12:49:35 PMgithub.com/AnalogJ/scrutiny                             dev-0.4.9
today at 12:49:35 PM
today at 12:49:35 PMStart the scrutiny server
today at 12:49:35 PMtime="2022-06-08T12:49:35+03:00" level=info msg="Trying to connect to scrutiny sqlite db: \n"
today at 12:49:35 PMtime="2022-06-08T12:49:35+03:00" level=info msg="Successfully connected to scrutiny sqlite db: \n"
today at 12:49:35 PMpanic: failed to check influxdb setup status - parse "://:": missing protocol scheme
today at 12:49:35 PM
today at 12:49:35 PMgoroutine 1 [running]:
today at 12:49:35 PMgithub.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0x10ce1e0, 0xc0000100a0}, {0x10d78b0, 0xc000452460})
today at 12:49:35 PM	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xa5
today at 12:49:35 PMgithub.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc000065260, {0x10d78b0, 0xc000452460})
today at 12:49:35 PM	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:27 +0xb4
today at 12:49:35 PMgithub.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc000065260)
today at 12:49:35 PM	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:105 +0x46b
today at 12:49:35 PMmain.main.func2(0xc000079380)
today at 12:49:35 PM	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x1f7
today at 12:49:35 PMgithub.com/urfave/cli/v2.(*Command).Run(0xc000458240, 0xc000079200)
today at 12:49:35 PM	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/command.go:164 +0x64a
today at 12:49:35 PMgithub.com/urfave/cli/v2.(*App).RunContext(0xc00045e000, {0x10b84b0, 0xc0000be000}, {0xc0000ba000, 0x2, 0x2})
today at 12:49:35 PM	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:306 +0x926
today at 12:49:35 PMgithub.com/urfave/cli/v2.(*App).Run(...)
today at 12:49:35 PM	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:215
today at 12:49:35 PMmain.main()
today at 12:49:35 PM	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x679
today at 12:49:35 PMwaiting for influxdb
today at 12:49:35 PMstarting scrutiny
today at 12:49:35 PM2022/06/08 12:49:35 No configuration file found at /opt/scrutiny/config/scrutiny.yaml. Using Defaults.

**Comment by AnalogJ** [comment]
looks like you're migrating from the LSIO docker image. 
You'll need to follow these steps https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md#upgrading-from-v03x-to-v04x

basically remove the `SCRUTINY_WEB=true`, `SCRUTINY_COLLECTOR=true` env variables and fix your volume mount paths. 

Closing this issue for now, but feel free to reopen if you still have problems after following the steps described in the guide.

**Comment by flargargoyl** [comment]
volume mounts was fine, however you were correct with the rest - i did try LSIO image, it didn`t work, tried your original one with that error and did not found that support article. It seems to have started now, thank you much!
