### ISSUE TITLE
[BUG] Windows Database connection failure

### ISSUE THREAD

**Issue by gabriel-vanca** [AnalogJ/scrutiny#292]
Scrutiny is no longer working on Windows since the latest updates. I'm getting the following when trying to run the web executable:

`Start the scrutiny server`

`2022/06/09 02:56:44 Loading configuration file: C:\scrutiny\config\scrutiny.yaml`

`time="2022-06-09T02:56:44+01:00" level=info msg="Trying to connect to scrutiny sqlite db: C:\\scrutiny\\config\\scrutiny.db\n"`

`time="2022-06-09T02:56:44+01:00" level=info msg="Successfully connected to scrutiny sqlite db: C:\\scrutiny\\config\\scrutiny.db\n"`

`panic: failed to check influxdb setup status - Get "http://localhost:8086/api/v2/setup": dial tcp [::1]:8086: connectex: No connection could be made because the target machine actively refused it.`

I deleted the database to see if that fixes it, but no success.

**Comment by AnalogJ** [comment]
can you confirm the status of the InfluxDB service on your machine? 
Can you visit the following url in your browser and paste the output below: `http://localhost:8086/health`

If you upgraded from `0.3.x` to a `0.4.x` version, then you may be missing the new InfluxDB dependency. You'll want to take a look at the updated [manual installation instructions](https://github.com/AnalogJ/scrutiny/blob/master/docs/INSTALL_MANUAL.md)

Thanks!

**Comment by AnalogJ** [comment]
Closing this issue for now. Feel free to comment/reopen if this is still an issue for you.

**Comment by gabriel-vanca** [comment]
Finally had time today to deal with this. A couple of points:

1. I wish the migration to InfluxDB would have been made clear in the docs. Also, does that mean the sqlite is now no longer necessary? Should I delete that from the config file?

2. The reason I was getting the error was actually that the InfluxDB lines in the config file were not indented properly.

3. Why does Scrutiny need a full access token? Why does a normal read/write token not work? I've tried to do that but it says "Organisation not found"

4. Why has Gotify HTTP support been deprecated? Now I'm getting 100 lines of errors because my Gotify doesn't support HTTPS.

5. The web app still doesn't work. it connect to the InfluxDB, it says "Database migration completed successfully" after which it doesn't do anything for about 2 minutes after which it throws a lot of errors:

`time="2022-06-26T19:49:05+01:00" level=info msg="::1 - NAS [26/Jun/2022:19:49:05 +0100] \"POST /api/devices/register\" 200 7374 \"\" \"Go-http-client/1.1\" (21ms)" clientIP="::1" hostname=NAS latency=21 method=POST path=/api/devices/register referer= respLength=7374 statusCode=200 userAgent=Go-http-client/1.1`

`time="2022-06-26T19:49:05+01:00" level=info msg="No notification endpoints configured. Skipping failure notification."`

`time="2022-06-26T19:49:05+01:00" level=info msg="::1 -NAS [26/Jun/2022:19:49:05 +0100] \"POST /api/device/6000c290194102b60ec9f8580455a47f/smart\" 200 16 \"\" \"Go-http-client/1.1\" (55ms)" clientIP="::1" hostname=NAS latency=55 method=POST path=/api/device/6000c290194102b60ec9f8580455a47f/smart referer= respLength=16 statusCode=200 userAgent=Go-http-client/1.1`

`time="2022-06-26T19:49:05+01:00" level=info msg="No notification endpoints configured. Skipping failure notification."`

**Comment by gabriel-vanca** [comment]
Never mind my final point. I changed the port for Scrutiny to avoid a conflict with my Homer dashboard, but I only updated the new firewall rule in the ESXi firewall, but not in the Windows Firewall. The web app now works.
