### ISSUE TITLE
[FEAT] Docker env variable for dark mode

### ISSUE THREAD

**Issue by extremelyonline** [AnalogJ/scrutiny#294]
Docker env variable for constant dark mode

**Comment by AnalogJ** [comment]
Unfortunately this is not possible (yet) as all the settings are stored in the frontend (via browser LocalStorage).

Eventually we'll create a `Settings` table in the database. But until then this is not possible.

I'll keep this open but label it as `wontfix` for now.

**Comment by AnalogJ** [comment]
the dark mode setting has now been moved to the database (so it persists between sessions & browsers) but there's no mechanism to force Darkmode on startup. 

Having said that, I think it's fair to change the setting once via the WebUI. 
I'm going to close this as `wontfix`, but feel free to comment if you have any feedback.
