### ISSUE TITLE
Why does the container delete when it exits?

### ISSUE THREAD

**Issue by dudefoxlive** [AnalogJ/scrutiny#298]
I am attempting to setup scrutiny but I notice that the docker run commands contain -rm in them which delete them once the container exits. Is there a specific reason for this? I want the containers to stay as I don't want to have to recreate them each time.

**Comment by AnalogJ** [comment]
you are correct, `--rm` is not required for scrutiny to function. The intention is just to clean up the host if the user decides to manually kill the container (after testing). 

I'll close this issue for now, feel free to reopen if you have any further questions.
