### ISSUE TITLE
[FEAT] Name of computer in Web Frontend

### ISSUE THREAD

**Issue by dudefoxlive** [AnalogJ/scrutiny#299]
I have a small number of systems that I would like to have upload info to the Web Frontend. One thing I noticed is that its difficult to determine where that drive is or in which system. I would suggest either separating the drives by the name of the System or adding the name of the system to the beginning of the drive in the Web Frontend.

**Comment by AnalogJ** [comment]
this is already possible, please see the `host.id` key in the collector config file:

https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml#L19-L22

Closing this issue for now. If you have any follow up questions, please feel free to reopen.
