### ISSUE TITLE
Attempting to load dashboard from web container presents 404s

### ISSUE THREAD

**Issue by RealOrangeOne** [AnalogJ/scrutiny#3]
```
$ curl http://xxxxxx/
<a href="/web">Found</a>.

$ curl http://xxxxxxx/web
<a href="/web/">Moved Permanently</a>.

$ curl http://xxxxxx/web/
404 page not found
```

Logs simply show:

```
web_1        | [GIN] 2020/09/17 - 12:54:19 | 404 |     176.723?s |      xxx.xxx.xxx.xxx | GET      "/web/"
```

There are successful responses from `/api` routes, so the API is definitely up, the collector appears to run successfully.

Happy to help debug, but so far i'm stumped (realise this isn't the most helpful issue in the world in terms of detail).

**Comment by alex-phillips** [comment]
Same issue for me.

**Comment by AnalogJ** [comment]
This is definitely related to my Dockerfile change. I moved them into the
docker directory from the root of the repo.

I’ll have to fix it this evening, sorry about that.

**Comment by AnalogJ** [comment]
Actually I might have lied, I just did `docker run -p 8080:8080 analogj/scrutiny:web` and `curl -L localhost:8080` works correctly. 

Basically localhost:8080 redirects to `localhost:8080/web` which redirects to `localhost:8080/web/`

That double redirection definitely needs to be fixed, but the UI does show up in my browser. 

Can you confirm @alex-phillips @RealOrangeOne ?

**Comment by marcinozga** [comment]
I deployed Scrutiny today, and I’m facing the same issue. I’m using single container while testing. Scrutiny is behind traefik reverse proxy, and accessible over domain name. Initially it was redirecting url to `/web/dashboard` and it loaded just fine, but I would get 404 when refreshing the page. I would have to visit scrutiny.mydomain.name to get it to load. I also tried accessing it from iPad, and I get redirected to `/web` with 404 error.

**Comment by AnalogJ** [comment]
interesting, I did have scrutiny running behind traefik at one point, but for most of my development & testing I've just been accessing it via a port mapping. 

Let me do some testing with Traefik and see if I can reproduce this.

**Comment by marcinozga** [comment]
Looks like my issue was caused by config file. I used default values, just commented out notifications section. Upon further investigation, database file was not being created. I removed config volume mapping, database got created, but since it’s inside container, it won’t persist. This probably needs better documentation, how to map both config file and database locations, perhaps complete docker compose file.

**Comment by marcinozga** [comment]
I did more testing, and played with volume mappings, I can use custom config file and persistent database, but I still get 404 on reload. I'm deploying Scrutiny with ansible, behind traefik and [https://github.com/thomseddon/traefik-forward-auth](https://github.com/thomseddon/traefik-forward-auth), syntax is very similar to docker compose:

```$ cat roles/scrutiny/tasks/main.yml
---
# tasks file for scrutiny
  - name: Set DNS Record on CloudFlare
    include_role:
      name: cloudflare
    vars:
      subdomain: smart

  - name: Remove existing scrutiny container
    docker_container:
      name: scrutiny
      state: absent

  - name: Create Scrutiny directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 0775
      owner: "{{ user }}"
      group: "{{ user }}"
    with_items:
      - /opt/data/scrutiny/config

  - name: Create Scrutiny config
    file:
      path: "{{ item }}"
      state: touch
      mode: 0664
      owner: "{{ user }}"
      group: "{{ user }}"
    with_items:
      - /opt/data/scrutiny/config/scrutiny.yaml

  - name: Create container
    docker_container:
      name: scrutiny
      image: analogj/scrutiny:latest
      pull: yes
      privileged: yes
      env:
        PUID: "{{ puid }}"
        PGID: "{{ pgid }}"
        TZ: "{{ tz }}"
      labels:
        "traefik.enable": "true"
        "traefik.backend": "scrutiny"
        "traefik.port": "8080"
        "traefik.docker.network": "proxy"
        "traefik.frontend.auth.forward.address": "http://auth:4181"
        "traefik.frontend.auth.forward.authResponseHeaders": "X-Forwarded-User"
        "traefik.frontend.auth.forward.trustForwardHeader": "true"
        "traefik.frontend.rule": "Host:smart.mydomain.name"
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/dev/disk:/dev/disk"
        - "/run/udev:/run/udev:ro"
        - "/opt/data/scrutiny/config:/scrutiny/config"
        - "/opt/data/scrutiny/config/scrutiny.yaml:/scrutiny/config/scrutiny.yaml"
      networks:
        - name: proxy
        - name: internal
          aliases:
            - scrutiny
      purge_networks: yes
      restart_policy: always
      stop_timeout: 300
      state: started
```

And here's my config.yaml

```$ cat scrutiny.yaml
# Commented Scrutiny Configuration File
#
# The default location for this file is ~/scrutiny.yaml.
# In some cases to improve clarity default values are specified,
# uncommented. Other example values are commented out.
#
# When this file is parsed by Scrutiny, all configuration file keys are
# lowercased automatically. As such, Configuration keys are case-insensitive,
# and should be lowercase in this file to be consistent with usage.


######################################################################
# Version
#
# version specifies the version of this configuration file schema, not
# the scrutiny binary. There is only 1 version available at the moment
version: 1

web:
  listen:
    port: 8080
    host: 0.0.0.0
  database:
    # can also set absolute path here
    location: /scrutiny/config/scrutiny.db
  src:
    frontend:
      path: ./dist

disks:
  include:
     - /dev/sda
     - /dev/sdb
     - /dev/sdc
     - /dev/sdd
     - /dev/sde
     - /dev/sdf
     - /dev/sdg
     - /dev/sdh
     - /dev/sdi
     - /dev/sdj
  exclude:
    # - /dev/sdb

notify:
  urls:
#    - "discord://token@channel"
#    - "telegram://token@telegram?channels=channel-1[,channel-2,...]"
#    - "pushover://shoutrrr:apiToken@userKey/?devices=device1[,device2, ...]"
#    - "slack://[botname@]token-a/token-b/token-c"
#    - "smtp://username:password@host:port/?fromAddress=fromAddress&toAddresses=recipient1[,recipient2,...]"
#    - "teams://token-a/token-b/token-c"
#    - "gotify://gotify-host/token"
#    - "pushbullet://api-token[/device/#channel/email]"
#    - "ifttt://key/?events=event1[,event2,...]&value1=value1&value2=value2&value3=value3"
#    - "mattermost://[username@]mattermost-host/token[/channel]"
#    - "hangouts://chat.googleapis.com/v1/spaces/FOO/messages?key=bar&token=baz"
#    - "zulip://bot-mail:bot-key@zulip-domain/?stream=name-or-id&topic=name"
#    - "join://shoutrrr:api-key@join/?devices=device1[,device2, ...][&icon=icon][&title=title]"
#    - "script:///file/path/on/disk"
#    - "https://www.example.com/path"

limits:
  ata:
    critical:
      error: 10
    standard:
      error: 20
      warn: 10
  scsi:
    critical: true
    standard: true
  nvme:
    critical: true
    standard: true


collect:
  metric:
    enable: true
    command: '-a -o on -S on'
  long:
    enable: false
    command: ''
  short:
    enable: false
    command: ''
```

**Comment by TChilderhose** [comment]
Think you just need to change
```
  src:
    frontend:
      path: ./dist

```
to
```
  src:
    frontend:
      path: /scrutiny/web

```

Looks like the example config has a different path than the default
https://github.com/AnalogJ/scrutiny/blob/119e24f6ec512e4c0ea569b594f20d60fa3baa9c/webapp/backend/pkg/config/config.go#L32

**Comment by marcinozga** [comment]
Yeah, I figured out that part, I commented out that section completely, and it appeared to solve the 404 errors.

**Comment by AnalogJ** [comment]
oof. I didn't expect people to copy paste the example config file as-is. That would definitely explain the issues in this thread, sorry about that. 
Let me fix the config file.
