### ISSUE TITLE
[BUG] Troubleshooting doc is missing a semicolon in the sqlite3 command

### ISSUE THREAD

**Issue by ridizy** [AnalogJ/scrutiny#302]
**Describe the bug**
The section for [Device failed but Smart & Scrutiny passed](https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#device-failed-but-smart--scrutiny-passed) in the Troubleshooting Doc is missing a semicolon for the sqlite3 cli command.  As written, the command will not execute and disk status will not be reset.

**Expected behavior**
The command completes without error and the disk status is reset

**Resolution**
Line 208 should read:
```UPDATE devices SET device_status = null;```

**Comment by AnalogJ** [comment]
good catch, fixed. Thanks @ridizy !
