### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [AnalogJ/scrutiny#306]
I used the Command which is shown on Github  to deploy the container (I only modified the Port and config location). But I get the following error message. 

 ___   ___  ____  __  __  ____  ____  _  _  _  _

/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )

\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /

(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)

github.com/AnalogJ/scrutiny                            dev-0.4.13

Start the scrutiny server

time="2022-06-18T09:21:14+02:00" level=info msg="Trying to connect to scrutiny sqlite db: \n"

time="2022-06-18T09:21:14+02:00" level=info msg="Successfully connected to scrutiny sqlite db: \n"

panic: failed to check influxdb setup status - parse "://:": missing protocol scheme

goroutine 1 [running]:

github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0x1021e20, 0xc000136cd8}, {0x102b4f0, 0xc0003e41c0})

	/app/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xa5

github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc0003e0650, {0x102b4f0, 0xc0003e41c0})

	/app/scrutiny/webapp/backend/pkg/web/server.go:27 +0xb4

github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc0003e0650)

	/app/scrutiny/webapp/backend/pkg/web/server.go:105 +0x46b

main.main.func2(0xc0003bbc00)

	/app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x1f7

github.com/urfave/cli/v2.(*Command).Run(0xc0003e6000, 0xc0003bba80)

	/app/scrutiny/vendor/github.com/urfave/cli/v2/command.go:164 +0x64a

github.com/urfave/cli/v2.(*App).RunContext(0xc00032a180, {0x100c1f0, 0xc00013c000}, {0xc00013a000, 0x2, 0x2})

	/app/scrutiny/vendor/github.com/urfave/cli/v2/app.go:306 +0x926

github.com/urfave/cli/v2.(*App).Run(...)

	/app/scrutiny/vendor/github.com/urfave/cli/v2/app.go:215

main.main()

	/app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x679

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

Docker info:
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 31
  Running: 27
  Paused: 0
  Stopped: 4
 Images: 98
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-117-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.428GiB
 Name: nas
 ID: VB2G:TELZ:FLQM:NRKM:YLRA:TDXZ:GZSK:54PR:23SV:WAE6:P55A:54PK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by AnalogJ** [comment]
you most likely have a `SCRUTINY_WEB=true` environmental variable configured - see https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md#upgrading-from-v03x-to-v04x

Closing this issue, please comment/reopen if you run into any other issues.
