### ISSUE TITLE
[FEAT] Ability to reset the "CRC Error Count" error level. 

### ISSUE THREAD

**Issue by FingerlessGlov3s** [AnalogJ/scrutiny#309]
**Is your feature request related to a problem? Please describe.**
I had an issue while back with a dodgy SATA cable, which caused a number of CRC errors on a drive, the count is at 20 and has been for years, I've recently migrated to the new scrutiny version, and it now alerting me about this drive as failed because of the number of CRC errors. I don't believe the drive is actually faulty because it was a dodgy SATA cable.

![image](https://user-images.githubusercontent.com/3495647/174787256-d172234e-cf0d-4c06-b63c-354329522720.png)
![image](https://user-images.githubusercontent.com/3495647/174787606-6c56e11a-98ac-426c-b804-cdea961b3f7c.png)

**Describe the solution you'd like**
I would like a way to reset the alert threshold for "CRC Error Count", so when people get issues with cables, they can reset the alert threshold, or offset it. Since CRC errors are usually due to poor cable or backplane issues.

**Additional context**
None required.

**Comment by AnalogJ** [comment]
Hey @FingerlessGlov3s 
Yeah, I'm still working on the ability to enable/disable scrutiny analysis (and configure the notification thresholds) - https://github.com/AnalogJ/scrutiny/issues/275

It's still a WIP, but I'm going to close this as a dupe -- since fixing that issue will fix this :)
