### ISSUE TITLE
[BUG] Unable to delete disk with no data

### ISSUE THREAD

**Issue by adhawkins** [AnalogJ/scrutiny#314]
**Describe the bug**
While setting up on my Synology NAS, I initially had it scan all 8 bays, even though there weren't 8 disks in it. This has led to an empty entry for /dev/sata8. If I use the 'Delete Device' option on the menu for this device, when the confirmation dialog comes up, pressing 'delete' does nothing.

**Expected behavior**
Pressing 'delete' should delete the device'

**Screenshots**

![image](https://user-images.githubusercontent.com/1628607/175835789-72c5a9e3-29ce-4dae-aa4f-31980d7e6d5f.png)

![image](https://user-images.githubusercontent.com/1628607/175835798-29ec5ef7-f3af-4dde-b550-1621798f2133.png)

Version is shown as 'master#eefdc54'

**Comment by AnalogJ** [comment]
thats odd. @adhawkins can you zip up your `config` directory and email it to me at `jason@thesparktree.com`? Thanks!

**Comment by adhawkins** [comment]
Done.

**Comment by AnalogJ** [comment]
Hey @adhawkins
I finally had time to look at the db backup you provided, and it looks like the device unique identifier is blank for one of your disks, which would explain why scrutiny can't delete it.

I thought I fixed this in an earlier version, but it looks like there's a related in another function.

**Comment by adhawkins** [comment]
> Hey @adhawkins I finally had time to look at the db backup you provided, and it looks like the device unique identifier is blank for one of your disks, which would explain why scrutiny can't delete it.
> 
> I thought I fixed this in an earlier version, but it looks like there's a related in another function.

Thanks for taking a look. I assume at some point there'll be a release that contains this fix? Will give it a try then.

**Comment by AnalogJ** [comment]
yep, I fixed it in the beta branch. Basically I added extra code to ensure that empty disk identifiers are filtered out, and a database migration that deletes any existing disks with an empty identifier. 

It'll be available in the `v0.4.16` release.

**Comment by tdehaeze** [comment]
Still have the same issue with last version #ee893cc
