### ISSUE TITLE
[BUG] Temperature graph delayed?

### ISSUE THREAD

**Issue by adhawkins** [AnalogJ/scrutiny#317]
**Describe the bug**
The historic graph showing temperatures appears to be delayed. It's currently 2022-06-29 16:53. The latest data point is shown as 16:45 today. However, if I hover over the right hand edge of the graph, the latest point is 2022-06-28 12:00:00.

**Expected behavior**
The graph should show the latest data

**Screenshots**

![image](https://user-images.githubusercontent.com/1628607/176481275-5e0ba579-b7a5-4836-8b4f-c80368af726c.png)

**Comment by adhawkins** [comment]
Just gone back to it again this morning (30th June at 10am) and the graph's right hand edge is still showing 28th June 12:00.

**Comment by AnalogJ** [comment]
Yeah, there's something wrong with the aggregation queries. Looking into this right now.
