### ISSUE TITLE
New Drive Reset Data Option

### ISSUE THREAD

**Issue by exxrxxe** [AnalogJ/scrutiny#319]
There doesn't seem to be documentation, that I could find, or a GUI function on how to reset stats when replacing a drive.

Example: I have a 4 year old drive with failing sectors. I replaced the drive with a new drive that is a different size. Currently within the GUI it reports the old drives info still.

**Comment by AnalogJ** [comment]
Drives are not removed unless you delete them. 

You can delete a drive by clicking the three dots icon for a drive in the dashboard
<img width="665" alt="Screen Shot 2022-07-05 at 10 20 58 PM" src="https://user-images.githubusercontent.com/891875/177474635-50ee5376-2ae8-471b-b299-b5be2a915690.png">


That should answer your question. Feel free to reopen this issue if you need any more help.

**Comment by exxrxxe** [comment]
I only have "View Details" available? Is there a flag that is read-only somewhere? Running on Unraid with lscr.io/linuxserver/scrutiny:8e34ef8d-ls35

**Comment by AnalogJ** [comment]
you're on an old version of Scrutiny that doesn't include this functionality. 
If you migrate from the LSIO image to the official image, you'll need to follow these instructions:

https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md#upgrading-from-v03x-to-v04x

**Comment by exxrxxe** [comment]
Hugely helpful and seamless upgrade! Thank you.

**Comment by AnalogJ** [comment]
glad to hear it!
