### ISSUE TITLE
[BUG] Missing Compressed frontend

### ISSUE THREAD

**Issue by martadinata666** [AnalogJ/scrutiny#327]
**Describe the bug**
Release 0.4.15 missing web-frontend `the dist`

**Expected behavior**
Compressed web frontend available like v0.4.14

**Comment by AnalogJ** [comment]
good catch. I broke the Github Action that releases the frontend artifact. Its fixed in: https://github.com/AnalogJ/scrutiny/pull/325

I also manually uploaded the artifact to v0.4.15. 

Thanks!
