### ISSUE TITLE
[BUG] scrutiny uses wrong unit for drive capacity

### ISSUE THREAD

**Issue by dom6770** [AnalogJ/scrutiny#330]
**Describe the bug**
The displayed unit in the webinterface for drive capacity is wrong. It displays base 1000 units (GB) although the calculated size is base 1024.
It's the same issue with Windows, which also calculates with base 1042, but uses base 1000 units.
So, scrutiny calculates with base 1024, but does not use base 1042 units, which should be f.ex. Gibibyte (GiB).

**Expected behavior**
Either

a) calculate with base 1000 and display base 1000 (500 GB)
b) calculate with base 1024 and display base 1024 (465 GiB)

Preferably, let the user decide in the settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/11932291/178159597-2ad7982c-1a03-4da8-8e85-e04466d63991.png)

Same in Windows:
![image](https://user-images.githubusercontent.com/11932291/178159588-82634104-c814-4eef-8f00-f043608ee10b.png)

smartctl reports the capacity correctly
![image](https://user-images.githubusercontent.com/11932291/178159876-18dbc10a-0d6e-4904-b654-953516807611.png)

**Comment by AnalogJ** [comment]
you're not wrong, but when I added the humanize code I didn't think people would care. 

KB ~= KiB for most people. 

I'll make a note to make it configurable via something like this: https://stackoverflow.com/a/14919494

**Comment by Panzer1119** [comment]
> KB ~= KiB for most people.

Maybe, but GB and GiB already differ a little bit more, and TB and TiB can make a huge difference e.g. 18 (TB) vs 16.37 (TiB)

**Comment by AnalogJ** [comment]
`v0.5.0` has been released and fixes this issue via a dropdown in the Dashboard settings panel! Thanks for your patience!
