### ISSUE TITLE
[BUG] Scrutiny takes a long time to startup.

### ISSUE THREAD

**Issue by ariejan** [AnalogJ/scrutiny#334]
**Describe the bug**
Scrutiny takes 30+ seconds to load on first-access. Subsequent access takes ~5 seconds, until new data comes in or some internal (db?) cache has expired.

**Expected behavior**
I expect it to load faster than that. No specific target, but 30+ seconds is too long.

**Screenshots**
N/A

**Diagnosis**
I monitor 19 disks and I think the amount of data that's being loaded from `/summary` takes a long time to load. It's 42MB in total.

**Comment by AnalogJ** [comment]
can you give me some information about your environment? Are you running Scrutiny via Docker? Which version? What docker image exactly? 

v0.3.x builds had alot of problems similar to what you're describing. You may need to update to the latest image.

If you we on the LSIO image previously, you'll want to check out these instructions:
https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md#upgrading-from-v03x-to-v04x

**Comment by ariejan** [comment]
I think I might have been on old release. I did a quick deploy last time, so all volume data was deleted. It seems fast now. I'll open another ticket with more details if the problem comes back.
