### ISSUE TITLE
[BUG] Update Collector Working Directory

### ISSUE THREAD

**Issue by joe-eklund** [AnalogJ/scrutiny#335]
**Describe the bug**
I see that the `WORKDIR` is set to `/scrutiny` on[ this line.](https://github.com/AnalogJ/scrutiny/blob/c34ee85e486d623bb4ac67ee70705307391d7102/docker/Dockerfile.collector#L17)

But I see no reference to this directory anywhere else, everything seems to be located in `/opt/scrutiny/bin` now. This looks left over from the first iteration of the collector. This also means when you drop into a bash shell in the container it drops you into `/scrutiny`, but it's empty. Kinda pointless.

**Expected behavior**
I think it should instead drop you into `/` or `/opt/scrutiny/bin` or something. Unless there is some reason it's still `/scrutiny` that I am missing?

**Comment by AnalogJ** [comment]
good catch, you're exactly right. I've updated the collector WORKDIR to `/opt/scrutiny` in the beta branch. 
It'll be fixed in the next release.

**Comment by AnalogJ** [comment]
`v0.5.0` has been released and fixes this issue! Thanks for your patience!
