### ISSUE TITLE
Notifications from multiple servers

### ISSUE THREAD

**Issue by s7thamon** [AnalogJ/scrutiny#337]
Is there a way to specify the hostname somewhere so that when we receive alerts (slack) we know which host is reporting the issue? Currently using this on 4 different servers.

```
Scrutiny SMART error (EmailTest) detected on device: /dev/sda
TEST NOTIFICATION:
Scrutiny SMART error notification for device: /dev/sda
Failure Type: EmailTest
Device Name: /dev/sda
Device Serial: FAKEWDDJ324KSO
Device Type: ATA
Date: 2022-07-14T15:15:55Z
```

**Comment by AnalogJ** [comment]
Oh, this is definitely a simple QoL change. I'll get this added with the next release.

**Comment by AnalogJ** [comment]
`v0.5.0` has been released and fixes this issue! Thanks for your patience!
