### ISSUE TITLE
[FEAT] Support for systems that don't have udev

### ISSUE THREAD

**Issue by MattKobayashi** [AnalogJ/scrutiny#340]
**Is your feature request related to a problem? Please describe.**
I've recently transitioned to Alpine Linux as my host OS, and I noticed that /run/udev (required by Scrutiny for device metadata) isn't available by default. I believe the `eudev` package can replace the required functionality, but it would be nice if Scrutiny was able to work around this requirement on OSes that don't have udev.

**Describe the solution you'd like**
Implement an alternative method of gathering device metadata for OSes that don't have udev.

**Comment by AnalogJ** [comment]
Hey @MattKobayashi 
Under the hood scrutiny uses [github.com/jaypipes/ghw](https://github.com/jaypipes/ghw) to get block device information. 

Can you open an issue there about Alpine/`eudev` support?

**Comment by MattKobayashi** [comment]
Hi @AnalogJ,

I seem to have worked around the issue by installing eudev and triggering a udev update with `udevadm trigger`. I feel like it might be prudent to document this, are you averse to a PR with some extra details in the troubleshooting docs?

**Comment by AnalogJ** [comment]
Hey @MattKobayashi 
Adding this to the troubleshooting docs would be great, thanks!

**Comment by MattKobayashi** [comment]
Thanks @AnalogJ, I've opened #342 and closing this issue out. 😄
