### ISSUE TITLE
[FEAT]/Question - Connect to existing InfluxDB

### ISSUE THREAD

**Issue by BloodBlight** [AnalogJ/scrutiny#359]
This may already be possible, but if so, I don't see it in the documentation.

When attempting to deploy a central collector and UI, I tried to connect to an existing InfluxDB, but I don't see anywhere to specify an API key.

Would it be possible to add a variable for the API key?
And/or add the option to specify what port to connect to InfluxDB on so a deployment can be done that does not conflict with existing instances.

Thanks!!!

**Comment by AnalogJ** [comment]
Hey @BloodBlight, this is definitely supported.

- You can see the configuration options necessary in the `web.influxdb.*` block of the config file - https://github.com/AnalogJ/scrutiny/blob/master/example.scrutiny.yaml#L38-L49
	- all configuration file keys have an equivalent environmental variable (eg `web.influxdb.token: xxx` can also be set via `SCRUTINY_WEB_INFLUXDB_TOKEN=xxxx` )
- Here are some helpful scripts to generate the org, buckets, tasks and scoped API token that Scrutiny would create itself during first startup - https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md#bring-your-own-influxdb
- Here's a docker-compose file showing you how to run Scrutiny in hub-spoke mode (replace/remove the influxdb container and use your own hostname) - https://github.com/AnalogJ/scrutiny/blob/master/docker/example.hubspoke.docker-compose.yml

Hopefully that answers all your questions?

**Comment by BloodBlight** [comment]
I think so!!!  Thanks!  :)

**Comment by AnalogJ** [comment]
closing this issue
