### ISSUE TITLE
[FEAT] Show number of data point

### ISSUE THREAD

**Issue by artivis** [AnalogJ/scrutiny#360]
**Is your feature request related to a problem? Please describe.**
I'd like to know to number of data point per drive.

**Describe the solution you'd like**
A simple number in the drive detailed view reflecting how many times smartctl was called for that particular drive.

**Additional context**

ps- Thanks for the great tool :)

**Comment by AnalogJ** [comment]
hm. This is an interesting idea, but now that Scrutiny automatically down-samples historical data, it's going to have limited utility. 

How would you use this counter exactly?

**Comment by AnalogJ** [comment]
I'm going to close this as `wontfix`. 
While it's possible to keep an ongoing count (even with the down-sampling) I'm not quite sure what value this would add to Scrutiny.

Feel free to comment/reopen this issue if you have some additional context you're willing to share :)
