### ISSUE TITLE
Collection failure when connected devices are across separate buses

### ISSUE THREAD

**Issue by teambvd** [AnalogJ/scrutiny#37]
When running the collector, any device not connected to the first bus scanned fails to load. For reference, here's what the UI shows:
![Scrutiny_display](https://user-images.githubusercontent.com/70113838/93712549-38462a80-fb1c-11ea-9b06-c67e02a63eb4.png)

There are several options here, the easiest of which would be something like 'if <smartcl -a> returns error, then <smartcl -x> AND <smartctl -l selftest /dev/sdBLAH>, end if / else end' - I've confirmed that these devices show their data properly in this case.

Take, for example:
```
smartctl -a /dev/sdz
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-4.19.107-Unraid] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               IBM-ESXS
Product:              ST3000NM0043  E
Revision:             EC5L
Compliance:           SPC-4
User Capacity:        3,000,592,982,016 bytes [3.00 TB]
Logical block size:   512 bytes
LU is fully provisioned
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000c50083ef0e8f
Serial number:        Z1Y3HGGZ0000R553JSTG
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Sun Sep 20 13:04:25 2020 CDT
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Current Drive Temperature:     38 C
Drive Trip Temperature:        65 C

```
Additionally, I can kick off a smart test as well:
```
smartctl -t short /dev/sdz
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-4.19.107-Unraid] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

```
Short Background Self Test has begun
Use smartctl -X to abort test

The drives still have smart, it just has to be queried explicitly (when connected through an add-in device which supports it):
```
smartctl -l selftest /dev/sdz
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-4.19.107-Unraid] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART Self-test log
Num  Test              Status                 segment  LifeTime  LBA_first_err [SK ASC ASQ]
     Description                              number   (hours)
# 1  Background short  Completed                   -   31426                 - [-   -    -]
# 2  Background long   Completed                   -   31250                 - [-   -    -]
```

While it may not provide you the level of detail, I'm sure other options exist to query them (likely using sdparm... it's just been so long since I've messed with it that I can't remember it all currently, sorry!)

At the very least, this will give you the number of hours for the drive as well as it's SMART status, which while not perfect, is a great start.

**Comment by AnalogJ** [comment]
Hey @teambvd 

So if I'm reading this correctly, you're saying that `smartctl -a /dev/sdX` returns an error but `smartctl -x /dev/sdX` works correctly?

I'm actually testing out a completely new (& hopefully more robust) device detection method, would you be willing to test it and see if it's still broken there? The code lives in the smartctl_scan branch, and I've created a Docker image for it.

Can you try running the following command, and tell me if everything looks correct?

```
docker run --rm -p 8080:8080 \
-v /dev/disk:/dev/disk \
-v /run/udev:/run/udev:ro \
--name scrutiny \
--privileged analogj/scrutiny:smartctl_scan
```

You'll need to exec into the container and start the collector manually too:

```
docker exec scrutiny scrutiny-collector-metrics run --debug --log-file /tmp/test.log
```

If it's still broken, it would be super helpful if you could attach the logfile from the collector: 

```
docker cp scrutiny:/tmp/test.log test.log
```

**Comment by teambvd** [comment]
Certainly, happy to help! To be clear, the '-a' switch only appears to work with *some* devices. I did some further testing and found that the bus in use doesn't matter. 

Unfortunately it looks like my version doesn't have a --log-file function:
```
docker exec scrutiny scrutiny-collector-metrics run --debug --log-file /tmp/test.log

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                               dev-0.1.13

Incorrect Usage: flag provided but not defined: -log-file
```

Looks like the -log-file switch won't let you save out of context, so I just provided a file name within the local directory:
`root@a955541dfea6:/scrutiny# scrutiny-collector-metrics run --debug > logfile.txt`
[logfile.txt](https://github.com/AnalogJ/scrutiny/files/5252546/logfile.txt)

No change in the *number* of drives which reported in properly and those that didn't previously though which ones reported and which ones did not, that was different. 

Confirming version of smartmontools in use:
```
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-4.19.107-Unraid] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org
```

The fact that two of my 6TB WD6003FFBX (SATA) drives, running the same firmware, had different results gave me an idea. On a hunch, I hooked up a UART debugger to take a lower level view of what's going on. 

Looking at the timing of events on the i2c bus, I think part of what's happening is that the commands are ran too quickly in sequence for all drives to report in properly; might be worth spacing out the tests, i.e. "query + COUNT number of devices, add devices to array, run against one every X minutes/seconds/whatever until COUNT satisfied, sleep till INTERVAL is satisfied, begin again". Seems entirely possible this is simply a scaling problem.

**Comment by AnalogJ** [comment]
Yeah, the collector in the `analogj/scrutiny:smartctl_scan` image is completely different from the `analogj/scrutiny` image. 

If you don't want to shut down your existing scrutiny container, you can bind it to a new port and give it a unique container name:

```
docker run --rm -p 9090:8080 \
-v /dev/disk:/dev/disk \
-v /run/udev:/run/udev:ro \
--name scrutinysmartctl \
--privileged analogj/scrutiny:smartctl_scan
```

and then exec into the container and start the collector manually :

```
docker exec scrutinysmartctl scrutiny-collector-metrics run --debug --log-file /tmp/test.log
```

Adding an offset/backoff for the collector processing is a great idea. I have a couple thoughts on how I could make that work, thanks.

**Comment by teambvd** [comment]
To be clear, in case I'm misunderstanding something, I did the above and attached the log file in line, but after re-reading through it understood I hadn't. Running through the above I ended up with the same issue, again with separate disks, but only 10 disks reporting this time. 

On a whim, I shut down my running VMs, then re-ran with metrics collection you noted - and now, 18 disks reported. Finally, I stopped the docker service and ran it one final time, at which point it was successful across all drives; definitely feels like a scaling problem!

Now that I felt like I had a handle on what was causing this, I went back to the original container; even with 0 load, it still had issues, so I still think there's real value to the modified collection method. Pegging all at once can cause some weirdness with iowait as well, at least based on some limited testing (ZoL/ZFS filesystem in use, in the event that matters).

**Comment by AnalogJ** [comment]
Ugh, I wish I could replicate this issue on my local server. If you can provide me with that log file, it would be super helpful. I'm planning on adding a randomized delay for each "thread" so they dont all hit the system at the same time, however it would be nice if there is a specific exit code or error message from `smartctl` that I can watch out for an trigger a retry on. 
This data would be included in the log file. 

You can use the latest `analogj/scrutiny` image now. I've merged my `smartctl_scan` branch into master.

**Comment by AnalogJ** [comment]
Ok. I've removed all collector concurrency from the `master` branch. Can you verify that it fixed your issue?

**Comment by teambvd** [comment]
I do plan on gettin you a copy of the log file, just going to be a bit. Gonna clean up the previous installs, run the (now merged) version, and then get it over to you. Employers - for whatever reason, they think just because they give me money, I have to 'do work'; sheesh, the nerve! 😁 

I hope to have time to get this done tonight.

**Comment by teambvd** [comment]
Looks like it's going to be another day FYI - I neglected the fact that I'd cron'd a backup that begins the 21st evening of each month, and as it's about 13TB, it's not going to finish till sometime after midnight or so; still plan on getting this sent your way.

**Comment by AnalogJ** [comment]
No worries!

I've updated scrutiny again, to add support for debug logging and writing to log files. If you could use these instructions for your testing, it would make things much easier for me :)

```
docker run -it --rm -p 8080:8080 \
-v /run/udev:/run/udev:ro \
-v /dev/disk:/dev/disk \
-e DEBUG=true \
-e COLLECTOR_LOG_FILE=/tmp/collector.log \
-e SCRUTINY_LOG_FILE=/tmp/web.log \
--name scrutiny \
--privileged analogj/scrutiny

# in another terminal trigger the collector
docker exec scrutiny scrutiny-collector-metrics run

# then use docker cp to copy the log files out of the container.
docker cp scrutiny:/tmp/collector.log collector.log
docker cp scrutiny:/tmp/web.log web.log
```

**Comment by AnalogJ** [comment]
Hey @teambvd can you verify that everything works with the latest image?

**Comment by teambvd** [comment]
Finally had some time - while it looks like it's now able to communicate properly, it's not able to pull/populate the power-on hours for whatever reason in the dashboard for the vast majority of drives:
![Screen Shot 2020-09-25 at 12 47 14 PM](https://user-images.githubusercontent.com/70113838/94299472-54d3cf80-ff2d-11ea-9d29-c437ba85c2f3.png)

However, the output is displayed when commands manually ran from the host:
```
root@Tower:~# smartctl -x /dev/sdi
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-4.19.107-Unraid] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               TOSHIBA
Product:              MG03SCA300
Revision:             DG04
Compliance:           SPC-4
User Capacity:        3,000,592,982,016 bytes [3.00 TB]
Logical block size:   512 bytes
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x50000395f8d35e51
Serial number:        Z4K0A12YFVL9
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Fri Sep 25 12:37:33 2020 CDT
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Disabled or Not Supported
Read Cache is:        Enabled
Writeback Cache is:   Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Current Drive Temperature:     33 C
Drive Trip Temperature:        65 C

Manufactured in week 51 of year 2014
Specified cycle count over device lifetime:  50000
Accumulated start-stop cycles:  128
Specified load-unload count over device lifetime:  600000
Accumulated load-unload cycles:  45502
Elements in grown defect list: 0
```
(etc)

And the log file! Finally attached:
[test.log](https://github.com/AnalogJ/scrutiny/files/5284510/test.log)

**Comment by teambvd** [comment]
@AnalogJ as we're now able to at least communicate with the devices, should this one be closed out, then a new one opened for the failure to report power on hours? Or how would you prefer we proceed?

**Comment by AnalogJ** [comment]
Apologies @teambvd I've been a bit busy the last couple of days. Yeah, I think its a good idea to close this issue out, and create a new one specifically for the power on hours. 
I'll do that now and reference this issue. 

Thanks so much for that test.log file. I'll take a look at it and hopefully I can figure out the underlying issue.
