### ISSUE TITLE
How do I specify a device type with docker compose

### ISSUE THREAD

**Issue by andres-asm** [AnalogJ/scrutiny#371]
Hi

I have a few devices behind a USB bridge, so I have to specify device type: sat
Is there anyway to do so when using docker compose?

**Comment by AnalogJ** [comment]
You'll need to create a collector config file:

https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#collector-config-file

This section might also be handy: https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#usb-devices

I'm going to close this issue for now, but feel free to reopen if you run into any issues with those docs!

**Comment by andres-asm** [comment]
Thank you
