### ISSUE TITLE
[FEAT] Unraid CA Install. Guide? Is this correct? /opt/scrutiny/*

### ISSUE THREAD

**Issue by Natedude** [AnalogJ/scrutiny#373]
**Is your feature request related to a problem? Please describe.**
When I click install in the Community Apps page it brings me to this.

![Screen Shot 2022-09-23 at 5 30 00 AM](https://user-images.githubusercontent.com/5846465/191960589-618f2975-9ae2-4c5e-b828-d834dd69821d.png)

- I was looking at t his except the Config and Database fields were empty.
- I assumed that having "Container Path: /opt/scrutiny/config" and "Container Path: /opt/scrutiny/influxdb" there under the originally blank lines meant that I should just use that. 

**Describe the solution you'd like**
It would be great is there was just minimally more guidance on setup. Like an note that if those are the correct locations, than to just copy and paste those paths so I knew I was setting it up right.

**Additional context**
Could you make a video about it specifically for Unraid users? Thanks

Was correct what I did by copy and pasting and putting  /opt/scrutiny/config in the config field and same for the database field??????

Thanks

**Comment by AnalogJ** [comment]
Hey @Natedude 
I didn't write the Unraid Community App integration for Scrutiny, but from what I'm seeing in the UI, those fields are being used to setup bind mounts between the host and container. Specifically the host side of the bind mount. 

You can see something similar in my Docker compose file: 
https://github.com/AnalogJ/scrutiny/blob/master/docker/example.omnibus.docker-compose.yml#L12-L15

In your case, you'll probably want your host path to be something like `/myhost/datadrive/directory/scrutiny/config` and `/myhost/datadrive/directory/scrutiny/influxdb` where the host directories are paths on your storage drives (as opposed to `/opt/scrutiny` which would most likely be on your  OS disk) 

Hopefully that answers all your questions? I'll close this issue for now, but feel free to comment or reopen.
