### ISSUE TITLE
[BUG] Failed - Command Timeout Segate

### ISSUE THREAD

**Issue by Susosvk** [AnalogJ/scrutiny#382]
**Describe the bug**
I have Segate HDD USB and debian OS - DIsable USB -UAS
I check hdd on windows smart check and disk is Healt OK

**Scree
![Untitled](https://user-images.githubusercontent.com/21984307/195530364-2fe5cfef-0116-4455-ba12-356922306cf4.png)
nshots**

**Comment by ForsakenRei** [comment]
I saw similar things on two of my SATA SSDs, they both passed smart short test and show command timeout in Scrutiny. 

While if you use `smartctl -a /dev/sdb` you should be able to see whether it's really have command timeout, for my case yes they do. As the numbers are quite small and didn't change and they happened before I added them to my system, it's generally OK. It's a critical attributes for sure, if you see the number increases then it might need to be replaced.

**Comment by Susosvk** [comment]
I use command smartctl -a /dev/sdb its all ok but dont show me ID 188
Segate dont have ID 188 on smartctl 

https://www.smartmontools.org/wiki/AttributesSeagate

Meaby fix for this bug - Segate hdd ignore ID 188

**Comment by wanderling** [comment]
I am also running into this particular bug. Scrutiny marks my two brand new Seagate drives as failed with excessive 'Command Timeouts'. Running smartctl -a on the drives in question they pass all smart checks: 
<pre><code>SMART Attributes Data Structure revision number: 10
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000f   078   077   006    Pre-fail  Always       -       58897940
  3 Spin_Up_Time            0x0003   097   096   000    Pre-fail  Always       -       0
  4 Start_Stop_Count        0x0032   100   100   020    Old_age   Always       -       284
  5 Reallocated_Sector_Ct   0x0033   100   100   010    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000f   100   253   045    Pre-fail  Always       -       715885
  9 Power_On_Hours          0x0032   099   099   000    Old_age   Always       -       878
 10 Spin_Retry_Count        0x0013   100   100   097    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   020    Old_age   Always       -       2
183 Runtime_Bad_Block       0x0032   100   100   000    Old_age   Always       -       0
184 End-to-End_Error        0x0032   100   100   099    Old_age   Always       -       0
187 Reported_Uncorrect      0x0032   100   100   000    Old_age   Always       -       0
<b><i>188 Command_Timeout         0x0032   099   098   000    Old_age   Always       -       5</i></b>
189 High_Fly_Writes         0x003a   100   100   000    Old_age   Always       -       0
190 Airflow_Temperature_Cel 0x0022   060   056   040    Old_age   Always       -       40 (Min/Max 27/44)
191 G-Sense_Error_Rate      0x0032   100   100   000    Old_age   Always       -       0
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       1
193 Load_Cycle_Count        0x0032   100   100   000    Old_age   Always       -       329
194 Temperature_Celsius     0x0022   040   044   000    Old_age   Always       -       40 (0 23 0 0 0)
195 Hardware_ECC_Recovered  0x001a   078   077   000    Old_age   Always       -       58897940
197 Current_Pending_Sector  0x0012   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0010   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x003e   200   200   000    Old_age   Always       -       0
240 Head_Flying_Hours       0x0000   100   253   000    Old_age   Offline      -       145 (183 208 0)
241 Total_LBAs_Written      0x0000   100   253   000    Old_age   Offline      -       2477203161
242 Total_LBAs_Read         0x0000   100   253   000    Old_age   Offline      -       71890218

SMART Error Log Version: 1
No Errors Logged
</pre></code>

I propose an option to check a box on the drive settings page that allows the admin user to ignore a check completely. This should allow you to leave the database intact while giving the admin user some control over errors and issues.

**Comment by johnthq** [comment]
debian 11 docker compose
Brand new Seagate Hybrid shows 1 command timeout but smartctl -a shows 0. drive marked as failed. this is kind of annoying.

**Comment by AnalogJ** [comment]
Unfortunately this is a known issue with Seagate drives - https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#seagate-drives-failing

I'm already disabling some analysis for Seek Error Rate & Read Error Rate, and now it looks like I may also need to do this for `Command Timeout` .


I really don't like excluding this analysis completely. I wonder if there's a way to detect and normalize this data before comparing against Backblaze's thresholds.

**Comment by PetrusZ** [comment]
WD has the same issue, failed in scrutiny, but passed in `smartctl -a`

![CleanShot 2023-04-24 at 10 45 06@2x](https://user-images.githubusercontent.com/4990592/233889188-8cd1b770-f968-47a9-9c6b-dedfc37e5fba.png)

![CleanShot 2023-04-24 at 10 47 03@2x](https://user-images.githubusercontent.com/4990592/233889298-fc5a0040-be8b-4f60-aa1a-1aa865a0c431.png)

**Comment by joshua-pe** [comment]
Having the same issue. Here's my full report. Initially I wasn't sure if it was the drive actually failing and I should RMA, but seeing this thread eases my concern I think.
![image](https://github.com/AnalogJ/scrutiny/assets/63589370/8a0dcb1c-c2bf-461d-8dba-9fc023fdbf68)

**Comment by aaron9610** [comment]
Having the same issue. Does anyone know the solution?

**Comment by hamlynt** [comment]
Same issue here with Seagate Ironwolf 18TB `command timeout`.

I have three of 11 drives generating this alert daily. Disabling this check would at least avoid false positives.

**Comment by kaysond** [comment]
This is mainly an issue with the thresholds (see #510). Until #512 gets merged, you can build my fork to address this: https://github.com/kaysond/scrutiny/tree/master (clone it, then run `make docker-web`, then switch your compose file to use the `analogj/scrutiny-dev:web` image)

**Comment by AnalogJ** [comment]
Closing this now that #512 is merged, Feel free to comment/reopen if this is still a problem.

**Comment by firasdib** [comment]
@AnalogJ I'm not convinced this is solved. I believe the value has to be parsed to be accurately analyzed, not compared as is, since it represents number of operations as well. Please see https://github.com/AnalogJ/scrutiny/issues/522 for further details.

**Comment by SiLenCe-WB** [comment]
I'm having a similar issue with three Seagate Ironwolfs. I'm using them inside a Synology box. This is what the GUI shows:
SDA: https://gyazo.com/729b0a623cc814519bed02420a05495d
SDB: https://gyazo.com/f5041b549e6c99d14e50c7a66c96b127
SDC: https://gyazo.com/cc671e75fe29aa69c7723beb70feacb2

Is this something we should be worried about? Or are these just bugs? And can it be fixed?

PS: I used [this guide](https://drfrankenstein.co.uk/2022/07/28/scrutiny-in-docker-on-a-synology-nas/) to set it up.

**Comment by kaysond** [comment]
> I'm having a similar issue with three Seagate Ironwolfs. I'm using them inside a Synology box. This is what the GUI shows: SDA: https://gyazo.com/729b0a623cc814519bed02420a05495d SDB: https://gyazo.com/f5041b549e6c99d14e50c7a66c96b127 SDC: https://gyazo.com/cc671e75fe29aa69c7723beb70feacb2
> 
> Is this something we should be worried about? Or are these just bugs? And can it be fixed?
> 
> PS: I used [this guide](https://drfrankenstein.co.uk/2022/07/28/scrutiny-in-docker-on-a-synology-nas/) to set it up.

@SiLenCe-WB - see comments here: https://github.com/AnalogJ/scrutiny/issues/522

**Comment by SiLenCe-WB** [comment]
I read that thread but I don't really know what to make of it. I don't get any errors; just warnings. And I don't really know how to get rid of them, as they are false positives.

Anyway, since they all display a healthy status (passed), I will not worry about it.

**Comment by kaysond** [comment]
> I read that thread but I don't really know what to make of it. I don't get any errors; just warnings. And I don't really know how to get rid of them, as they are false positives.
> 
> Anyway, since they all display a healthy status (passed), I will not worry about it.

For some drives the SMART values aren't being decoded properly. You can tell by clicking on that row in scrutiny and looking at the RAW value. It's fixed by setting up a `collector.yaml` file as described in the readme and [this comment](https://github.com/AnalogJ/scrutiny/issues/522#issuecomment-1775724077).

In your case, though, I think at a value of 100 it must be real, so it is a potential issue, but only if it gets much, much bigger. More often it's just that you get some command timeouts if the cable/drive is bumped, or the link is bad.

**Comment by SiLenCe-WB** [comment]
Two of those drives are from december last year and the last one is from may but they show the same values, so I'm pretty sure the drives are fine. And I've never taken them out of the Synology NAS since I bought them.

edit: I just bought two new drives (same model) and they show the same "issue". So I'm pretty sure the drives are perfectly fine.
