### ISSUE TITLE
[BUG] Display Title Label not working

### ISSUE THREAD

**Issue by jeremehancock** [AnalogJ/scrutiny#383]
**Describe the bug**
Setting the Display Title in the settings to Label doesn't work. 

**Expected behavior**
I have added labels to my drives so I would expect them to show as the Display Title when set to Label.

**Screenshots**
![image](https://user-images.githubusercontent.com/1692414/195721492-bb94cc51-1593-4a31-849a-cd59b70df4df.png)
![image](https://user-images.githubusercontent.com/1692414/195721533-ef574b25-1fdd-4147-a3a4-5cc4022ce11f.png)

**Comment by AnalogJ** [comment]
That's what I would expect as well - https://github.com/AnalogJ/scrutiny/blob/master/webapp/frontend/src/app/shared/device-title.pipe.ts#L29-L33

- What version of scrutiny are you running?
- can you attach the output of the `/api/summary` url? eg. `https://scrutiny.example.com/api/summary`

**Comment by jeremehancock** [comment]
I am running the latest version.

Here is the output.
`// 20221014072253
// http://overseer:8008/api/summary

{
  "data": {
    "summary": {
      "0x5000cca291d4f59c": {
        "device": {
          "CreatedAt": "2022-10-01T17:39:49.982279139Z",
          "UpdatedAt": "2022-10-14T00:00:03.119167676Z",
          "DeletedAt": null,
          "wwn": "0x5000cca291d4f59c",
          "device_name": "sdd",
          "device_uuid": "",
          "device_serial_id": "scsi-35000000000000001",
          "device_label": "",
          "manufacturer": "",
          "model_name": "HGST HUH721212ALE604",
          "interface_type": "",
          "interface_speed": "6.0 Gb/s",
          "serial_number": "5PHH3AKF",
          "firmware": "LEGNW925",
          "rotational_speed": 7200,
          "capacity": 12000138625024,
          "form_factor": "3.5 inches",
          "smart_support": false,
          "device_protocol": "ATA",
          "device_type": "sat",
          "label": "",
          "host_id": "",
          "device_status": 0
        },
        "smart": {
          "collector_date": "2022-10-14T00:00:01Z",
          "temp": 33,
          "power_on_hours": 10161
        },
        "temp_history": [
          {
            "date": "2022-10-02T02:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-07T22:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-07T23:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-08T00:00:00Z",
            "temp": 36
          },
          {
            "date": "2022-10-08T01:00:00Z",
            "temp": 36
          },
          {
            "date": "2022-10-08T22:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-08T23:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-09T00:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-09T01:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-09T22:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-09T23:00:00Z",
            "temp": 32
          },
          {
            "date": "2022-10-10T00:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-10T01:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-10T22:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-10T23:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-11T00:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-11T01:00:00Z",
            "temp": 37
          },
          {
            "date": "2022-10-11T22:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-11T23:00:00Z",
            "temp": 32
          },
          {
            "date": "2022-10-12T00:00:00Z",
            "temp": 32
          },
          {
            "date": "2022-10-12T01:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-12T14:00:00Z",
            "temp": 36
          },
          {
            "date": "2022-10-12T15:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-12T16:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-12T17:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-12T18:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-12T19:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-12T20:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-12T21:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-12T22:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-12T23:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-13T00:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-13T01:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-13T18:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-13T19:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-13T20:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-13T21:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-13T22:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-13T23:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-14T00:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-14T01:00:00Z",
            "temp": 34
          }
        ]
      },
      "0x5000cca2a1d17a5d": {
        "device": {
          "CreatedAt": "2022-10-01T17:39:49.986820333Z",
          "UpdatedAt": "2022-10-14T00:00:05.071597913Z",
          "DeletedAt": null,
          "wwn": "0x5000cca2a1d17a5d",
          "device_name": "sde",
          "device_uuid": "",
          "device_serial_id": "scsi-35000000000000001",
          "device_label": "",
          "manufacturer": "",
          "model_name": "WDC WD140EDGZ-11B2DA2",
          "interface_type": "",
          "interface_speed": "6.0 Gb/s",
          "serial_number": "2CH7EXLN",
          "firmware": "85.00A85",
          "rotational_speed": 7200,
          "capacity": 14000519643136,
          "form_factor": "3.5 inches",
          "smart_support": false,
          "device_protocol": "ATA",
          "device_type": "sat",
          "label": "",
          "host_id": "",
          "device_status": 0
        },
        "smart": {
          "collector_date": "2022-10-14T00:00:03Z",
          "temp": 34,
          "power_on_hours": 4618
        },
        "temp_history": [
          {
            "date": "2022-10-02T02:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-07T22:00:00Z",
            "temp": 36
          },
          {
            "date": "2022-10-07T23:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-08T00:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-08T01:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-08T22:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-08T23:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-09T00:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-09T01:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-09T22:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-09T23:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-10T00:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-10T01:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-10T22:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-10T23:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-11T00:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-11T01:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-11T22:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-11T23:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-12T00:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-12T01:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-12T14:00:00Z",
            "temp": 37
          },
          {
            "date": "2022-10-12T15:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-12T16:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-12T17:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-12T18:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-12T19:00:00Z",
            "temp": 36
          },
          {
            "date": "2022-10-12T20:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-12T22:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-12T23:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-13T00:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-13T01:00:00Z",
            "temp": 36
          },
          {
            "date": "2022-10-13T18:00:00Z",
            "temp": 36
          },
          {
            "date": "2022-10-13T19:00:00Z",
            "temp": 36
          },
          {
            "date": "2022-10-13T20:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-13T21:00:00Z",
            "temp": 37
          },
          {
            "date": "2022-10-13T22:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-13T23:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-14T00:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-14T01:00:00Z",
            "temp": 35
          }
        ]
      },
      "0x5000cca2adc159e2": {
        "device": {
          "CreatedAt": "2022-10-01T17:39:49.978068863Z",
          "UpdatedAt": "2022-10-14T00:00:07.16498232Z",
          "DeletedAt": null,
          "wwn": "0x5000cca2adc159e2",
          "device_name": "sdb",
          "device_uuid": "",
          "device_serial_id": "scsi-35000000000000001",
          "device_label": "",
          "manufacturer": "",
          "model_name": "WDC WD140EDGZ-11B1PA0",
          "interface_type": "",
          "interface_speed": "6.0 Gb/s",
          "serial_number": "Y6G2Z4AC",
          "firmware": "85.00A85",
          "rotational_speed": 7200,
          "capacity": 14000519643136,
          "form_factor": "3.5 inches",
          "smart_support": false,
          "device_protocol": "ATA",
          "device_type": "sat",
          "label": "",
          "host_id": "",
          "device_status": 0
        },
        "smart": {
          "collector_date": "2022-10-14T00:00:06Z",
          "temp": 34,
          "power_on_hours": 5523
        },
        "temp_history": [
          {
            "date": "2022-10-02T02:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-07T22:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-07T23:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-08T00:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-08T01:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-08T22:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-08T23:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-09T00:00:00Z",
            "temp": 32
          },
          {
            "date": "2022-10-09T01:00:00Z",
            "temp": 32
          },
          {
            "date": "2022-10-09T22:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-09T23:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-10T00:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-10T01:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-10T22:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-10T23:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-11T00:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-11T01:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-11T22:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-11T23:00:00Z",
            "temp": 32
          },
          {
            "date": "2022-10-12T00:00:00Z",
            "temp": 32
          },
          {
            "date": "2022-10-12T01:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-12T14:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-12T15:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-12T16:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-12T17:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-12T18:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-12T19:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-12T20:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-12T22:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-12T23:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-13T00:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-13T01:00:00Z",
            "temp": 35
          },
          {
            "date": "2022-10-13T18:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-13T19:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-13T20:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-13T21:00:00Z",
            "temp": 34
          },
          {
            "date": "2022-10-13T22:00:00Z",
            "temp": 33
          },
          {
            "date": "2022-10-13T23:00:00Z",
            "temp": 32
          },
          {
            "date": "2022-10-14T00:00:00Z",
            "temp": 32
          },
          {
            "date": "2022-10-14T01:00:00Z",
            "temp": 34
          }
        ]
      },
      "0x50014ee21295bbeb": {
        "device": {
          "CreatedAt": "2022-10-01T17:39:49.973926711Z",
          "UpdatedAt": "2022-10-14T00:00:05.752899629Z",
          "DeletedAt": null,
          "wwn": "0x50014ee21295bbeb",
          "device_name": "sdf",
          "device_uuid": "",
          "device_serial_id": "usb-WD_Game_Drive_575836324432304B43504C32-0:0",
          "device_label": "",
          "manufacturer": "",
          "model_name": "WDC WD50NMZW-59A8NS1",
          "interface_type": "",
          "interface_speed": "6.0 Gb/s",
          "serial_number": "WD-WX62D20KCPL2",
          "firmware": "01.01A01",
          "rotational_speed": 5400,
          "capacity": 5000947523584,
          "form_factor": "2.5 inches",
          "smart_support": false,
          "device_protocol": "ATA",
          "device_type": "sat",
          "label": "",
          "host_id": "",
          "device_status": 0
        },
        "smart": {
          "collector_date": "2022-10-14T00:00:05Z",
          "temp": 39,
          "power_on_hours": 13387
        },
        "temp_history": [
          {
            "date": "2022-10-02T02:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-07T22:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-07T23:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-08T00:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-08T01:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-08T22:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-08T23:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-09T00:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-09T01:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-09T22:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-09T23:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-10T00:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-10T01:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-10T22:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-10T23:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-11T00:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-11T01:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-11T22:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-11T23:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-12T00:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-12T01:00:00Z",
            "temp": 40
          },
          {
            "date": "2022-10-12T14:00:00Z",
            "temp": 41
          },
          {
            "date": "2022-10-12T15:00:00Z",
            "temp": 40
          },
          {
            "date": "2022-10-12T16:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-12T17:00:00Z",
            "temp": 40
          },
          {
            "date": "2022-10-12T18:00:00Z",
            "temp": 40
          },
          {
            "date": "2022-10-12T19:00:00Z",
            "temp": 41
          },
          {
            "date": "2022-10-12T20:00:00Z",
            "temp": 40
          },
          {
            "date": "2022-10-12T22:00:00Z",
            "temp": 44
          },
          {
            "date": "2022-10-12T23:00:00Z",
            "temp": 40
          },
          {
            "date": "2022-10-13T00:00:00Z",
            "temp": 41
          },
          {
            "date": "2022-10-13T01:00:00Z",
            "temp": 40
          },
          {
            "date": "2022-10-13T18:00:00Z",
            "temp": 42
          },
          {
            "date": "2022-10-13T19:00:00Z",
            "temp": 40
          },
          {
            "date": "2022-10-13T20:00:00Z",
            "temp": 41
          },
          {
            "date": "2022-10-13T21:00:00Z",
            "temp": 41
          },
          {
            "date": "2022-10-13T22:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-13T23:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-14T00:00:00Z",
            "temp": 39
          },
          {
            "date": "2022-10-14T01:00:00Z",
            "temp": 40
          }
        ]
      },
      "0x5001b444a64d3e0d": {
        "device": {
          "CreatedAt": "2022-10-01T17:39:49.996059687Z",
          "UpdatedAt": "2022-10-14T00:00:06.226565439Z",
          "DeletedAt": null,
          "wwn": "0x5001b444a64d3e0d",
          "device_name": "sda",
          "device_uuid": "",
          "device_serial_id": "ata-SanDisk_X400_M.2_2280_512GB_164002420126",
          "device_label": "",
          "manufacturer": "",
          "model_name": "SanDisk X400 M.2 2280 512GB",
          "interface_type": "",
          "interface_speed": "6.0 Gb/s",
          "serial_number": "164002420126",
          "firmware": "X4130012",
          "rotational_speed": 0,
          "capacity": 512110190592,
          "form_factor": "M.2",
          "smart_support": false,
          "device_protocol": "ATA",
          "device_type": "scsi",
          "label": "",
          "host_id": "",
          "device_status": 0
        },
        "smart": {
          "collector_date": "2022-10-14T00:00:06Z",
          "temp": 49,
          "power_on_hours": 8353
        },
        "temp_history": [
          {
            "date": "2022-10-02T02:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-07T20:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-07T21:00:00Z",
            "temp": 48
          },
          {
            "date": "2022-10-07T22:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-07T23:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-08T00:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-08T01:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-08T20:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-08T21:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-08T22:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-08T23:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-09T00:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-09T01:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-09T20:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-09T21:00:00Z",
            "temp": 48
          },
          {
            "date": "2022-10-09T22:00:00Z",
            "temp": 48
          },
          {
            "date": "2022-10-09T23:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-10T00:00:00Z",
            "temp": 48
          },
          {
            "date": "2022-10-10T01:00:00Z",
            "temp": 50
          },
          {
            "date": "2022-10-10T20:00:00Z",
            "temp": 48
          },
          {
            "date": "2022-10-10T21:00:00Z",
            "temp": 48
          },
          {
            "date": "2022-10-10T22:00:00Z",
            "temp": 48
          },
          {
            "date": "2022-10-10T23:00:00Z",
            "temp": 48
          },
          {
            "date": "2022-10-11T00:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-11T01:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-11T20:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-11T21:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-11T22:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-11T23:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-12T00:00:00Z",
            "temp": 50
          },
          {
            "date": "2022-10-12T01:00:00Z",
            "temp": 51
          },
          {
            "date": "2022-10-12T11:00:00Z",
            "temp": 52
          },
          {
            "date": "2022-10-12T12:00:00Z",
            "temp": 51
          },
          {
            "date": "2022-10-12T13:00:00Z",
            "temp": 50
          },
          {
            "date": "2022-10-12T14:00:00Z",
            "temp": 48
          },
          {
            "date": "2022-10-12T15:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-12T16:00:00Z",
            "temp": 50
          },
          {
            "date": "2022-10-12T17:00:00Z",
            "temp": 52
          },
          {
            "date": "2022-10-12T18:00:00Z",
            "temp": 52
          },
          {
            "date": "2022-10-12T19:00:00Z",
            "temp": 51
          },
          {
            "date": "2022-10-12T20:00:00Z",
            "temp": 52
          },
          {
            "date": "2022-10-12T21:00:00Z",
            "temp": 50
          },
          {
            "date": "2022-10-12T22:00:00Z",
            "temp": 51
          },
          {
            "date": "2022-10-12T23:00:00Z",
            "temp": 51
          },
          {
            "date": "2022-10-13T00:00:00Z",
            "temp": 51
          },
          {
            "date": "2022-10-13T01:00:00Z",
            "temp": 52
          },
          {
            "date": "2022-10-13T16:00:00Z",
            "temp": 52
          },
          {
            "date": "2022-10-13T17:00:00Z",
            "temp": 52
          },
          {
            "date": "2022-10-13T18:00:00Z",
            "temp": 51
          },
          {
            "date": "2022-10-13T19:00:00Z",
            "temp": 51
          },
          {
            "date": "2022-10-13T20:00:00Z",
            "temp": 50
          },
          {
            "date": "2022-10-13T21:00:00Z",
            "temp": 49
          },
          {
            "date": "2022-10-13T22:00:00Z",
            "temp": 50
          },
          {
            "date": "2022-10-13T23:00:00Z",
            "temp": 51
          },
          {
            "date": "2022-10-14T00:00:00Z",
            "temp": 52
          },
          {
            "date": "2022-10-14T01:00:00Z",
            "temp": 52
          }
        ]
      },
      "0x50024e900289a4b9": {
        "device": {
          "CreatedAt": "2022-10-01T17:39:49.991710435Z",
          "UpdatedAt": "2022-10-14T00:00:07.905186676Z",
          "DeletedAt": null,
          "wwn": "0x50024e900289a4b9",
          "device_name": "sdc",
          "device_uuid": "",
          "device_serial_id": "scsi-35000000000000001",
          "device_label": "",
          "manufacturer": "",
          "model_name": "SAMSUNG HD154UI",
          "interface_type": "",
          "interface_speed": "",
          "serial_number": "S1Y6J1MSB05270",
          "firmware": "1AG01118",
          "rotational_speed": 0,
          "capacity": 1500301910016,
          "form_factor": "",
          "smart_support": false,
          "device_protocol": "ATA",
          "device_type": "sat",
          "label": "",
          "host_id": "",
          "device_status": 0
        },
        "smart": {
          "collector_date": "2022-10-14T00:00:07Z",
          "temp": 25,
          "power_on_hours": 51892
        },
        "temp_history": [
          {
            "date": "2022-10-02T02:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-07T22:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-07T23:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-08T00:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-08T01:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-08T22:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-08T23:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-09T00:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-09T01:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-09T22:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-09T23:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-10T00:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-10T01:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-10T22:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-10T23:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-11T00:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-11T01:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-11T22:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-11T23:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-12T00:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-12T01:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-12T14:00:00Z",
            "temp": 27
          },
          {
            "date": "2022-10-12T15:00:00Z",
            "temp": 27
          },
          {
            "date": "2022-10-12T16:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-12T17:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-12T18:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-12T19:00:00Z",
            "temp": 27
          },
          {
            "date": "2022-10-12T20:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-12T22:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-12T23:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-13T00:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-13T01:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-13T18:00:00Z",
            "temp": 26
          },
          {
            "date": "2022-10-13T19:00:00Z",
            "temp": 27
          },
          {
            "date": "2022-10-13T20:00:00Z",
            "temp": 27
          },
          {
            "date": "2022-10-13T21:00:00Z",
            "temp": 28
          },
          {
            "date": "2022-10-13T22:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-13T23:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-14T00:00:00Z",
            "temp": 25
          },
          {
            "date": "2022-10-14T01:00:00Z",
            "temp": 26
          }
        ]
      }
    }
  },
  "success": true
}`

Here is an example of the output of `sudo blkid` on my server.

/dev/sdd1: LABEL="Movies" UUID="XXXXXXXXXXXXXXXX" TYPE="ext4" PARTLABEL="WD_BLACK" PARTUUID="XXXXXXXXXXXXXXXX"

Thanks!

**Comment by AnalogJ** [comment]
looks like the `device_label` and the `label` values are both empty. What operating system are you using? On Linux this `device_label` is retrieved using this code: https://github.com/AnalogJ/scrutiny/blob/3a970e7a27ddee754bf1ca02021c762533417d57/collector/pkg/detect/devices_linux.go#L90-L91

**Comment by jeremehancock** [comment]
I am on Ubuntu 20.04 Server. 

When I run `sudo blkid` on my server I get results like below. Is the LABEL listed there the one that should be showing?

/dev/sdd1: LABEL="Movies" UUID="XXXXXXXXXXXXXXXX" TYPE="ext4" PARTLABEL="WD_BLACK" PARTUUID="XXXXXXXXXXXXXXXX"

**Comment by AnalogJ** [comment]
Scrutiny doesnt use `blkid` to retrive label information.

Can you run a couple of commands for me:


```
$ cat /sys/class/block/sdd/dev
8:0

#take the value from the command above, prefix it with `b` and then add it to `/run/udev/data/`
$ cat /run/udev/data/b8:0

E:ID_TYPE=disk
E:ID_BUS=ata
E:ID_MODEL=Samsung_SSD_860_EVO_500GB
....
E:ID_PATH=pci-0000:00:17.0-ata-3.0
E:ID_PATH_TAG=pci-0000_00_17_0-ata-3_0
E:ID_PATH_ATA_COMPAT=pci-0000:00:17.0-ata-3
E:ID_PART_TABLE_UUID=16cfa833-6167-47b0-bc97-33aa9d22999c
E:ID_PART_TABLE_TYPE=gpt
E:ID_FS_TYPE=
G:systemd
Q:systemd
V:1
```


paste the output as a comment below (and look for a line containing `ID_FS_LABEL`)

**Comment by jeremehancock** [comment]
`S:disk/by-id/scsi-SHGST_HUH_721212ALE604_6F80062402202
S:disk/by-id/scsi-35000000000000001
S:disk/by-id/wwn-0x5000000000000001
S:disk/by-path/pci-0000:00:14.0-usb-0:4.1.3:1.0-scsi-0:0:0:0
W:11
I:10199584
E:SCSI_TPGS=0
E:SCSI_TYPE=disk
E:SCSI_VENDOR=HGST_HUH
E:SCSI_VENDOR_ENC=HGST\x20HUH
E:SCSI_MODEL=721212ALE604
E:SCSI_MODEL_ENC=721212ALE604\x20\x20\x20\x20
E:SCSI_REVISION=0
E:ID_SCSI=1
E:ID_SCSI_INQUIRY=1
E:ID_VENDOR=HGST_HUH
E:ID_VENDOR_ENC=HGST\x20HUH
E:ID_MODEL=721212ALE604
E:ID_MODEL_ENC=721212ALE604\x20\x20\x20\x20
E:ID_REVISION=0
E:ID_TYPE=disk
E:SCSI_IDENT_SERIAL=6F80062402202
E:SCSI_IDENT_LUN_NAA_REG=5000000000000001
E:ID_WWN=0x5000000000000001
E:ID_WWN_WITH_EXTENSION=0x5000000000000001
E:ID_BUS=scsi
E:ID_SERIAL=35000000000000001
E:ID_SERIAL_SHORT=5000000000000001
E:MPATH_SBIN_PATH=/sbin
E:ID_PATH=pci-0000:00:14.0-usb-0:4.1.3:1.0-scsi-0:0:0:0
E:ID_PATH_TAG=pci-0000_00_14_0-usb-0_4_1_3_1_0-scsi-0_0_0_0
E:ID_PART_TABLE_UUID=dc59c967-0a15-4f23-83cc-2f68ca9f5c2f
E:ID_PART_TABLE_TYPE=gpt
E:ID_FS_TYPE=
G:systemd`

**Comment by AnalogJ** [comment]
I don't see any label information there. I'm guessing you set the label on a partition, rather than creating a whole disk partition with a label.

**Comment by jeremehancock** [comment]
I followed the steps described here to label them. I generally don't label disks but once I started using Scrutiny I decided it would help identify them better.

https://linuxconfig.org/how-to-name-label-a-partition-or-volume-on-linux

**Comment by AnalogJ** [comment]
In general Scrutiny is unaware of partition/volume information, it only understands devices and raw disks. I'm guessing you have a partitioned disk, rather than [formatting the raw device with a filesystem](https://blog.thesparktree.com/disk-management#format) (following that guide will wipe your data, so I wouldn't do it now)

What happens if you try to add a label to a device (rather than a partition) using `e2label`?

```
sudo e2label /dev/sdd "Movies" 

# instead of `sudo e2label /dev/sdd1 "Movies"`
```

**Comment by jeremehancock** [comment]
I get this.

`Bad magic number in super-block while trying to open /dev/sdd
Found a gpt partition table in /dev/sdd`

**Comment by AnalogJ** [comment]
I'm going to close this for now, since I'm unaware of a way to read (OS agnostic) partition information via Go.
