### ISSUE TITLE
[BUG] influxdb not ready, scrutiny api not ready

### ISSUE THREAD

**Issue by milindpatel63** [AnalogJ/scrutiny#384]
**Describe the bug**
I am running scrutiny in docker in network host mode on non-standard ports. I noticed that the default run script for scrutiny assumes that influxdb is running on a static pre-defined port inside container. Same for scrutiny.

I am talking about these two files,
https://github.com/AnalogJ/scrutiny/blob/54b195f85104523ea830d07e21339568c9249a3b/rootfs/etc/services.d/collector-once/run
https://github.com/AnalogJ/scrutiny/blob/2a39421524b3ae2e32855e69f455ae730b9ed52b/rootfs/etc/services.d/scrutiny/run

It would be great if they picked up host and port values for influxdb and scrutiny from environment variable or config file.

**Expected behavior**
host and port values for influxdb and scrutiny are used from environment variable or config file.

**Comment by milindpatel63** [comment]
as a workaround for my use case, I have just created those two files with modified port values in my host system and mounted them to appropriate path inside the container for now.

**Comment by AnalogJ** [comment]
Honestly running Scrutiny in network host mode is a pretty non-standard/unsupported use-case. Is there a reason you need to run it that way?

**Comment by milindpatel63** [comment]
> Honestly running Scrutiny in network host mode is a pretty non-standard/unsupported use-case. Is there a reason you need to run it that way?

Docker network has a weird issue with UFW firewall of ubuntu where it bypasses the firewall by editing iptables directly. So I run all my containers in host network mode and manually manage ufw firewall rules and not let docker mess up my firewall.

**Comment by AnalogJ** [comment]
ah thanks for the explanation, I think I understand your use-case now. 
Unfortunately, I think your workaround is the best solution. 

I'm going to close this issue for now, but feel free to comment if you have any concerns/feedback.
