### ISSUE TITLE
[FEAT] NixOS formula please?

### ISSUE THREAD

**Issue by pshirshov** [AnalogJ/scrutiny#399]
Could you create a formula for [NixOS](https://nixos.org/) please?

**Comment by AnalogJ** [comment]
If you'd be willing to contribute it, I'd be happy to review it, but unfortunately I don't use Nix/NixOS, so its difficult for me to debug/develop for that platform/toolchain.

**Comment by c0h2r** [comment]
This one can be closed, I believe: scrutiny's [now in nixpkgs](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=services.scrutiny), thanks to @jnsgruk

**Comment by jnsgruk** [comment]
That's correct! I wrote about the [initial implementation](https://jnsgr.uk/2024/02/packaging-scrutiny-for-nixos/) and the [contribution process](https://jnsgr.uk/2024/02/contributing-scrutiny-to-nixpkgs/) on my blog! Let me know if you have any issues!
