### ISSUE TITLE
NVMe drives not correctly detected by Scrutiny

### ISSUE THREAD

**Issue by Roxedus** [AnalogJ/scrutiny#4]
Output of
```bash
root@c43726ce532e:/scrutiny# smartctl -j -x /dev/nvme0
```

```json
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-4.19.107-Unraid",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-j",
      "-x",
      "/dev/nvme0"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/nvme0",
    "info_name": "/dev/nvme0",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "Force MP510",
  "serial_number": "yes",
  "firmware_version": "ECFM12.3",
  "nvme_pci_vendor": {
    "id": 6535,
    "subsystem_id": 6535
  },
  "nvme_ieee_oui_identifier": 6584743,
  "nvme_total_capacity": 480103981056,
  "nvme_unallocated_capacity": 0,
  "nvme_controller_id": 1,
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 937703088,
        "bytes": 480103981056
      },
      "capacity": {
        "blocks": 937703088,
        "bytes": 480103981056
      },
      "utilization": {
        "blocks": 937703088,
        "bytes": 480103981056
      },
      "formatted_lba_size": 512,
      "eui64": {
        "oui": 6584743,
        "ext_id": 171819811633
      }
    }
  ],
  "user_capacity": {
    "blocks": 937703088,
    "bytes": 480103981056
  },
  "logical_block_size": 512,
  "local_time": {
    "time_t": 1600380529,
    "asctime": "Thu Sep 17 22:08:49 2020 Europe"
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 38,
    "available_spare": 100,
    "available_spare_threshold": 5,
    "percentage_used": 1,
    "data_units_read": 6734413,
    "data_units_written": 15749028,
    "host_reads": 29048027,
    "host_writes": 17155968,
    "controller_busy_time": 298,
    "power_cycles": 4,
    "power_on_hours": 6420,
    "unsafe_shutdowns": 4,
    "media_errors": 0,
    "num_err_log_entries": 8382,
    "warning_temp_time": 0,
    "critical_comp_time": 0
  },
  "temperature": {
    "current": 38
  },
  "power_cycle_count": 4,
  "power_on_time": {
    "hours": 6420
  }
}
```

**Comment by FoRTu** [comment]
Hi,

I have the same problem, the nvme device is not detected when I run **"scrutiny-collector-metrics run"**. But if I run **"smartctl -j -x /dev/nvme0"** I get this:

```json
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-4.19.107-Unraid",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-j",
      "-x",
      "/dev/nvme0"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/nvme0",
    "info_name": "/dev/nvme0",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "PM981a NVMe Samsung 256GB",
  "serial_number": "S4GVNFXXXXXXXX",
  "firmware_version": "15302029",
  "nvme_pci_vendor": {
    "id": 5197,
    "subsystem_id": 5197
  },
  "nvme_ieee_oui_identifier": 9528,
  "nvme_total_capacity": 256060514304,
  "nvme_unallocated_capacity": 0,
  "nvme_controller_id": 4,
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 500118192,
        "bytes": 256060514304
      },
      "capacity": {
        "blocks": 500118192,
        "bytes": 256060514304
      },
      "utilization": {
        "blocks": 185681392,
        "bytes": 95068872704
      },
      "formatted_lba_size": 512
    }
  ],
  "user_capacity": {
    "blocks": 500118192,
    "bytes": 256060514304
  },
  "logical_block_size": 512,
  "local_time": {
    "time_t": 1600408469,
    "asctime": "Fri Sep 18 05:54:29 2020 Europe"
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 47,
    "available_spare": 100,
    "available_spare_threshold": 50,
    "percentage_used": 1,
    "data_units_read": 3223590,
    "data_units_written": 16852620,
    "host_reads": 24329333,
    "host_writes": 84120028,
    "controller_busy_time": 377,
    "power_cycles": 56,
    "power_on_hours": 472,
    "unsafe_shutdowns": 25,
    "media_errors": 0,
    "num_err_log_entries": 65,
    "warning_temp_time": 0,
    "critical_comp_time": 0,
    "temperature_sensors": [
      47,
      46
    ]
  },
  "temperature": {
    "current": 47
  },
  "power_cycle_count": 56,
  "power_on_time": {
    "hours": 472
  }
}
```

Why is not added to _secrutiny_ in the same way of the other HDD devices?

**Comment by mrhotio** [comment]
Not getting anything either for nvme drives

```
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      1
    ],
    "svn_revision": "5022",
    "platform_info": "x86_64-linux-5.4.0-47-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-j",
      "-x",
      "/dev/nvme0"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/nvme0",
    "info_name": "/dev/nvme0",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "THNSN5512GPU7 TOSHIBA",
  "serial_number": "jdsklfjdsfjkdsfjksjfsjfsjfk",
  "firmware_version": "57GA4103",
  "nvme_pci_vendor": {
    "id": 4473,
    "subsystem_id": 4473
  },
  "nvme_ieee_oui_identifier": 2061,
  "nvme_controller_id": 0,
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 1000215216,
        "bytes": 512110190592
      },
      "capacity": {
        "blocks": 1000215216,
        "bytes": 512110190592
      },
      "utilization": {
        "blocks": 1000215216,
        "bytes": 512110190592
      },
      "formatted_lba_size": 512,
      "eui64": {
        "oui": 2061,
        "ext_id": 8591634072
      }
    }
  ],
  "user_capacity": {
    "blocks": 1000215216,
    "bytes": 512110190592
  },
  "logical_block_size": 512,
  "local_time": {
    "time_t": 1600426731,
    "asctime": "Fri Sep 18 12:58:51 2020 CEST"
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 42,
    "available_spare": 100,
    "available_spare_threshold": 10,
    "percentage_used": 32,
    "data_units_read": 335873808,
    "data_units_written": 211840944,
    "host_reads": 9650743886,
    "host_writes": 1872960732,
    "controller_busy_time": 44456,
    "power_cycles": 24,
    "power_on_hours": 26359,
    "unsafe_shutdowns": 13,
    "media_errors": 0,
    "num_err_log_entries": 0,
    "warning_temp_time": 0,
    "critical_comp_time": 0,
    "temperature_sensors": [
      42
    ]
  },
  "temperature": {
    "current": 42
  },
  "power_cycle_count": 24,
  "power_on_time": {
    "hours": 26359
  }
}
```

**Comment by AnalogJ** [comment]
This should be fixed with the following commit: https://github.com/AnalogJ/scrutiny/commit/a7cd91231887090a046d13dfc4e20abf05a34d7c

Its old code from before I supported NVMe storage controllers & drives. Unfortunately I don't have an NVMe drive myself, so can one of you verify that the latest docker image fixed your issue? You'll have to wait until the images finish building on Docker Hub: [(a7cd9123)](https://hub.docker.com/repository/docker/analogj/scrutiny/builds)

**Comment by Roxedus** [comment]
Seems to have fixed it for me 😄

**Comment by FoRTu** [comment]
For me too 👍 

Thanks!

**Comment by AnalogJ** [comment]
Hey @Roxedus  @FoRTu 

I'm testing out a completely new (& hopefully more robust) device detection method, and I wanted to make sure that your NVMe drives are correctly detected. The code lives in the `smartctl_scan` branch, and I've created a Docker image for it. 

Can you try running the following command, and tell me if everything looks correct?

```
docker run --rm -p 8080:8080 \
-v /dev/disk:/dev/disk \
-v /run/udev:/run/udev:ro \
--name scrutiny \
--privileged analogj/scrutiny:smartctl_scan
```

You'll need to exec into the container and start the collector manually too:

`docker exec scrutiny scrutiny-collector-metrics run`

**Comment by Roxedus** [comment]
It does detect it, but it doesn't show any data
![image](https://user-images.githubusercontent.com/7110194/93690878-0ca44f80-fade-11ea-9463-4432bd007549.png)

**Comment by AnalogJ** [comment]
can you run the following commands and paste the output from each command below?

- `docker exec scrutiny smartctl --scan -j`
- `docker exec scrutiny smartctl -x -j -d nvme /dev/nvme0`
- `docker exec scrutiny smartctl -x -j /dev/nvme0`

Thanks!

**Comment by Roxedus** [comment]
`smartctl --scan -j`
```json
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-4.19.107-Unraid",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-j",
      "--scan"
    ],
    "exit_status": 0
  },
  "devices": [
    {
      "name": "/dev/sdb",
      "info_name": "/dev/sdb",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdc",
      "info_name": "/dev/sdc",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdd",
      "info_name": "/dev/sdd",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sde",
      "info_name": "/dev/sde",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdf",
      "info_name": "/dev/sdf",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdg",
      "info_name": "/dev/sdg",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdh",
      "info_name": "/dev/sdh",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdi",
      "info_name": "/dev/sdi",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdj",
      "info_name": "/dev/sdj",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdk",
      "info_name": "/dev/sdk",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/sdl",
      "info_name": "/dev/sdl",
      "type": "scsi",
      "protocol": "SCSI"
    },
    {
      "name": "/dev/nvme0",
      "info_name": "/dev/nvme0",
      "type": "nvme",
      "protocol": "NVMe"
    }
  ]
}
```
------

`smartctl -x -j -d nvme /dev/nvme0`
```json
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-4.19.107-Unraid",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-x",
      "-j",
      "-d",
      "nvme",
      "/dev/nvme0"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/nvme0",
    "info_name": "/dev/nvme0",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "Force MP510",
  "serial_number": "yes",
  "firmware_version": "ECFM12.3",
  "nvme_pci_vendor": {
    "id": 6535,
    "subsystem_id": 6535
  },
  "nvme_ieee_oui_identifier": 6584743,
  "nvme_total_capacity": 480103981056,
  "nvme_unallocated_capacity": 0,
  "nvme_controller_id": 1,
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 937703088,
        "bytes": 480103981056
      },
      "capacity": {
        "blocks": 937703088,
        "bytes": 480103981056
      },
      "utilization": {
        "blocks": 937703088,
        "bytes": 480103981056
      },
      "formatted_lba_size": 512,
      "eui64": {
        "oui": 6584743,
        "ext_id": 171819811633
      }
    }
  ],
  "user_capacity": {
    "blocks": 937703088,
    "bytes": 480103981056
  },
  "logical_block_size": 512,
  "local_time": {
    "time_t": 1600559445,
    "asctime": "Sat Sep 19 23:50:45 2020 Europe"
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 38,
    "available_spare": 100,
    "available_spare_threshold": 5,
    "percentage_used": 1,
    "data_units_read": 6932118,
    "data_units_written": 16093122,
    "host_reads": 29878701,
    "host_writes": 17533252,
    "controller_busy_time": 305,
    "power_cycles": 4,
    "power_on_hours": 6470,
    "unsafe_shutdowns": 4,
    "media_errors": 0,
    "num_err_log_entries": 8382,
    "warning_temp_time": 0,
    "critical_comp_time": 0
  },
  "temperature": {
    "current": 38
  },
  "power_cycle_count": 4,
  "power_on_time": {
    "hours": 6470
  }
}
```
-----

`smartctl -x -j /dev/nvme0`
```json
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-4.19.107-Unraid",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-x",
      "-j",
      "/dev/nvme0"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/nvme0",
    "info_name": "/dev/nvme0",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "Force MP510",
  "serial_number": "yes",
  "firmware_version": "ECFM12.3",
  "nvme_pci_vendor": {
    "id": 6535,
    "subsystem_id": 6535
  },
  "nvme_ieee_oui_identifier": 6584743,
  "nvme_total_capacity": 480103981056,
  "nvme_unallocated_capacity": 0,
  "nvme_controller_id": 1,
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 937703088,
        "bytes": 480103981056
      },
      "capacity": {
        "blocks": 937703088,
        "bytes": 480103981056
      },
      "utilization": {
        "blocks": 937703088,
        "bytes": 480103981056
      },
      "formatted_lba_size": 512,
      "eui64": {
        "oui": 6584743,
        "ext_id": 171819811633
      }
    }
  ],
  "user_capacity": {
    "blocks": 937703088,
    "bytes": 480103981056
  },
  "logical_block_size": 512,
  "local_time": {
    "time_t": 1600559542,
    "asctime": "Sat Sep 19 23:52:22 2020 Europe"
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 38,
    "available_spare": 100,
    "available_spare_threshold": 5,
    "percentage_used": 1,
    "data_units_read": 6932118,
    "data_units_written": 16093122,
    "host_reads": 29878701,
    "host_writes": 17533252,
    "controller_busy_time": 305,
    "power_cycles": 4,
    "power_on_hours": 6470,
    "unsafe_shutdowns": 4,
    "media_errors": 0,
    "num_err_log_entries": 8382,
    "warning_temp_time": 0,
    "critical_comp_time": 0
  },
  "temperature": {
    "current": 38
  },
  "power_cycle_count": 4,
  "power_on_time": {
    "hours": 6470
  }
}
```

**Comment by AnalogJ** [comment]
weird. Those entries look fine.

Ok, so I added some extra logging to this branch, and the ability to generate a log file. 
Can you pull the latest image and run the collector with `--debug` & `--log-file=`? After that you'll need to attach the file here. 

```
docker pull analogj/scrutiny:smartctl_scan

docker run --rm -p 8080:8080 \
-v /dev/disk:/dev/disk \
-v /run/udev:/run/udev:ro \
--name scrutiny \
--privileged analogj/scrutiny:smartctl_scan

docker exec scrutiny scrutiny-collector-metrics run --debug --log-file /tmp/test.log

# we can use docker cp to copy the log file out of the container. 
docker cp scrutiny:/tmp/test.log test.log
```

Thanks for helping me with all this

**Comment by Roxedus** [comment]
DMd 😄

**Comment by AnalogJ** [comment]
Hey @Roxedus 
I took a look at your log file. All your Smartctl json data looks correct, so the only way you'd be left in this state is if the API did not accept the data from the collector for some reason. I added a new minimal anonymized test with your NVMe drive data, and everything is working, which means the API can correctly de-serialize your JSON data..

So now I'm wondering if it's a transient error. Can you rerun the collector and check if its consistently failing the data upload for your NVMe drive?  

In the meantime, I'm going to add some better logging & a log file option to the webapp so we can get dumps from there as well.

**Comment by Roxedus** [comment]
Thanks for making me do a sanity check, using the same image on my laptop, which has the same model NVME, works.

**Comment by AnalogJ** [comment]
You have no idea how happy I am to hear that 😆 
I'm wondering if the concurrent nature of scrutiny processing and the fact that I use sqlite under the hood is causing some issues. 

I'll add some offsets to the `smartctl` runs, so hopefully that'll help.

Thanks for checking on that for me!

**Comment by Roxedus** [comment]
It did work on master at the time, it now doesnt

**Comment by AnalogJ** [comment]
Ok. I've removed all collector concurrency from the `master` branch, which is something that has been causing intermittent failures. Can you verify that it fixed your issue?

```
docker pull analogj/scrutiny
docker run --rm -p 8080:8080 \
-v /dev/disk:/dev/disk \
-v /run/udev:/run/udev:ro \
--name scrutiny \
--privileged analogj/scrutiny
```

**Comment by Roxedus** [comment]
I would not call this fixed. 
![image](https://user-images.githubusercontent.com/7110194/93786302-708a5d80-fc2f-11ea-8ea3-5e56689e71d0.png)

**Comment by mrhotio** [comment]
Are there any plans on fixing this bug?

**Comment by Roxedus** [comment]
Currently back to not registering SMART for NVMEs

**Comment by AnalogJ** [comment]
Hey,
Sorry, it took me a while to get debug logging to a file implemented in the API. 

Can you two run the following commands and attach the log files here?

```
docker pull analogj/scrutiny

docker run -it --rm -p 8080:8080 \
-v /run/udev:/run/udev:ro \
-v /dev/disk:/dev/disk \
-e DEBUG=true \
-e COLLECTOR_LOG_FILE=/tmp/collector.log \
-e SCRUTINY_LOG_FILE=/tmp/web.log \
--name scrutiny \
--privileged analogj/scrutiny

# in another terminal trigger the collector
docker exec scrutiny scrutiny-collector-metrics run

# then use docker cp to copy the log files out of the container.
docker cp scrutiny:/tmp/collector.log collector.log
docker cp scrutiny:/tmp/web.log web.log
```

**Comment by mrhotio** [comment]
[web.log](https://github.com/AnalogJ/scrutiny/files/5262221/web.log)
[collector.log](https://github.com/AnalogJ/scrutiny/files/5262223/collector.log)

**Comment by AnalogJ** [comment]
Hey @hotio can you get the latest scrutiny container and generate the logs again? I was missing some log statements in the version of the image you used.

**Comment by mrhotio** [comment]
[collector.log](https://github.com/AnalogJ/scrutiny/files/5266097/collector.log)
[web.log](https://github.com/AnalogJ/scrutiny/files/5266098/web.log)

**Comment by AnalogJ** [comment]
Everything looks fine with those logs. Smartctl is correctly passing the nvme data to the collector, which is passing it to the API.
Can you confirm that the NVMe data is still missing from the dashboard?

If so, can you send me the logs after running the collector and loading up the dashboard (and the details page)?

**Comment by mrhotio** [comment]
still missing, will do, back in a minute

**Comment by mrhotio** [comment]
![image](https://user-images.githubusercontent.com/26902309/93988159-b0b12380-fd88-11ea-8bd8-4790636a532b.png)

![image](https://user-images.githubusercontent.com/26902309/93988073-98d99f80-fd88-11ea-93d4-00cb04b7f3a0.png)
[collector.log](https://github.com/AnalogJ/scrutiny/files/5266740/collector.log)
[web.log](https://github.com/AnalogJ/scrutiny/files/5266741/web.log)

**Comment by AnalogJ** [comment]
@hotio This is bizarre. I just copied the request/responses from the API server logs you provided, and built an integration test based on it. The device & smartctl data was correctly parsed and stored in the DB. Finally I did a comparison between the output from the dashboard page API & your logged response. They were significantly different, my test response had all the drive details (smart result, temperature, capacity & powered on values) that yours is missing. 


**At this point, the only difference between the processing on my side and yours is the serial number.** 
- Can you tell me if there's any spaces or special characters in your serial number? 
- Would you be willing to email me one of your serial numbers (jason@thesparktree.com) or include a lightly modified version of it as a comment (replace a couple of alpha-numberic values with other alpha-numeric values, in the same case, leaving the majority of the string alone)

Thanks!

**Comment by mrhotio** [comment]
`W5IS108NTXHV`

**Comment by AnalogJ** [comment]
oh god. I think I found the issue. Basically NVME drives don't have wwn values (which is used to generate a hexadecimal string), so I fall back to using the serial number as the identifier for the drive. The problem is that when I push data to the API, I lowercase the identifier, and then use this lower cased identifier to do a DB lookup -> no results. 

Ugh. 
I've committed a fix, and its going through the Docker hub build pipe now. (8a336bf5)

https://hub.docker.com/repository/docker/analogj/scrutiny/builds

Thanks for all the help tracking this down!

**Comment by mrhotio** [comment]
🤦‍♂️ it's always something stupid like that 😄

**Comment by mrhotio** [comment]
it doesn't seem to wanna compile

**Comment by AnalogJ** [comment]
Had to make a small fix for linux. It just finished successfully.

**Comment by mrhotio** [comment]
![image](https://user-images.githubusercontent.com/26902309/94052395-2d6bee00-fdd9-11ea-8843-4f566a090292.png)

**Comment by Roxedus** [comment]
👍

**Comment by AnalogJ** [comment]
This is great, thanks for confirming!

**Comment by parkerlreed** [comment]
Are these changes in the current docker image? Completely not working for me.

**Comment by parkerlreed** [comment]
Ok you might want to add the collector to the readme. I didn't know it had to be run manually and the web page doesn't tell you the docker specific way to run it.

```
docker exec scrutiny scrutiny-collector-metrics run
```

**Comment by shamoon** [comment]
Im having same issue not fixed by current release at least for me.

`sudo docker exec scrutiny smartctl -j -x /dev/nvme0n1` gives:
```
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-5.4.0-47-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-j",
      "-x",
      "/dev/nvme0n1"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/nvme0n1",
    "info_name": "/dev/nvme0n1",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "Samsung SSD 970 EVO 500GB",
  "serial_number": "S466NX0M776250H",
  "firmware_version": "2B2QEXE7",
  "nvme_pci_vendor": {
    "id": 5197,
    "subsystem_id": 5197
  },
  "nvme_ieee_oui_identifier": 9528,
  "nvme_total_capacity": 500107862016,
  "nvme_unallocated_capacity": 0,
  "nvme_controller_id": 4,
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 976773168,
        "bytes": 500107862016
      },
      "capacity": {
        "blocks": 976773168,
        "bytes": 500107862016
      },
      "utilization": {
        "blocks": 104717696,
        "bytes": 53615460352
      },
      "formatted_lba_size": 512,
      "eui64": {
        "oui": 9528,
        "ext_id": 376106710327
      }
    }
  ],
  "user_capacity": {
    "blocks": 976773168,
    "bytes": 500107862016
  },
  "logical_block_size": 512,
  "local_time": {
    "time_t": 1601337222,
    "asctime": "Mon Sep 28 23:53:42 2020 UTC"
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 37,
    "available_spare": 100,
    "available_spare_threshold": 10,
    "percentage_used": 0,
    "data_units_read": 5329638,
    "data_units_written": 5146071,
    "host_reads": 19209989,
    "host_writes": 81665521,
    "controller_busy_time": 390,
    "power_cycles": 16,
    "power_on_hours": 756,
    "unsafe_shutdowns": 5,
    "media_errors": 0,
    "num_err_log_entries": 36,
    "warning_temp_time": 0,
    "critical_comp_time": 0,
    "temperature_sensors": [
      37,
      39
    ]
  },
  "temperature": {
    "current": 37
  },
  "power_cycle_count": 16,
  "power_on_time": {
    "hours": 756
  }
}
```

But that drive doesnt show in dashboard. My docker-compose is:
```
...
    volumes:
      - /run/udev:/run/udev:ro
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda
      - /dev/nvme0n1
...
```

Thanks for your work on this, sorry if I'm missing something obvious.

**Comment by shamoon** [comment]
Im having same issue not fixed by current release at least for me.

`sudo docker exec scrutiny smartctl -j -x /dev/nvme0n1` gives:
```
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-5.4.0-47-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-j",
      "-x",
      "/dev/nvme0n1"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/nvme0n1",
    "info_name": "/dev/nvme0n1",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "Samsung SSD 970 EVO 500GB",
  "serial_number": "Sxxxx",
  "firmware_version": "2B2QEXE7",
  "nvme_pci_vendor": {
    "id": 5197,
    "subsystem_id": 5197
  },
  "nvme_ieee_oui_identifier": 9528,
  "nvme_total_capacity": 500107862016,
  "nvme_unallocated_capacity": 0,
  "nvme_controller_id": 4,
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 976773168,
        "bytes": 500107862016
      },
      "capacity": {
        "blocks": 976773168,
        "bytes": 500107862016
      },
      "utilization": {
        "blocks": 104717696,
        "bytes": 53615460352
      },
      "formatted_lba_size": 512,
      "eui64": {
        "oui": 9528,
        "ext_id": 376106710327
      }
    }
  ],
  "user_capacity": {
    "blocks": 976773168,
    "bytes": 500107862016
  },
  "logical_block_size": 512,
  "local_time": {
    "time_t": 1601337222,
    "asctime": "Mon Sep 28 23:53:42 2020 UTC"
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 37,
    "available_spare": 100,
    "available_spare_threshold": 10,
    "percentage_used": 0,
    "data_units_read": 5329638,
    "data_units_written": 5146071,
    "host_reads": 19209989,
    "host_writes": 81665521,
    "controller_busy_time": 390,
    "power_cycles": 16,
    "power_on_hours": 756,
    "unsafe_shutdowns": 5,
    "media_errors": 0,
    "num_err_log_entries": 36,
    "warning_temp_time": 0,
    "critical_comp_time": 0,
    "temperature_sensors": [
      37,
      39
    ]
  },
  "temperature": {
    "current": 37
  },
  "power_cycle_count": 16,
  "power_on_time": {
    "hours": 756
  }
}
```

But that drive doesnt show in dashboard. My docker-compose is:
```
...
    volumes:
      - /run/udev:/run/udev:ro
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda
      - /dev/nvme0n1
...
```

Thanks for your work on this, sorry if I'm missing something obvious.

**Comment by AnalogJ** [comment]
@shamoon are you using my image or the LSIO image? I think their image may be a bit out of date. 

If you are using my image, can you run the following commands to generate some log files for me?

Make sure you add your devices using `--device` and add the `--cap-add SYS_ADMIN` flag. 
```
docker run -it --rm -p 8080:8080 \
-v /run/udev:/run/udev:ro \
--cap-add SYS_RAWIO \
--device=/dev/sda \
--device=/dev/sdb \
-e DEBUG=true \
-e COLLECTOR_LOG_FILE=/tmp/collector.log \
-e SCRUTINY_LOG_FILE=/tmp/web.log \
--name scrutiny \
analogj/scrutiny

# in another terminal trigger the collector
docker exec scrutiny scrutiny-collector-metrics run

# then use docker cp to copy the log files out of the container.
docker cp scrutiny:/tmp/collector.log collector.log
docker cp scrutiny:/tmp/web.log web.log
```

Once you've copied over the log files from the Docker image, you'll need to attach them below.

**Comment by shamoon** [comment]
Logs attached. Thanks so much!
[collector.log](https://github.com/AnalogJ/scrutiny/files/5295961/collector.log)
[web.log](https://github.com/AnalogJ/scrutiny/files/5295962/web.log)

Edit: Oh, and sorry, your image.
`image: analogj/scrutiny:latest`

**Comment by AnalogJ** [comment]
@shamoon can you check if you have a `/dev/nvme0` device?

**Comment by shamoon** [comment]
For `/dev/nvme0n1`, see my [output above](https://github.com/AnalogJ/scrutiny/issues/4#issuecomment-700343755), when I use `nvme0` I just get `Smartctl open device: /dev/nvme0 failed: No such device`

**Comment by zackelan** [comment]
Running into this as well, but I was able to work around it by passing `--privileged` to the docker run command.

Here's debug logs from running both with and without `--privileged`, if they help. In particular, when running unprivileged, the collector log has a `"Read NVMe Identify Controller failed: NVME_IOCTL_ADMIN_CMD: Permission denied"` error. 

[privileged-collector.log](https://github.com/AnalogJ/scrutiny/files/5296582/privileged-collector.log)
[privileged-web.log](https://github.com/AnalogJ/scrutiny/files/5296583/privileged-web.log)
[unprivileged-collector.log](https://github.com/AnalogJ/scrutiny/files/5296584/unprivileged-collector.log)
[unprivileged-web.log](https://github.com/AnalogJ/scrutiny/files/5296585/unprivileged-web.log)

**Comment by shamoon** [comment]
Cheers @zackelan that solves it for me! Odd my logs didn't have that same error message. I know there are concerns about `--privileged` but not sure if theres a way around it for now...

**Comment by lordraiden** [comment]
This drive the power cycle count is wrong, can't be 33
![imagen](https://user-images.githubusercontent.com/17175395/94619095-8f7e9480-02ac-11eb-8566-4db93326bd8f.png)

In addition I don't get any info for this Nvme
![imagen](https://user-images.githubusercontent.com/17175395/94619138-a1f8ce00-02ac-11eb-8e43-38f8354057cd.png)

**Comment by AnalogJ** [comment]
I'm going to close this issue since it seems like we were able to get NVMe drives detected. 

Hey @lordraiden That looks like a different issue. Can you create a new bug report (with logs) for it?

**Comment by npodbielski** [comment]
> Cheers @zackelan that solves it for me! Odd my logs didn't have that same error message. I know there are concerns about `--privileged` but not sure if theres a way around it for now...

Still no solution to this? I would rather not allow container to the whole system as root just to view some drive metrics.

In docs there is mention about: CAP_ADMIN to make this work but it does not without `--privileged`

**Comment by AnalogJ** [comment]
@npodbielski Unfortunately this is out of my control. Scrutiny uses Smartctl under the hood, and smartctl requires capabilities equivalent to `--privileged` -- when running in a container. 

If you're really worried, you can run the scrutiny webapp and influxdb in docker, and the collector outside (as a locked-down non-root user).

**Comment by npodbielski** [comment]
Maybe not worried but kind of uneasy. I wanted this tool as a way to monitor my disks on machine I am using for my various self hosted services. As such there are bunch of private, important stuff for me. 
Running software that is security issue by definition is not a good idea. But at the same time OSS and whole IT is security issue in the same way. I am unable to check every piece of software I am running and I just trust some things more than the others. 
Running software in the container is some kind of isolation. Running  it as privileged user is for your system breaks isolation but still there is some trust. 
But this can be broken by malicious code injected into the container without your knowledge. Container that needs to be run as privileged in order to do its job would be prime target for attackers. 
So I kind of thing that probably it will be fine but you never know... You know. So for now I do not use it. Which is a shame. 

Anyway thank you for your workaround. I will check it out.
