### ISSUE TITLE
Support for USB NVME external adapters using JMicron

### ISSUE THREAD

**Issue by hubikj** [AnalogJ/scrutiny#402]
**Is your feature request related to a problem? Please describe.**
Scrutiny does not detect any discs for me and I am using a USB NVME external adapter with JMicron chip. [In another project I found somebody suggesting a special parameter](https://github.com/Draggon/hassio-hdd-tools/issues/50) for the kind of USB NVME adapter that I have. And as suggested `smartctl --all -d sntjmicron /dev/sda` works for me.

**Describe the solution you'd like**
Would it be possible to support my adapter using this information? Thanks!

**Comment by AnalogJ** [comment]
Hey @hubikj 
Yes USB devices are supported! If you have a working `smartctl` command, you can pass those flags to Scrutiny & smartctl using a custom [collector.yml](https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml#L57-L61)

Please see https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#usb-devices for more information about USB devices.

I'm going to close this issue for now, but feel free to comment/reopen if you're still having issues.
