### ISSUE TITLE
[FEAT] Notification Configuration & Testing in GUI

### ISSUE THREAD

**Issue by boomam** [AnalogJ/scrutiny#405]
**Is your feature request related to a problem? Please describe.**
Not directly, however an inability to easily test a notification config means that we wont be able to check if our alerting works until its too late, potentially.

**Describe the solution you'd like**

- Ability to configure notifications in GUI.
- Ability to set 'what' is notified + thresholds.
- Ability to test notifications work.

**Additional context**

**Comment by AnalogJ** [comment]
You can test notifications by `curl`ing the following url:

```
curl -X POST http://localhost:8080/api/health/notify
```

However, you are correct, a UI mechanism would make this easier for some users.

**Comment by boomam** [comment]
Could it be worth listing the above curl command in the readme/docs until said feature is ready?  
Would probably help as a 'workaround' in the interim?

**Comment by AnalogJ** [comment]
It's already in the readme

**Comment by boomam** [comment]
So it is...I'll add it to the troubleshooting page for notifications though, as its relevant to that too.  
I'll submit a PR shortly.

**Comment by boomam** [comment]
https://github.com/AnalogJ/scrutiny/pull/406
