### ISSUE TITLE
[BUG] No error printed when failing to parse scrutiny.yaml

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [AnalogJ/scrutiny#408]
**Describe the bug**
I decided to re-install Scrutiny to monitor my PCs and copied an older configuration from a previous install.  This configuration had an invalid configuration parameter in it.  When trying to start the container, it simply printed the following message repetitively:

`Loading configuration file: /opt/scrutiny/config/scrutiny.yaml`

without the software actually running.  It took quite some time to debug the issue as I didn't know where to look for what was wrong.

**Expected behavior**
If Scrutiny is unable to parse a configuration file, it should print an error so that the config can be corrected.

**Config issue**
The issue was from using what must be a deprecated option in `notify` called `level`.  I see that it is no longer shown in the sample config.  Removing this setting resolved my issue.

```
notify:
  level: 'warn' # 'warn' or 'error'
  urls:
    - "smtp://<details>"
```

**Comment by AnalogJ** [comment]
Hm, thats odd.
Scrutiny should print an error message if the config file is invalid. I explicitly check for deprecated options like `notify.level`

https://github.com/AnalogJ/scrutiny/blob/master/webapp/backend/pkg/config/config.go#L131-L133

Any chance you can copy-paste some of your error logs?

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
The Docker console shows:

```
2022/11/30 05:22:31 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
2022/11/30 05:22:31 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
2022/11/30 05:22:32 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
2022/11/30 05:22:32 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
2022/11/30 05:22:33 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
2022/11/30 05:22:35 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
2022/11/30 05:22:39 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
2022/11/30 05:22:45 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
2022/11/30 05:22:59 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
```

Unfortunately the debug log file is not created when the error is present.  For clarity, the config for the log is as follows:

```
log:
  file: '/opt/scrutiny/config/debug.log' #absolute or relative paths allowed, eg. web.log
  level: DEBUG
```

**Comment by AnalogJ** [comment]
sorry about that, looks like I forgot to print an error message when the config file validation fails. Fixed in master.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Fantastic!  Thanks so much!

**Comment by Enissay** [comment]
@AnalogJ I stumpled on this post and blindly copied both configs for notif & log both with their level... Sadly the error is not explicit about which to remove... It took me a while to trace my path here and fix it xD
```
12/11/2022 6:11:48 AM
2022/12/11 06:11:48 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
12/11/2022 6:11:48 AM
2022/12/11 06:11:48 CONFIG ERROR: ConfigValidationError: "`notify.level` configuration option is deprecated. Replaced by option in Dashboard Settings page"
```

Also the https://github.com/AnalogJ/scrutiny/blob/master/example.scrutiny.yaml must be updated accordingly :-)

**Comment by AnalogJ** [comment]
@Enissay not sure what you mean 

```
CONFIG ERROR: ConfigValidationError: "`notify.level` configuration option is deprecated
```
Seems pretty explicit to me, but I'm happy to re-word the error message if there's something I can change to make it clearer. 

Also, I dont see any references to `notify.level` in the config file, they should be completely removed.

**Comment by Enissay** [comment]
@AnalogJ you are absolutely right. Working up to 5am is a bad idea. Please forgive my spam!
