### ISSUE TITLE
[BUG] device override with type: sat,auto not working

### ISSUE THREAD

**Issue by gerohaug** [AnalogJ/scrutiny#418]
**Describe the bug**
Overriding device type with a list in collector.yaml leads to commands being run for each list parameter.

device override in collector.yaml:
```
devices:
  - device: /dev/sdc
    type: sat,auto
```
resulting smartctl commands from logfile:
```
time="2023-01-02T09:48:17Z" level=info msg="Executing command: smartctl --info --json --device sat /dev/sdc" type=metrics
time="2023-01-02T09:48:17Z" level=error msg="Could not retrieve device information for sdc: exit status 2" type=metrics
time="2023-01-02T09:48:17Z" level=info msg="Executing command: smartctl --info --json --device auto /dev/sdc" type=metrics
time="2023-01-02T09:48:17Z" level=error msg="Could not retrieve device information for sdc: exit status 2" type=metrics
```
Using ghcr.io/analogj/scrutiny:master-omnibus (dev-0.5.0) with docker 20.10.12 on Ubuntu 20.04.5 LTS

**Expected behavior**
Setting device type override for a disk to 'sat,auto' should run smartctl commands with --device sat,auto

**Comment by AnalogJ** [comment]
weird. It's almost like its treating the string like a list. Scrutiny does support that mode for RAID devices, but it shouldn't apply here. Let me see if I can replicate this.

**Comment by AnalogJ** [comment]
Hey @gerohaug 
I was able to replicate your issue locally, and its related to the config file parsing library that I'm using -- meaning this is going to be difficult to fix.

However, there is a workaround that you can use (I've confirmed it works):

```
devices:
  - device: /dev/sdc
    type: ['sat,auto']
```

I'll close this issue for now, but feel free to comment/reopen if this is still an issue.
