### ISSUE TITLE
[BUG] Teams notifications return w/code 500 Internal Server Error

### ISSUE THREAD

**Issue by neo21670** [AnalogJ/scrutiny#420]
**Describe the bug**
Scrutiny running in omnibus mode and with Teams webhook configured, notification testing fails during test run (i.e. `curl -X POST http://localhost:8080/api/health/notify`)

**Expected behavior**
Notification tests run successfully.

**Log Files**
[web.log](https://github.com/AnalogJ/scrutiny/files/10345955/web.log)

```
root@ngpve1:/opt/scrutiny/config# docker run --rm -ti containrrr/shoutrrr send -m specific\ test\ message -u teams://[[REMOVED_WEBHOOK_URL]]
Notification sent
```
![Screenshot 2023-01-04 at 17 53 07](https://user-images.githubusercontent.com/205882/210607690-a4a8cd20-de24-43e2-a302-5b0c67da7277.png)

**Comment by AnalogJ** [comment]
Hey @neo21670 
I just released v0.6.0 which includes a change to the Shoutrrr library that Scrutiny uses for notifications. That should fix your Teams notification issue. 

Can you try it out and comment if it worked for you?
