### ISSUE TITLE
[BUG] Release 0.6.0 missing frontend file

### ISSUE THREAD

**Issue by martadinata666** [AnalogJ/scrutiny#426]
**Describe the bug**
Relase 0.6.0 missing frontend file, the web app become blank white page

**Expected behavior**
Web part working correctly, with frontend file exist.

**Comment by AnalogJ** [comment]
Sorry, is this in the docker container? or do you have a script that downloads the webapp frontend?

**Comment by martadinata666** [comment]
The frontend file of release 0.6.0 was missing, result 404 on download. Then i thought it packed into binary, but seems that is not the case. So i compared assets of 0.5.0 and 0.6.0, the web frontend tar.gz missing. ☕ 

Release 0.5.0
![2023-01-12-120304_1258x867_scrot](https://user-images.githubusercontent.com/2433562/211981649-6163527e-30b8-4afb-bc1a-6fe6668ed7c6.png)

Compared to release 0.6.0
![2023-01-12-120251_1266x825_scrot](https://user-images.githubusercontent.com/2433562/211981657-1a9f9ca5-4029-47e8-b690-bf43cd524432.png)

**Comment by AnalogJ** [comment]
ah apologies, looks like the GH Action failed. Let me get that fixed.

**Comment by AnalogJ** [comment]
Hey @martadinata666 
I manually generated the web frontend asset. Can you try using it and confirm that its working for you?

**Comment by martadinata666** [comment]
yes, it working. Thanks.

![2023-01-12-123317_1491x856_scrot](https://user-images.githubusercontent.com/2433562/211985650-fc387f8e-1cf8-4c01-b191-b55f9642910f.png)

**Comment by AnalogJ** [comment]
fantastic, closing

**Comment by thvd** [comment]
@AnalogJ seems like the `v0.6.0-web` version is still missing? https://github.com/AnalogJ/scrutiny/pkgs/container/scrutiny/versions?filters%5Bversion_type%5D=tagged

**Comment by AnalogJ** [comment]
yeah, the `v0.6.0-web` image is missing, however as a workaround you should be able to deploy `v0.5.0-web` since there were no UI changes between the latest releases. 

@thvd @d1ceward

**Comment by AnalogJ** [comment]
This has been permanently fixed with v0.7.0 (which upgrades the project to Angular 13.x)
