### ISSUE TITLE
[BUG] Changing the port causes it to say "scrutiny api not ready"

### ISSUE THREAD

**Issue by BadCoder12** [AnalogJ/scrutiny#429]
**Describe the bug**
I changed the port using the scrutiny.yaml to 9999 and I get "scrutiny api not ready"

**Expected behavior**
Login using the new port

version: 1

web:
  listen:
    port: 9999
    host: 0.0.0.0

This is what I get
time="2023-01-17T21:58:45Z" level=info msg="SQLite global configuration migrations completed successfully" type=web
scrutiny api not ready

When I change the port back to 8080 it works without any issues.

**Comment by AnalogJ** [comment]
this is a good catch. Scrutiny uses curl to check if the webapi and influxdb are ready before continuing. 

Though, I'm curious why you want to change the port within the container? That option is mostly intended for users running outside of docker to configure the port used.

**Comment by BadCoder12** [comment]
I like the inside/exposed ports to match if possible.

**Comment by AnalogJ** [comment]
ah. TBH I don't think it's worth the effort to implement a fix for this issue. I'm going to close this as `wontfix` but if you or other users have a compelling argument for why this should be changed, I'm willing to re-consider.
