### ISSUE TITLE
[FEAT] Support for ntfy notifications

### ISSUE THREAD

**Issue by fallenbagel** [AnalogJ/scrutiny#433]
**Is your feature request related to a problem? Please describe.**
I would like to be able to get notifications on [ntfy](https://github.com/binwiederhier/ntfy) about smart failures.

**Describe the solution you'd like**
Be able to receive ntfy notifications about smart failures on my devices.

**Additional context**
Ntfy (pronounce: notify) is an open sourced simple HTTP-based pub-sub notification service that allows notifications on phone, desktop.

**Comment by AnalogJ** [comment]
I see references to ntfy in the [shoutrrr codebase](https://github.com/search?q=repo%3Acontainrrr%2Fshoutrrr%20ntfy&type=code) (which is what Scrutiny uses for handling notifications to external services) -- it may already be supported, however their documentation site implies its only available in the `dev` branch https://containrrr.dev/shoutrrr/dev/services/ntfy/

**Comment by Robin-Sch** [comment]
You can use a webhook for ntfy like this:

```
version: 1
notify:
    urls:
        - "https://ntfy.sh/xxxx"
```

For authorization (with user:pass or a token), see https://docs.ntfy.sh/publish/#query-param

**Comment by fallenbagel** [comment]
> You can use a webhook for ntfy like this:
> 
> ```
> version: 1
> notify:
>     urls:
>         - "https://ntfy.sh/xxxx"
> ```
> 
> For authorization (with user:pass or a token), see https://docs.ntfy.sh/publish/#query-param

Oh yeah that works! Although the payload is sent as is so no formatting right? I think for the time being I'll just create a webhook server and then divert the payload to ntfy for the time being 🤔

**Comment by Robin-Sch** [comment]
Yeah it's sent as JSON, maybe there should be/is an option to just send it as text?

**Comment by AnalogJ** [comment]
looks like shoutrrr v7.1 has been released. This should be a fairly easy upgrade (and will natively support ntfy).
