### ISSUE TITLE
Drive marked as failed

### ISSUE THREAD

**Issue by yordanov-alexandar** [AnalogJ/scrutiny#439]
![nvme_status](https://user-images.githubusercontent.com/16528750/216769821-d2f73eab-f6e0-4a12-9753-ddd789cbedf1.png)
I am using scrutiny from a docker container where I've passed the internal nvme drive(Samsung 980 1TB). It's status is marked as failed although currently all status attributes are passed. There were a few days in the past that had critical warning failures so i am guessing they are the reason for the current failed status of the drive. The days with critical warnings coincide with days when there was a spike in drive temperature (to 84 C). My guess is that this high temperature triggered these critical warnings.
Is it correct that past Critical Warnings make the drive failed although there are no present Critical Warnings?
Thank you

**Comment by AnalogJ** [comment]
correct, Scrutiny takes into account historical failures to determine if a hard drive is failing.

There's no way to "mark a drive as healthy" in the UI, but you can do it via the commandline: 

https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#device-failed-but-smart--scrutiny-passed

**Comment by yordanov-alexandar** [comment]
Any way to prevent this type of error to mark a drive as failed? Spikes in temperatures will probably happen from time to time and after every one I'll have to reset the drive state.

**Comment by AnalogJ** [comment]
you can disable the Scrutiny analysis (which uses Backblaze data) and instead just depend on SMART metrics. 

Under Settings go to "Device Status - Thresholds" and select "SMART" instead of "Both". 
Then hit Save.

**Comment by yordanov-alexandar** [comment]
I have already done that but it is still marked as failed. Or do you mean that after I reset the status it will no longer be marked as failed for this reason? I'll try that

**Comment by yordanov-alexandar** [comment]
I have fully reset Scrutiny and set "Device Status - Thresholds" to SMART. Yesterday there was a temperature spike again and a corresponding Critical warning and the drive was marked as failed. Today everything is passed but the drive is still marked as failed.

**Comment by shortN0te** [comment]
@AnalogJ Is it planned to add a  "mark a drive as healthy" Button/Option to the UI?
![Screenshot_2023-02-12_12-09-26](https://user-images.githubusercontent.com/50641835/218307486-d3ecfdc0-2471-4aa4-8bae-c8f8894d355c.png)
The "Media Errors" is stable at 1 since 2 months i would consider it ok for now.

**Comment by yordanov-alexandar** [comment]
After some investigation it turned out that my SSD(Samsung 980) has a firmware bug. After flashing the fixed firmware I no longer have the temperature spikes and the corresponding critical warnings.
It still would be a good feature to have a "Mark drive as healthy" button though. But maybe the case can be handled by https://github.com/AnalogJ/scrutiny/issues/380

**Comment by AnalogJ** [comment]
Agreed, #380 is probably the right solution here. 

closing.
