### ISSUE TITLE
[BUG] Smart status passed but no info

### ISSUE THREAD

**Issue by dr400** [AnalogJ/scrutiny#444]
No information for Western Digital HDD

HDD details are given but not more.

![image](https://user-images.githubusercontent.com/48514024/218265822-2e451537-dd6b-4ad0-9f18-a9844cb82895.png)

![image](https://user-images.githubusercontent.com/48514024/218265922-5c77dbcb-c7af-4880-8e36-50553d84b0e6.png)

And status failed this morning : 

![image](https://user-images.githubusercontent.com/48514024/218299562-b0fa3e51-7d5d-40cb-a2ab-a02ae9cc2d4b.png)

When on synology interfaces : 

![image](https://user-images.githubusercontent.com/48514024/218265782-aebb49cc-e133-4aba-8ecc-347cbd3b3225.png)

Scrutiny is run under docker

**Comment by AnalogJ** [comment]
Please take a look at this troubleshooting guide - https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md

I'm going to close this issue, but feel free to reopen if you can't solve your issue after debugging or via a collector.yaml file
