### ISSUE TITLE
[FEAT] Doc on using collector.yaml with master-collector Docker container

### ISSUE THREAD

**Issue by samteezy** [AnalogJ/scrutiny#457]
**Is your feature request related to a problem? Please describe.**
I have a hub-and-spoke setup with a Synology NAS as the host (proper hub and spoke, not using the omnibus image). It's on the Synology where I am having some issues retrieving device data, and I would like to be able to set up collector.yaml to force device types and see if that fixes it.

It's not clear to me in the documentation how to use a collector.yaml file with the master-collector Docker container in a hub-and-spoke model.

I could be missing it, but I've been looking through all the docs for about 15 min and not finding anything.

**Describe the solution you'd like**
What is the appropriate volume mapping for the collector container that will allow me to specify a local collector.yaml file?

**Additional context**

**Comment by AnalogJ** [comment]
Hey @samteezy I think I saw your question already elsewhere, but if you're still looking, the collector.yaml file needs to be mapped to the `/opt/scrutiny/config` directory in the container. 

see: https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml

I'll close this issue for now, but feel free to reopen if that doesnt solve your issue.
