### ISSUE TITLE
[FEAT] Failed drives that are not powering on should have a different status

### ISSUE THREAD

**Issue by evilbulgarian** [AnalogJ/scrutiny#459]
**Is your feature request related to a problem? Please describe.**
Its hard to distinguish from Failed ( based on backblaze metrics ) vs actual drives that failed which are now not powering on. It would be nice if the drive in the DB is now not found to be a different failed status. So that way we can match the serial number and pull the drives out.

**Describe the solution you'd like**
A clear distinction between failed drives which are still online and failed drives which are offline.

**Additional context**

**Comment by AnalogJ** [comment]
Scrutiny is designed to support a hub/spoke deployment mode, which means it may not have direct access to the host, and so will not be able to determine which devices are connected/disconnected. 

Scrutiny does a have a different UI if it [hasn't received a SMART report for a drive in X days](https://github.com/AnalogJ/scrutiny/blob/e4bbe8c035cf5e7d42b8531fff137e689967b7f1/webapp/frontend/src/app/layout/common/dashboard-device/dashboard-device.component.ts#L60-L68):
- error - last scan as 1 month ago
- warn - last scan was 2 weeks ago.

**Comment by evilbulgarian** [comment]
> Scrutiny is designed to support a hub/spoke deployment mode, which means it may not have direct access to the host, and so will not be able to determine which devices are connected/disconnected.
> 
> Scrutiny does a have a different UI if it [hasn't received a SMART report for a drive in X days](https://github.com/AnalogJ/scrutiny/blob/e4bbe8c035cf5e7d42b8531fff137e689967b7f1/webapp/frontend/src/app/layout/common/dashboard-device/dashboard-device.component.ts#L60-L68):
> 
>     * error - last scan as 1 month ago
> 
>     * warn - last scan was 2 weeks ago.

Great thanks! Looking at the code seems like this is exactly what I was thinking. Thanks!
