### ISSUE TITLE
[FEAT] add htpasswd or some mechanism to protect webGUI with user/password

### ISSUE THREAD

**Issue by raulfg3** [AnalogJ/scrutiny#462]
I use your valuable piece of software on a docker and expose webGUI throught heimdall, I have secure conecction (https), but scrutiny do not ask for user/password on load .

I point you to heimdall that use standart htpassw to generate user/password to ask on page load, that I suposse is really easy to implemento on your docker image.

https://hub.docker.com/r/linuxserver/heimdall/

<img width="584" alt="image" src="https://user-images.githubusercontent.com/12611785/228622989-49dbab08-d628-4980-814e-7d501395745f.png">

**Comment by AnalogJ** [comment]
closing this as a dupe of #34
