### ISSUE TITLE
[FEAT] Disk name(s)

### ISSUE THREAD

**Issue by Robin-Sch** [AnalogJ/scrutiny#464]
**Is your feature request related to a problem? Please describe.**
It's difficult to keep apart multiple disks on two (or more) servers, especially if they are from the same brand. 

**Describe the solution you'd like**
It should be possible to give the disk a specific name. Like for example, I use ONE dashboard, for two servers with multiple disks per server. If I could rename each disk to for example "server 1 root" and "server 1 data1" or something like that, it could help to distinguish the different storage media. Instead of the two /dev/sda's which are now on the dashboard.

**Comment by AnalogJ** [comment]
this is already possible using the collector.yaml config file:

https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml#L19-L22

Also see the instructions in the troubleshooting docs:

https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#hub--spoke-model-with-multiple-hosts
