### ISSUE TITLE
[BUG] Timeout when Sending Data through Reverse Proxy via TLS

### ISSUE THREAD

**Issue by astr0n8t** [AnalogJ/scrutiny#467]
**Describe the bug**
I'm currently running scrutiny in Kubernetes and experiencing weird timeout issues when running the collector and accessing the API via a reverse proxy (Istio) over TLS.  Accessing through HTTP works as expected.

Basically, I have three devices I am scanning, two SATA and one NVMe running on a FreeBSD host.  The smartctl collection works as intended, but when trying to publish the data to the scrutiny web api, the first SATA drive JSON publishes fine, but then on the second drive I always receive the following error after the 60s timeout:
```
INFO[0003] Publishing smartctl results for 0x5000xxxxxxxxxxxxx  type=metrics
ERRO[0063] An error occurred while publishing SMART data for device (0x5000xxxxxxxxxxxxx): Post "https://scrutiny.domain.com/api/device/0x5000xxxxxxxxxxxxx/smart": context deadline exceeded (Client.Timeout exceeded while awaiting headers) type=metrics
INFO[0063] Main: Completed                               type=metrics
```

If the NVMe drive is published before this drive it also succeeds.  I'm currently working around by running the collector once for the first SATA and NVMe, and then running it a second time for the second SATA drive.  Oddly enough it also works fine if I disable the TLS redirect in Istio and run over plain http.

My guess is the client collector is trying to re-use a connection that Istio/envoy has since closed, but I have no way of verifying.

**Expected behavior**
My expectation is that the scrutiny collector would retry these POST requests three or more times to prevent transient network issues from posting SMART data.

I can write some rough retry logic, but wanted to post here first to see if that is a good avenue to pursue before making a PR.

**Comment by AnalogJ** [comment]
can you attach DEBUG logs for the web api? This is definitely unexpected. While we could probably fix it with some retries, I'd like to understand exactly whats breaking.

**Comment by astr0n8t** [comment]
I've attached the debug log from the server.  It most likely won't help though as it only contains the logs from the first drive and no logs about the second POST request.  I'm guessing it never actually receives the proxied connection from Istio, so I'm unsure if its necessarily a bug in scrutiny or Istio/envoy proxy (which isn't unheard of unfortunately).

Output triggering:
```
root@scrutiny:~ # /opt/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --config /opt/scrutiny/config/collector-3.yaml --api-endpoint="https://scrutiny.example.com/"
2023/04/05 20:06:39 Loading configuration file: /opt/scrutiny/config/collector.yaml

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                      freebsd.amd64-0.6.0

2023/04/05 20:06:39 Loading configuration file: /opt/scrutiny/config/collector-3.yaml
INFO[0000] Verifying required tools                      type=metrics
INFO[0000] Executing command: smartctl --scan --json     type=metrics
INFO[0000] Executing command: smartctl --info --json --device atacam /dev/ada0  type=metrics
INFO[0000] Generating WWN                                type=metrics
INFO[0000] Executing command: smartctl --info --json --device atacam /dev/ada1  type=metrics
INFO[0000] Generating WWN                                type=metrics
INFO[0000] Executing command: smartctl --info --json --device nvme /dev/nvme0  type=metrics
INFO[0000] Using WWN Fallback                            type=metrics
INFO[0000] Sending detected devices to API, for filtering & validation  type=metrics
INFO[0000] Collecting smartctl results for ada0          type=metrics
INFO[0000] Executing command: smartctl --xall --json --device atacam /dev/ada0  type=metrics
INFO[0000] Publishing smartctl results for 0x5000xxxxxxxxxxxxx  type=metrics
INFO[0003] Collecting smartctl results for ada1          type=metrics
INFO[0003] Executing command: smartctl --xall --json --device atacam /dev/ada1  type=metrics
INFO[0003] Publishing smartctl results for 0x5000xxxxxxxxxxxxx  type=metrics
ERRO[0063] An error occurred while publishing SMART data for device (5000xxxxxxxxxxxxx): Post "https://scrutiny.example.com/api/device/5000xxxxxxxxxxxxx/smart": context deadline exceeded (Client.Timeout exceeded while awaiting headers)  type=metrics
INFO[0063] Collecting smartctl results for nvme0         type=metrics
INFO[0063] Executing command: smartctl --xall --json --device nvme /dev/nvme0  type=metrics
INFO[0063] Publishing smartctl results for 5000xxxxxxxxxxxxx  type=metrics
ERRO[0083] An error occurred while publishing SMART data for device (5000xxxxxxxxxxxxx): Post "https://scrutiny.example.com/api/device/5000xxxxxxxxxxxxx/smart": read tcp X.X.X.X:34810->X.X.X.X:443: read: operation timed out  type=metrics
INFO[0083] Main: Completed
```

**Comment by astr0n8t** [comment]
I no longer seeing this as of server version `v0.8.1` not sure if it was an issue on my end or something within scrutiny, the client is still version `0.6.0` but I have changed the networking drastically so it is possible that contributed to it as well.
