### ISSUE TITLE
[BUG] Verify Notifications Logic

### ISSUE THREAD

**Issue by mpadvisory** [AnalogJ/scrutiny#473]
I am running a Scrutiny container on my Unraid box for S.M.A.R.T. monitoring / alerting. The parameters allow for various notification services inside the configuration file for the container.

I passed through a Discord webhook value to the configuration file and spun it up. To test, I followed the developer’s  request for an empty payload via command `curl -X POST http://localhost:PORT/api/health/notify` which leverages the notification’s health check API. Each time I test I receive `{"success":true,"errors":null,"data":null}` back, and my Discord webhook sends back a faux S.M.A.R.T. error on /dev/sda EmailTest notification. 

![image](https://user-images.githubusercontent.com/92036460/230696823-3c4dbd03-f18f-4681-9453-f4763aba019f.png)

Is it possible that because of none of the disks have actually failed a S.M.A.R.T. attribute value, that’s why I would only see the EmailTest triggered and no notification on the other disks? The documentation isn’t very clear on parameters for notification trigger other than it supports sending SMART device failure notifications. 

I would think logically I have set it up correctly since I’m A) receiving an EmailTest notification from the health check API and B) no conditions have been met on /dev/sdb - /sdi, but want to verify that no other configuration is necessary for successful notification.

**Comment by AnalogJ** [comment]
> Is it possible that because of none of the disks have actually failed a S.M.A.R.T. attribute value, that’s why I would only see the EmailTest triggered and no notification on the other disks? 

Not quite, `curl -X POST http://localhost:PORT/api/health/notify` is only intended to test your notifications are configured correctly, `/dev/sda` is just a placeholder, and you can see from the `Device Serial: FAKE...` that it's not actually using your real device data. 

If you're receiving a message, your notification are working. 

I'm going to close this issue, but feel free to reopen if you have any additional questions.
