### ISSUE TITLE
[FEAT] Field for host/hostname

### ISSUE THREAD

**Issue by jangxbanger** [AnalogJ/scrutiny#475]
**Is your feature request related to a problem? Please describe.**
Not a problem per say. just a worthwhile feature. It is difficult to find disks associated to a certain device when having collectors send to a single web/api endpoint.

**Describe the solution you'd like**
Would thoroughly like to see a field added for hostname of the device and be able to sort the disks by the device. Would be really neat if I could do this in a variable for the collector. I would even take just a blank field and manually populate the data myself as well.

**Additional context**
Nothing further to add.

**Comment by rasodu** [comment]
I am also looking for hostname on list disk. Is there a way to list it?
