### ISSUE TITLE
"SATA downshift error count" false positive? 

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [AnalogJ/scrutiny#477]
My drive is currently marked as failed because of that value being 3. However, it's not from one of the manufacturers listed in the description. It's from Crucial and I wasn't able to find any information on what they use this attribute for.

If it only applies to Western Digital, Samsung and Seagate, should it maybe only be flagged as failed if a drive is from them?

(Don't know whether this additional info matters but... the drive is only a few weeks old, barely used and the Smart value for this attribute is 100.)

**Comment by AnalogJ** [comment]
can you attach the smartctl output for this disk?

**Comment by s-h-a-d-o-w** [comment]
This has resolved itself somehow. The overall drive is now marked as “passed” and only if I look at the details, there’s a red dot next to “passed” and the row I mentioned in the OP is marked as “failed” (still has the same value).
