### ISSUE TITLE
Why are two databases used?

### ISSUE THREAD

**Issue by Robin-Sch** [AnalogJ/scrutiny#492]
Why does scrutiny both use influxdb, and a `scrutiny.db` file? And is it possible to only use the .db file?

**Comment by AnalogJ** [comment]
InfluxDB and Sqlite are intended for different purposes. 
Here's a good summary for why we decided to use InfluxDB - https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md#why
