### ISSUE TITLE
[BUG] Logo isn't displayed when image is run as non-root user

### ISSUE THREAD

**Issue by kaysond** [AnalogJ/scrutiny#502]
**Describe the bug**
If I run the scrutiny image with a `--user` or `user:` setting, the image assets don't load

**Expected behavior**
Image should load

**Screenshots**
![image](https://github.com/AnalogJ/scrutiny/assets/1147328/194fd826-4a2e-44c4-97d4-8a52f6f24221)

I'm guessing the issue is that `/opt/scrutiny/web/assets` in the container image does not have executable permission set (and maybe can't be read either?).

**Comment by kaysond** [comment]
Just tried adding an extra chmod to the dockerfile and it fixes the problem. Let me know if you'd like a PR!

**Comment by atlanticfirst** [comment]
same issue，--cap-add=DAC_OVERRIDE fixes the problem

**Comment by kaysond** [comment]
Fixed by #520
