### ISSUE TITLE
[FEAT] [Question] Agentless monitoring

### ISSUE THREAD

**Issue by dimkasta** [AnalogJ/scrutiny#511]
**Is your feature request related to a problem? Please describe.**
I want to setup a sort of agent-less check. Imagine something like Uptime Kuma checking either the dashboard page or an API endpoint, and raising a failure if it detects a keyword like Warning or Failure. Or checking an API endpoint

I am currently want to check the dashboard and raisi a notification if the word "Passed" is not detected. It would work for me because I have single disks on my machines. But it will not work for multiple ones, since a single "Passed" disk would be enough to flag it as ok.

What are the status values that should raise concern?

**Describe the solution you'd like**
Documenting the exact status values should be enough for keyword detection. 

For more complex setups, exposing a rest API endpoint returning something like 

warning=true or 
critical=true and 
warningdevice=/dev/sda

**Additional context**

**Comment by dimkasta** [comment]
I just saw that /api/summary is a thing. Nice.
Does "device_status":0 mean passing? What are the values that would trigger a notification?

**Comment by meunomemauricio** [comment]
@dimkasta it does seems to be the case:

https://github.com/AnalogJ/scrutiny/blob/2f01e8c8e0ad663924aecd55a1979fa3a8c17c04/webapp/frontend/src/app/shared/device-status.pipe.ts#L12-L17

**Comment by AnalogJ** [comment]
Correct, there is an API (which is what the UI uses). You can use the device status flags to determine the health of the disk (as analyzed by Smart, Scrutiny or both).
