### ISSUE TITLE
[FEAT] Manually change thresholds

### ISSUE THREAD

**Issue by NLZ** [AnalogJ/scrutiny#514]
**Is your feature request related to a problem? Please describe.**
So I have a couple questionable disks that Scrutiny said they failed, but for now I'm taking the risk of using them.
Would be nice to say to Scrutiny that I accept the current situation as non-critical, so only flag them as failed if they get worse.

**Describe the solution you'd like**
I would like to manually increate the tresholds for a given disk.
Lets say on /dev/sda the Reallocated Sectors Count (0x05) is 8192 for this SSD, which is not good, but because it's not changing, I could set the config that 8192 is still WARN.

**Additional context**
Is the `limits` in example.scrutiny.yaml Features Coming Soon section going to implement something like this? Coudnt
https://github.com/AnalogJ/scrutiny/blob/master/example.scrutiny.yaml#L90

**Comment by AnalogJ** [comment]
TBH I never implemented a feature like this, but I can see why some users would like it. 
You have a couple of options, you can ignore the Scrutiny thresholds (while keeping SMART), or open a PR to add support for custom thresholds.

**Comment by NLZ** [comment]
I don't have the expertise to add this feature, so I guess I just have to live with it

**Comment by SaraDark** [comment]
I would also be interested in the possibility of setting individual thresholds for a specific disk + optionally a server (group of disks) :)

**Comment by taufikterdidik** [comment]
Yes, I need this feature. I have refurbished disk that still work (just for parity in snapraid) but the notification sends continuously about that failed/error disk. I want to except/ignore those disks.
