### ISSUE TITLE
[FEAT] Support setting/overriding config variables with docker environment variables

### ISSUE THREAD

**Issue by shamoon** [AnalogJ/scrutiny#52]
**Is your feature request related to a problem? Please describe.**
A nice feature implemented by other docker-friendly projects is to allow setting config values via docker environment variables. While certainly not mission-critical this can help keep things neater with all config in e.g. a docker-compose file

**Describe the solution you'd like**
E.g.
```
    environment:
      - SCRUTINY_NOTIFY_PUSHOVER=pushover://shoutrrr:apiToken@userKey/?devices=device1
```

**Additional context**
E.g. https://wiki.cajun.pro/books/varken/page/breakdown#bkmrk-environment-variable
Thanks for this awesome tool.

**Comment by AnalogJ** [comment]
Yeah, this is a good idea. I'm using Viper for config parsing, and it supports [loading config from the environment as well](https://github.com/spf13/viper#working-with-environment-variables). I just need to enable it.

**Comment by faucherc** [comment]
Do you have enabled it? How can we use it?  It's a very nice feature to pass notification password to the container and don't commit the password in a config repo.

**Comment by AnalogJ** [comment]
Yes, this should already work, though I haven't tested it myself. 
As I mentioned, scrutiny uses [Viper](https://github.com/spf13/viper/issues/339) under the hood for config/env parsing. 

You **should** be able to do this (please comment again if this doesnt work):

```

# note, "lines" are space delimited in the environmental variable. 
export SCRUTINY_NOTIFY_URLS="discord://token@channel telegram://token@telegram?channels=channel-1" 
scrutiny-collector

# the environmental variable above should be equivalent to the following config stanza
# notify:
#  urls:
#    - "discord://token@channel"
#    - "telegram://token@telegram?channels=channel-1"


```

**Comment by faucherc** [comment]
I have tried it this morning.  And unfortunatly I didn't find any way get it working.

I have dig some part of the code. And I think you need to activate the feature with the Viper method "AutomaticEnv" and optionally the method "SetEnvPrefix".  I don't have find any referece to this in your code.

https://github.com/spf13/viper#working-with-environment-variables

**Comment by AnalogJ** [comment]
apologies, yeah I noticed that yesterday. It's fixed in the Influxdb branch: https://github.com/AnalogJ/scrutiny/blob/influxdb/webapp/backend/pkg/config/config.go#L68-L71

Once that code is merged to master, we can close this issue.

**Comment by faucherc** [comment]
No problem. I will follow and wait the influxdb branch.  Thanks

**Comment by AnalogJ** [comment]
Almost all Scrutiny configuration can now be set via environmental variables. (v0.4.1+)

Scrutiny web options are prefixed with `SCRUTINY_` and Collector options are prefixed with `COLLECTOR_`

eg. `web.listen.port` becomes `SCRUTINY_WEB_LISTEN_PORT=8080` and `host.id` becomes `COLLECTOR_HOST_ID`. 

Closing this for now, feel free to reopen if there are more questions.
