### ISSUE TITLE
Email notification help

### ISSUE THREAD

**Issue by kevinruffus** [AnalogJ/scrutiny#532]
There's no discussion section to post and ask for help, so here it goes:

I run mailu. I've got every other service configured to use it for email notifications, including my host server.
I cannot get Scrutiny to work using email.
See below error:

{"errors":["error initializing router services: parse \"smtp://mail@my.domain.com:mailspasswordwithspecialchars@ms.my.domain.com:587/?FromAddress=scrutiny@my.domain.com\u0026ToAddresses=myemail@gmail.com\": net/url: invalid userinfo"],"success":false}

mail is the user I've configured to serve as the login for all services, using aliases for each service to allow logins when the from doesn't match. It's working in Bitwarden, Postfix, Overseerr, ownCloud, Watchtower, Uptime-Kuma, PFSense, my self-hosted RMM, etc.

Is the issue that the password supplied contains special chars like ^ ? I tried escaping them but it continued to fail.

**Comment by izzoa** [comment]
This is just a guess, but I would imagine it's a combination of the `@` in your username (which Shoutrrr will attempt to parse  into the following [password] field) and perhaps also the special characters in your password. 

I'd first try replacing `@` with its respective HTML encoding, which is `%40`, then if that still doesn't work, try doing the same for the special characters in your password as well. Here's a guide: (https://www.w3schools.com/tags/ref_urlencode.ASP).

**Comment by ninjamonkey198206** [comment]
I will give that a shot. Thank you!

**Comment by kevinruffus** [comment]
I had to replace each special character in both the username and password, but it worked after that. Thank you!

May want to add a note into the readme/troubleshooting about that little nugget. I don't think I saw that in there.

I'll check the Shoutrrr info for any mention of that, and if I don't find anything I'll mention it to them as well.

With special chars being so prevalent now in passwords, the info on how to use them correctly should be right up front at least, that way folks don't smash their heads into their keyboards until they have qwerty permanently imprinted on their foreheads.

**Comment by kevinruffus** [comment]
And the dual names for me reminds me that I need to finish moving things to the new profile so I can finally kill off that other email address...

**Comment by izzoa** [comment]
Awesome! 

I'm actually surprised the special characters in the password threw it off too (unless you had another `@`, `:`, or `/` in there). That tells me that however Shoutrrr is parsing out the urls, they're not casing it properly. So could definitely be worth mentioning there too, because as you mention, special characters are so prevalent (and even necessary!) in passwords these days. 

Anyway, glad it's working for you now! I'm just a random dude browsing this project throwing out suggestions haha, so I'll leave it to @AnalogJ to add that tidbit as a suggestion in the readme :)

**Comment by ninjamonkey198206** [comment]
I'll look and see if any of the characters were those.

Maybe a note to check that your password doesn't include those chars wouldn't hurt either. That link to the codes definitely helped, thank you.

**Comment by AnalogJ** [comment]
Special characters should work, however you'll need to url-encode the username and the password separately.

eg.

- your username is: `myname@example.com`
- your password is `124@34$1`

Then your shoutrrr url will look something like:

`smtp://myname%40example%2Ecom:124%4034%241@ms.my.domain.com:587`

I haven't verified this, but I'm pretty sure that should work.

**Comment by ninjamonkey198206** [comment]
> Special characters should work, however you'll need to url-encode the username and the password separately.
> 
> eg.
> 
> * your username is: `myname@example.com`
> * your password is `124@34$1`
> 
> Then your shoutrrr url will look something like:
> 
> `smtp://myname%40example%2Ecom:124%4034%241@ms.my.domain.com:587`
> 
> I haven't verified this, but I'm pretty sure that should work.

That's pretty much what I did. I guess I wasn't clear enough. That's the part I was suggesting might be worth documenting. "If your username and/or password include these characters, you'll need to encode them. Here are their values:"

**Comment by ninjamonkey198206** [comment]
Just to save some time. Then if someone else comes across it, you can just post the link to that page and say RTFM.
