### ISSUE TITLE
[HELP] How to install Scrunity on Proxmox

### ISSUE THREAD

**Issue by AuthorShin** [AnalogJ/scrutiny#534]
Hello
Thank you very much for creating and maintaining this awesome and critical app
I know it's not a right place to ask for this but I couldn't find a discussion section or a Discord server to ask for guidance regarding installing Scrunity on Proxmox.
The approach I'm looking forward to is since the collector and DB and WebUI are separated, install the collector on the Proxmox host without docker and then have WebUI and DB via docker on a VM that's getting the data from the collector, but reading and trying with the documents I couldn't quite understand the procedure and hence I'm opening this issue.
Thanks in advance

**Comment by AnalogJ** [comment]
https://github.com/AnalogJ/scrutiny/blob/master/docs/INSTALL_HUB_SPOKE.md might be a good guide for you

I'm going to close this issue, but feel free to reopen/comment if that doesnt help.

**Comment by AuthorShin** [comment]
Thank you very much for the link, with that guide I was able to setup Scrutiny on 2 of my Proxmox servers and it's just been awesome experience using it.
Hope it grow more and more during time and get the attention it actually deserves.

**Comment by AuthorShin** [comment]
@AnalogJ However there seems to be a problem with cronjob part of that guide that with cronjob it's not getting the data and the chart it's not getting update but when I manually execute the command it's updating the info on Scrutiny.

Like the guide said I just added the following line to the `crontab -e`
```
*/15 * * * * /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://192.168.11.99:8714"
```


Output of `service cron status`
```
● cron.service - Regular background program processing daemon
     Loaded: loaded (/lib/systemd/system/cron.service; enabled; preset: enabled)
     Active: active (running) since Sun 2023-11-05 12:23:22 UTC; 2 weeks 1 day ago
       Docs: man:cron(8)
   Main PID: 1659 (cron)
      Tasks: 1 (limit: 38038)
     Memory: 804.0K
        CPU: 4.110s
     CGroup: /system.slice/cron.service
             └─1659 /usr/sbin/cron -f

Nov 21 09:15:01 InfinityGauntlet CRON[2579269]: pam_unix(cron:session): session closed for user root
Nov 21 09:17:01 InfinityGauntlet CRON[2580346]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Nov 21 09:17:01 InfinityGauntlet CRON[2580347]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
Nov 21 09:17:01 InfinityGauntlet CRON[2580346]: pam_unix(cron:session): session closed for user root
Nov 21 09:30:01 InfinityGauntlet CRON[2586441]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Nov 21 09:30:01 InfinityGauntlet CRON[2586442]: (root) CMD (/opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://192.168.11.99:8714")
Nov 21 09:30:01 InfinityGauntlet CRON[2586441]: pam_unix(cron:session): session closed for user root
Nov 21 09:45:01 InfinityGauntlet CRON[2593746]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Nov 21 09:45:01 InfinityGauntlet CRON[2593747]: (root) CMD (/opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://192.168.11.99:8714")
Nov 21 09:45:01 InfinityGauntlet CRON[2593746]: pam_unix(cron:session): session closed for user root
```

**Comment by AuthorShin** [comment]
@AnalogJ Also I added the `COLLECTOR_RUN_STARTUP=true` and `COLLECTOR_RUN_STARTUP_SLEEP=10` as environment variables which was pointed in https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md but still didn't work for me.

**Comment by ushio75** [comment]
> @AnalogJ However there seems to be a problem with cronjob part of that guide that with cronjob it's not getting the data and the chart it's not getting update but when I manually execute the command it's updating the info on Scrutiny.
> 
> Like the guide said I just added the following line to the `crontab -e`
> 
> ```
> */15 * * * * /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://192.168.11.99:8714"
> ```
> 
> Output of `service cron status`
> 
> ```
> ● cron.service - Regular background program processing daemon
>      Loaded: loaded (/lib/systemd/system/cron.service; enabled; preset: enabled)
>      Active: active (running) since Sun 2023-11-05 12:23:22 UTC; 2 weeks 1 day ago
>        Docs: man:cron(8)
>    Main PID: 1659 (cron)
>       Tasks: 1 (limit: 38038)
>      Memory: 804.0K
>         CPU: 4.110s
>      CGroup: /system.slice/cron.service
>              └─1659 /usr/sbin/cron -f
> 
> Nov 21 09:15:01 InfinityGauntlet CRON[2579269]: pam_unix(cron:session): session closed for user root
> Nov 21 09:17:01 InfinityGauntlet CRON[2580346]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
> Nov 21 09:17:01 InfinityGauntlet CRON[2580347]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
> Nov 21 09:17:01 InfinityGauntlet CRON[2580346]: pam_unix(cron:session): session closed for user root
> Nov 21 09:30:01 InfinityGauntlet CRON[2586441]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
> Nov 21 09:30:01 InfinityGauntlet CRON[2586442]: (root) CMD (/opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://192.168.11.99:8714")
> Nov 21 09:30:01 InfinityGauntlet CRON[2586441]: pam_unix(cron:session): session closed for user root
> Nov 21 09:45:01 InfinityGauntlet CRON[2593746]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
> Nov 21 09:45:01 InfinityGauntlet CRON[2593747]: (root) CMD (/opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://192.168.11.99:8714")
> Nov 21 09:45:01 InfinityGauntlet CRON[2593746]: pam_unix(cron:session): session closed for user root
> ```

confermo ,anche a me non funziona...soluzioni?

**Comment by AuthorShin** [comment]
@ushio75 I used systemd instead of cronjob and it's been working that way.

**Comment by shaftspanner** [comment]
I also had problems with the collector running flawlessly when triggered manually, but failing to run using cron.  I switched to Systemd timers using this guide (https://www.howtogeek.com/replace-cron-jobs-with-systemd-timers/) and it's worked without issue ever since.

**Comment by phcreery** [comment]
I also had problems with cron. It would execute but only print the SCRUTINY title. I switched to systemd timers and it works now. Below is how I did it.

`sudo nano /root/scrutiny/scrutiny.sh`
```
#!/bin/bash

/opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://192.168.1.xxx:8080" | tee /var/log/scrutiny.log
```


`sudo nano /etc/systemd/system/scrutiny.service`
```
[Unit]
Description="Scrutiny Collector"
Requires=scrutiny.timer

[Service]
Type=simple
ExecStart=/root/scrutiny/scrutiny.sh
User=root
```


`sudo nano /etc/systemd/system/scrutiny.timer`
```
[Unit]
Description="Timer for the scrutiny.service"

[Timer]
Unit=scrutiny.service
OnBootSec=5min
OnUnitActiveSec=1min

[Install]
WantedBy=timers.target
```


`sudo systemctl enable scrutiny.timer`
`sudo systemctl start scrutiny.timer`

**Comment by hoggatt** [comment]
> I also had problems with cron. It would execute but only print the SCRUTINY title. I switched to systemd timers and it works now. Below is how I did it.
> 
> `sudo nano /root/scrutiny/scrutiny.sh`
> 
> ```
> #!/bin/bash
> 
> /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://192.168.1.xxx:8080" | tee /var/log/scrutiny.log
> ```
> ...

FYI, this only worked for me when I made the `scrutiny.sh` script executable: 
```bash
chmod +x /root/scrutiny/scrutiny.sh
```


For those who are interested, here is my whole script that automates this:
```bash
#!/bin/bash

# change as needed
API_ENDPOINT="http://192.168.1.xx:8081"


####################################
# Install Scrutiny Collector

# Installing dependencies
apt install smartmontools -y 

# Define variables
INSTALL_DIR="/opt/scrutiny"
BIN_DIR="$INSTALL_DIR/bin"
LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/AnalogJ/scrutiny/releases/latest | grep "browser_download_url.*scrutiny-collector-metrics-linux-amd64" | cut -d '"' -f 4)

# Create the installation directory if it doesn't exist
mkdir -p $BIN_DIR

# Download the latest release
curl -L $LATEST_RELEASE_URL -o $BIN_DIR/scrutiny-collector-metrics-linux-amd64

# Make the binary executable
chmod +x $BIN_DIR/scrutiny-collector-metrics-linux-amd64


#####################################
# Install Scrutiny Service

# Create the directory if it doesn't exist
mkdir -p /root/scrutiny

# Write the script to /root/scrutiny/scrutiny.sh
cat << EOF > /root/scrutiny/scrutiny.sh
#!/bin/bash

/opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "$API_ENDPOINT" 2>&1 | tee /var/log/scrutiny.log
EOF

# Make the script executable
chmod +x /root/scrutiny/scrutiny.sh

# Write the service file to /etc/systemd/system/scrutiny.service
cat << 'EOF' > /etc/systemd/system/scrutiny.service
[Unit]
Description="Scrutiny Collector"
Requires=scrutiny.timer

[Service]
Type=simple
ExecStart=/root/scrutiny/scrutiny.sh
User=root
EOF

# Write the timer file to /etc/systemd/system/scrutiny.timer
cat << 'EOF' > /etc/systemd/system/scrutiny.timer
[Unit]
Description="Timer for the scrutiny.service"

[Timer]
Unit=scrutiny.service
OnBootSec=5min
OnUnitActiveSec=15min

[Install]
WantedBy=timers.target
EOF

# Reload the systemd manager configuration
systemctl enable scrutiny.timer
systemctl start scrutiny.timer

# show status to prove it's running
systemctl status scrutiny.timer
```

**Comment by rickygm** [comment]
Hi , I'm trying run this script, when I run it it shows me the following:

`./scrutiny.sh
2025/02/10 18:29:25 No configuration file found at /opt/scrutiny/config/collector.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                        linux.amd64-0.8.1

time="2025-02-10T18:29:25-06:00" level=info msg="Verifying required tools" type=metrics
time="2025-02-10T18:29:25-06:00" level=info msg="Executing command: smartctl --scan --json" type=metrics
time="2025-02-10T18:29:25-06:00" level=info msg="Executing command: smartctl --info --json --device sat /dev/sda" type=metrics
time="2025-02-10T18:29:25-06:00" level=info msg="Generating WWN" type=metrics
time="2025-02-10T18:29:25-06:00" level=info msg="Executing command: smartctl --info --json --device sat /dev/sdb" type=metrics
time="2025-02-10T18:29:25-06:00" level=info msg="Generating WWN" type=metrics
time="2025-02-10T18:29:25-06:00" level=info msg="Executing command: smartctl --info --json --device nvme /dev/nvme0" type=metrics
time="2025-02-10T18:29:25-06:00" level=info msg="Using WWN Fallback" type=metrics
time="2025-02-10T18:29:25-06:00" level=info msg="Sending detected devices to API, for filtering & validation" type=metrics
2025/02/10 18:29:25 ERROR: Post "http://192.168.30.2:8081/api/devices/register": dial tcp 192.168.30.2:8081: connect: connection refused`

any idea?

**Comment by kzaoaai** [comment]
Instead of switching to systemd, I just passed the smartctl path to cron. The crontab line becomes:

`*/5 * * * * PATH=/usr/sbin:/usr/bin:/bin:/opt/scrutiny/bin /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://SCRUTINYHOST:8080"`

**Comment by rickygm** [comment]
I made the change, but I can't get it to work

[root@srv bin]$  /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://srv:8080"
2025/02/24 20:47:56 No configuration file found at /opt/scrutiny/config/collector.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                        linux.amd64-0.8.1

INFO[0000] Verifying required tools                      type=metrics
INFO[0000] Executing command: smartctl --scan --json     type=metrics
INFO[0000] Executing command: smartctl --info --json --device sat /dev/sda  type=metrics
INFO[0000] Generating WWN                                type=metrics
INFO[0000] Executing command: smartctl --info --json --device sat /dev/sdb  type=metrics
INFO[0000] Generating WWN                                type=metrics
INFO[0000] Executing command: smartctl --info --json --device nvme /dev/nvme0  type=metrics
INFO[0000] Using WWN Fallback                            type=metrics
INFO[0000] Sending detected devices to API, for filtering & validation  type=metrics

`ERROR: Post "http://srv:8080/api/devices/register": dial tcp 192.168.30.2:8080: connect: connection refused`

**Comment by kzaoaai** [comment]
This seems like a different issue and the server is not reachable. Does the normal command work if you try it in your client terminal?

`/opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://srv:8080"`

If it doesn't work, then your problem is not cron

**Comment by rickygm** [comment]
That command doesn't work for me

`2025/02/24 22:31:48 ERROR: Post "http://srv:8080/api/devices/register": dial tcp 192.168.30.2:8080: connect: connection refused`

Do you think it could be a problem with the package itself?

my version of Proxmox 

proxmox-ve: 8.2.0 (running kernel: 6.8.12-2-pve)
pve-manager: 8.2.7 (running version: 8.2.7/3e0176e6bb2ade3b)

**Comment by kzaoaai** [comment]
this is due to your srv:8080 not being accessible to the proxmox host. Is the webgui accessible at that address?

Also, to be sure, these are the commands you should run on the proxmox host prior:
```
apt install smartmontools -y 
mkdir -p /opt/scrutiny/bin && \
curl -L https://github.com/AnalogJ/scrutiny/releases/download/v0.8.1/scrutiny-collector-metrics-linux-amd64 > /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 && \
chmod +x /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 && \
ls -lha /opt/scrutiny/bin
```

**Comment by rickygm** [comment]
`ls -lha /opt/scrutiny/bin
-rwxr-xr-x 1 root root 13M Feb 25 05:43 scrutiny-collector-metrics-linux-amd64`

I had already done those steps before, port 8080 is not listening, and I have it open in the firewall

**Comment by kzaoaai** [comment]
then the problem is in your main instance (docker) not your collector. Check the logs from that one. You should be able to access the gui even with no collectors running.

**Comment by rickygm** [comment]
sorry for delay , I had to use docker to make it work, thanks for your help

**Comment by kipavy** [comment]
> > I also had problems with cron. It would execute but only print the SCRUTINY title. I switched to systemd timers and it works now. Below is how I did it.
> > `sudo nano /root/scrutiny/scrutiny.sh`
> > ```
> > #!/bin/bash
> > 
> > /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://192.168.1.xxx:8080" | tee /var/log/scrutiny.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...
> 
> FYI, this only worked for me when I made the `scrutiny.sh` script executable:
> 
> chmod +x /root/scrutiny/scrutiny.sh
> For those who are interested, here is my whole script that automates this:
> 
> #!/bin/bash
> 
> # change as needed
> API_ENDPOINT="http://192.168.1.xx:8081"
> 
> 
> ####################################
> # Install Scrutiny Collector
> 
> # Installing dependencies
> apt install smartmontools -y 
> 
> # Define variables
> INSTALL_DIR="/opt/scrutiny"
> BIN_DIR="$INSTALL_DIR/bin"
> LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/AnalogJ/scrutiny/releases/latest | grep "browser_download_url.*scrutiny-collector-metrics-linux-amd64" | cut -d '"' -f 4)
> 
> # Create the installation directory if it doesn't exist
> mkdir -p $BIN_DIR
> 
> # Download the latest release
> curl -L $LATEST_RELEASE_URL -o $BIN_DIR/scrutiny-collector-metrics-linux-amd64
> 
> # Make the binary executable
> chmod +x $BIN_DIR/scrutiny-collector-metrics-linux-amd64
> 
> 
> #####################################
> # Install Scrutiny Service
> 
> # Create the directory if it doesn't exist
> mkdir -p /root/scrutiny
> 
> # Write the script to /root/scrutiny/scrutiny.sh
> cat << EOF > /root/scrutiny/scrutiny.sh
> #!/bin/bash
> 
> /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "$API_ENDPOINT" 2>&1 | tee /var/log/scrutiny.log
> EOF
> 
> # Make the script executable
> chmod +x /root/scrutiny/scrutiny.sh
> 
> # Write the service file to /etc/systemd/system/scrutiny.service
> cat << 'EOF' > /etc/systemd/system/scrutiny.service
> [Unit]
> Description="Scrutiny Collector"
> Requires=scrutiny.timer
> 
> [Service]
> Type=simple
> ExecStart=/root/scrutiny/scrutiny.sh
> User=root
> EOF
> 
> # Write the timer file to /etc/systemd/system/scrutiny.timer
> cat << 'EOF' > /etc/systemd/system/scrutiny.timer
> [Unit]
> Description="Timer for the scrutiny.service"
> 
> [Timer]
> Unit=scrutiny.service
> OnBootSec=5min
> OnUnitActiveSec=15min
> 
> [Install]
> WantedBy=timers.target
> EOF
> 
> # Reload the systemd manager configuration
> systemctl enable scrutiny.timer
> systemctl start scrutiny.timer
> 
> # show status to prove it's running
> systemctl status scrutiny.timer

Thanks, for LATEST_RELEASE_URL you could've just used https://github.com/AnalogJ/scrutiny/releases/latest/download/scrutiny-collector-metrics-linux-amd64
