### ISSUE TITLE
Disk stats don't update

### ISSUE THREAD

**Issue by Maxobus** [AnalogJ/scrutiny#537]
Hello

Running in Docker mode.
There are no updates in the dashboard for 2 days. It shows only initial info after install.

I also added: 
```
    environment:
      - 'COLLECTOR_CRON_SCHEDULE=*/1 * * * *'
```
in `docker-compose.yml` file.

And in the container's `/etc/cron.d/scrutiny` there is `*/1 * * * * root . /env.sh; /opt/scrutiny/bin/scrutiny-collector-metrics run >/proc/1/fd/1 2>/proc/1/fd/2` corresponding string.

Please assist.

**Comment by vincejv** [comment]
haven't had any updates on my end since October 8 lol
![image](https://github.com/AnalogJ/scrutiny/assets/1276544/da48fa96-9c11-4330-8bdb-19a4e5e271b0)

**Comment by vincejv** [comment]
getting this error everytime i run the collector
```sh
root@ab818fff5aaa:/opt/scrutiny# scrutiny-collector-metrics run
2023/10/30 05:17:07 No configuration file found at /opt/scrutiny/config/collector.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                                dev-0.7.1

INFO[0000] Verifying required tools                      type=metrics
INFO[0000] Executing command: smartctl --scan --json     type=metrics
INFO[0000] Executing command: smartctl --info --json /dev/sda  type=metrics
INFO[0000] Using WWN Fallback                            type=metrics
INFO[0000] Executing command: smartctl --info --json /dev/sdb  type=metrics
INFO[0000] Generating WWN                                type=metrics
INFO[0000] Sending detected devices to API, for filtering & validation  type=metrics
2023/10/30 05:17:07 ERROR: invalid character '<' looking for beginning of value
```

**Comment by vincejv** [comment]
@Maxobus can you run `scrutiny-collector-metrics run` on the container to see if we have the same error message?

**EDIT:** I was able to fix the issue by setting the environment variables as per documentation, i only set the `SCRUTINY_WEB_LISTEN_BASEPATH` that's why it was not working

> # Environmental Variables.
> 
> You may also configure these values using the following environmental variables (both are required).
> 
> - `COLLECTOR_API_ENDPOINT=http://localhost:8080/custombasepath`
> - `SCRUTINY_WEB_LISTEN_BASEPATH=/custombasepath`

**Comment by Maxobus** [comment]
@vincejv thanks a lot!
After adding these two Environmental Variables problem solved.

**Comment by vincejv** [comment]
@Maxobus glad to hear it's fixed, cna you close the issue then?
