### ISSUE TITLE
[FEAT] Include host identifier with disks

### ISSUE THREAD

**Issue by Gorian** [AnalogJ/scrutiny#542]
**Is your feature request related to a problem? Please describe.**
Scrutiny doesn't seem to include hostnames or any other identifiers when displaying disks in the dashboard. When you run the scrutiny server with multiple clients, this is an issue as you don't know which disk belongs to which hosts.

**Describe the solution you'd like**
Include an option to display server hostnames with the disks. Maybe an option to set the hostname via variable, as containers won't have a usable hostname.

**Additional context**
As an example, these two disks are from two completely different hosts:
![image](https://github.com/AnalogJ/scrutiny/assets/1012176/dda34231-a779-4b15-9027-6bacf06b471a)

**Comment by jeremydelattre59** [comment]
Hello,
This is already possible.
To have the hostname, you must enter the "host -> id" property in the collector.yml file.

![image](https://github.com/AnalogJ/scrutiny/assets/66867404/e4daf2d0-018e-49c0-9bbc-28a60c9741f1)

Result:

![image](https://github.com/AnalogJ/scrutiny/assets/66867404/dcb0e029-bd15-4a09-bc30-cb441ff9bb86)

**Comment by PrplHaz4** [comment]
> Hello, This is already possible. To have the hostname, you must enter the "host -> id" property in the collector.yml file.
> 

For docker users this can be set via environment variable:
`COLLECTOR_HOST_ID`

**Comment by Gorian** [comment]
Awesome, thank you so much!

**Comment by xinmans** [comment]
thanks，can U update the docs include COLLECTOR_HOST_ID？

**Comment by PrplHaz4** [comment]
> thanks，can U update the docs include COLLECTOR_HOST_ID？

PR here https://github.com/AnalogJ/scrutiny/pull/566

**Comment by Tampa** [comment]
Collector also supports this via cli as --host-id "hostname"

Should really document the available cli parameters in the collector, because --help does not list it

**Comment by AnalogJ** [comment]
@Tampa it should. I think you just need to run `collector run --help`

**Comment by Tampa** [comment]
I see, but then the general help page does not mention that each command has its own help page. I would either just have them all listen under --help or add that each command has further help pages associated with it. There aren't that many commands in the collector to really warrant splitting it up in my opinion.
