### ISSUE TITLE
Device deletion should be hidden or disabled by default?

### ISSUE THREAD

**Issue by RebelliousX** [AnalogJ/scrutiny#544]
**Is your feature request related to a problem? Please describe.**
I just installed this on my TrueNAS. It works well, but I saw a dangerous option that says "Delete device". The description that asks for confirmation is pointing that all data associated with the device will be deleted! 

Does that mean it will erase the data on the device and all data will be lost? or the historical data is related to SMART monitoring? either way it is really bad wording for this. If it is the former, this is horrible for a SMART monitoring tool to easily offer wiping the drive. If it is the latter, the explanation couldn't be more scarier.

The UI looks good, but I have to uninstall for now, I don't want anyone with access to the web portal to easily delete my storage devices. I guess for now I will rely on `smartctl` command.

**Comment by AnalogJ** [comment]
It's the latter, but you're right the description in the confirmation popup should make it clear that only telemetry and SMART data "about" the device will be deleted, not the data on the device


How would you word that confirmation popup?

**Comment by PrplHaz4** [comment]
> It's the latter, but you're right the description in the confirmation popup should make it clear that only telemetry and SMART data "about" the device will be deleted, not the data on the device
> 
> How would you word that confirmation popup?

Something like?
`This will remove the device and all historical data from Scrutiny.  Any data on the device itself will remain intact.`

**Comment by RebelliousX** [comment]
@AnalogJ something like what @PrplHaz4 proposed is good, I would add to that the device can be added again (if Scrutiny allows adding the device again of course, it should).

**Comment by PrplHaz4** [comment]
> @AnalogJ something like what @PrplHaz4 proposed is good, I would add to that the device can be added again (if Scrutiny allows adding the device again of course, it should).

This is where it starts to get confusing - I believe unless you also remove the device from your config, the next time you restart it will be added automatically anyways.

**Comment by AnalogJ** [comment]
The messaging around device deletion has been updated in master. 

@PrplHaz4 Yeah, deleting your device from Scrutiny won't have an effect if your device is still present on the system. You'll need to remove device attachment in the docker run command/docker-compose config. 

The intention behind the Device delete functionality was to make it easy for users to delete disks that have been removed/replaced
