### ISSUE TITLE
[BUG] Desktop cpu usage spikes very high when pressing view details in webui and out of memory error

### ISSUE THREAD

**Issue by Gecko-with-a-hat** [AnalogJ/scrutiny#549]
**Describe the bug**
When I click on "view details" on the webui for any device my cpu usage spikes (on desktop which i use to view the webpage not the server). I have pretty powerfull computer and cpu usage goes to 100% for over a minute and then the page either loads (but everyting is unclickable) or i get an out of memory error in chrome either instantly or after a moment on the details page). 

**Expected behavior**
I expect the webpage to just load the device details. This worked perfectly fine till about a week ago. I do not think I changed anything relating to scrutiny on either the hub server or the spokes. 

**Screenshots**
![image](https://github.com/AnalogJ/scrutiny/assets/38657170/e3fb80ff-aa1d-4a9c-862e-44668b95e073)

**Log Files**
I don't think I see anything in logs. Just a ton of messages like this:

2023-11-30 17:53:15 level=info msg="Checking Influxdb & Sqlite health" type=web
2023-11-30 17:53:15 level=info msg="127.0.0.1 - b3fb6325c191 [30/Nov/2023:16:53:15 +0000] \"GET /api/health\" 200 16 \"\" \"curl/7.74.0\" (1ms)" clientIP=127.0.0.1 hostname=b3fb6325c191 latency=1 method=GET path=/api/health referer= respLength=16 statusCode=200 type=web userAgent=curl/7.74.0

**Comment by Gecko-with-a-hat** [comment]
Okay I deleted the historic data for the drives and after a refresh from the collectors it works as expected again.

**Comment by Gecko-with-a-hat** [comment]
After a few days it begins again and deleting the device in the WebUI fixes it again, but it only fixes it for a bit.

**Comment by AnalogJ** [comment]
which version of Scrutiny are you running?

**Comment by Gecko-with-a-hat** [comment]
I have it pinned to latest with watchtower auto-updating daily. So I guess it's the latest version as of every day. I added my docker compose to my original message, if you need that.

edit: okay i could not add the docker compose. the "code" thingie doesnt seem to work and the formatting gets messed up completely and it becomes near unreadable. sorry. But i just use the hub-spoke setup with:
- image: ghcr.io/analogj/scrutiny:master-web
- image: influxdb:2.2
- image: ghcr.io/analogj/scrutiny:master-collector

**Comment by Gecko-with-a-hat** [comment]
The problem went away now that I only push the collector data to the hub once an hour. Guess the hub does not like getting S.M.A.R.T. data from 16 drives every minute?

Closing the issue
