### ISSUE TITLE
[FEAT] Test notification

### ISSUE THREAD

**Issue by jakob42** [AnalogJ/scrutiny#55]
I just setup scrutiny and like it. I tried to setup a notification and hopefully have included the config into docker correctly. But since my HDDs all work well at the moment (and I don't want that to change), **is there a way to provoke a notification**? Maybe on the CLI? Just to test that it'll work when it really detects something is wrong. Thanks!

**Comment by AnalogJ** [comment]
Notifications are only partially implemented right now. 
You can manually trigger notifications by POSTing to `/api/health/notify`, however, automated notifications based on drive health are still a work-in-progress.

**Comment by jakob42** [comment]
Thanks! Doesn't seem to work though. Or isn't it supposed to yet?
```
curl -X POST https://my.scrutiny.server/api/health/notify
{"success":true,"errors":null,"data":null}
```

Log on DEBUG:
```
time="2020-10-01T07:00:25Z" level=info msg="192.168.6.47 - c941f71346a2 [01/Oct/2020:07:00:25 +0000] \"POST /api/health/notify\" 200 42 \"\" \"curl/7.58.0\" (1ms)" clientIP=192.168.6.47 hostname=c941f71346a2 latency=1 method=POST path=/api/health/notify referer= respLength=42 statusCode=200 userAgent=curl/7.58.0
time="2020-10-01T07:00:25Z" level=debug msg="{\"success\":true,\"errors\":null,\"data\":null}" bodyType=response clientIP=192.168.6.47 hostname=c941f71346a2 latency=1 method=POST path=/api/health/notify referer= respLength=42 statusCode=200 userAgent=curl/7.58.0
```

**Comment by AnalogJ** [comment]
Hey @jakob42 
I have a beta version of the notifications available via this Docker image: `analogj/scrutiny:notifications`

Would you be willing to test it out for me?

**Comment by jakob42** [comment]
Sure thing, but my weekend is packed. I'll gladly test it out next week

**Comment by jakob42** [comment]
Thanks, works as expected. Sorry I couldn't test it earlier.
```
TEST NOTIFICATION:
Scrutiny SMART error notification for device: /dev/sda
Failure Type: EmailTest
Device Name: /dev/sda
Device Serial: FAKEWDDJ324KSO
Device Type: ATA

Date: 2020-10-06T05:57:08Z
```
