### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by heapxor** [AnalogJ/scrutiny#568]
**Describe the bug**

collector.yaml contains only
devices:
   - device: /dev/ada0
   - device: /dev/ada1
   - device: /dev/ada2

so no idea why once i execute collector the output contains following:

ERRO[0000] Could not retrieve device information for ses0: exit status 2  type=metrics
and
ERRO[0000] no WWN (or fallback) populated for device: da0. Device will be registered, but no data will be published for this device.   type=metrics

ses0 and da0 are not present in collector.yaml

**Expected behavior**
?

**Screenshots**
-

**Log Files**
root@truenas[~]# /usr/local/tools/scrutiny/bin/scrutiny-collector-metrics-freebsd-amd64 run --config /usr/local/tools/scrutiny/config/collector.yaml
2024/01/22 21:33:00 No configuration file found at /opt/scrutiny/config/collector.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                      freebsd.amd64-0.7.2

2024/01/22 21:33:00 Loading configuration file: /usr/local/tools/scrutiny/config/collector.yaml
INFO[0000] Verifying required tools                      type=metrics
INFO[0000] Executing command: smartctl --scan --json     type=metrics
INFO[0000] Executing command: smartctl --info --json /dev/da0  type=metrics
INFO[0000] Using WWN Fallback                            type=metrics
ERRO[0000] no WWN (or fallback) populated for device: da0. Device will be registered, but no data will be published for this device.   type=metrics
INFO[0000] Executing command: smartctl --info --json --device atacam /dev/ada0  type=metrics
INFO[0000] Generating WWN                                type=metrics
INFO[0000] Executing command: smartctl --info --json --device atacam /dev/ada1  type=metrics
INFO[0000] Generating WWN                                type=metrics
INFO[0000] Executing command: smartctl --info --json --device atacam /dev/ada2  type=metrics
INFO[0000] Generating WWN                                type=metrics
INFO[0000] Executing command: smartctl --info --json --device atacam /dev/ses0  type=metrics
ERRO[0000] Could not retrieve device information for ses0: exit status 2  type=metrics
INFO[0000] Sending detected devices to API, for filtering & validation  type=metrics
INFO[0000] Collecting smartctl results for ada0          type=metrics
INFO[0000] Executing command: smartctl --xall --json --device atacam /dev/ada0  type=metrics
INFO[0000] Publishing smartctl results for 0x5000cca2a6c258a9  type=metrics
INFO[0001] Collecting smartctl results for ada1          type=metrics
INFO[0001] Executing command: smartctl --xall --json --device atacam /dev/ada1  type=metrics
INFO[0001] Publishing smartctl results for 0x5000cca2abc5fc27  type=metrics
INFO[0001] Collecting smartctl results for ada2          type=metrics
INFO[0001] Executing command: smartctl --xall --json --device atacam /dev/ada2  type=metrics
INFO[0002] Publishing smartctl results for 0x5000c500dbaf74a9  type=metrics
INFO[0002] Main: Completed                               type=metrics

**Comment by heapxor** [comment]
seems issue is on my side and i have to "somehow" disable in collector these 2 devices

smartctl --scan
**/dev/da0 -d scsi # /dev/da0, SCSI device**
/dev/ada0 -d atacam # /dev/ada0, ATA device
/dev/ada1 -d atacam # /dev/ada1, ATA device
/dev/ada2 -d atacam # /dev/ada2, ATA device
**/dev/ses0 -d atacam # /dev/ses0, ATA device**

**Comment by AnalogJ** [comment]
You can ignore devices via the collector config file. 
https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml#L38-L40
