### ISSUE TITLE
[FEAT] Multiple monitored servers/separate collector+webapp server/VMs?

### ISSUE THREAD

**Issue by fake-name** [AnalogJ/scrutiny#58]
From reading the documentation, it seems that the webapp and the actual SMART data collector are two different binaries, that look to communicate over HTTP.

Does this mean it's possible to run the webapp and collector independently? I have a number of VM hypervisors, and it'd be nice to be able to install *just* the collector on the actual hypervisor host (I use proxmox, and therefore LXC, so docker isn't an option), and then put the webapp in a LXC container. 

Additionally, can multiple collectors feed to the same webapp? Currently it seems like the collector gets passed `--api-endpoint "http://localhost:8080"`, so I assume that could be pointed to the webapp on another box/VM without issue, but that then opens up the concern of what happens if someone sprays garbage data at the webapp. I'd assume right now it only listens on `localhost`, as a security precaution.

Could multiple servers report to the same webapp? And can I separate the webapp and collector onto different (logical) machines?

**Comment by maran** [comment]
I've done what you outlined this morning on a few test servers in my cluster and it works fine. Just run the correct Docker images as provided in the readme and everything you want works.

**Comment by AnalogJ** [comment]
Yes, this is already supported. You can specify the API host using `SCRUTINY_API_ENDPOINT` or passing the value via `--api-endpoint` (if you're using the manual installation instructions). 

Going to close this for now. Feel free to reopen if those don't work for you.

**Comment by fake-name** [comment]
Gotcha. So it's just a minor documentation issue, then.

**Comment by tristan-k** [comment]
Can someone outline the steps to get this working on proxmox?
