### ISSUE TITLE
[FEAT] sorry for troubling you but are issues here being deleted rather than closed?

### ISSUE THREAD

**Issue by ovizii** [AnalogJ/scrutiny#580]
I was looking at an issue to see if there was any news on it and the issues seems to have been deleted as it shows a 404 error. 

This was the original link: https://github.com/AnalogJ/scrutiny/issues/523 

Somebody commented on that issue just 6 days ago as I got a notification email:
![image](https://github.com/AnalogJ/scrutiny/assets/837902/6161f70e-e823-4d05-b88c-f63ab3617b3e)

**Comment by AnalogJ** [comment]
that's kind of a strange accusation given how many unanswered, open issues there are in this repo. 
However I do see that  #523 is missing, and I also have the notification email in my inbox. 

You might want to open a bug with github, since I don't think users have the ability to delete issues in this repo -- even if they were the author.

**Comment by ovizii** [comment]
:-) That was in no way meant as an accusation. If it sounds like one, let me blame English not being my first language, OK?

I was simply wondering, as stated, what happened here. I will see where/how I can inquire about this from Github. Furthermore, I'm no developer and have no idea how this all works and if issues could or could not be deleted.

**Comment by ovizii** [comment]
Hm, I did some googling and found that:

> People with admin permissions in a repository can permanently delete an issue from a repository.

https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue

Not saying anyone did that in this case, but I don't think me opening an issue with GitHub makes sense as they'd probably ask me to check different (access) logs only the repo owner has access to.

I'll simply open a new issue of my own and describe the initial problem.

**Comment by AnalogJ** [comment]
I filed an issue with Github. This is strange, and as you mentioned only Administrators can delete issues, and I'm the only Admin of this repo.

**Comment by ovizii** [comment]
I've opened my own new issue: https://github.com/AnalogJ/scrutiny/issues/591 
The reason I was paying attention to the “deleted” one was that it had a similar error reported by someone else.

**Comment by AnalogJ** [comment]
Hey @ovizii I can't find an email address for you in your profile, so I'll just paste this below:

<img width="721" alt="Screen Shot 2024-02-27 at 9 14 41 AM" src="https://github.com/AnalogJ/scrutiny/assets/891875/92166f7a-a41e-4a62-8542-731ec7ff3c9d">


Looks like it was due to the original opener

**Comment by ovizii** [comment]
Thanks for the info and just in case it wasn't clear, I am 100% I was not the original opener. I just piggybacked onto his issue as it was the only hit which came up when searching for this particular error.

**Comment by Cyberes** [comment]
@ovizii My account was deleted and it took Sh*tHub 4 weeks to get around to restoring it. Sorry.

**Comment by ovizii** [comment]
> @ovizii My account was deleted by some vindictive user and it took Sh*tHub 4 weeks to get around to restoring it. Sorry.

welcome back :-)
