### ISSUE TITLE
Question regarding "scrutiny" value

### ISSUE THREAD

**Issue by oonqt** [AnalogJ/scrutiny#581]
I see under each SMART attribute, there are scrutiny, normalized, and raw. I understand both normalized and raw, but I don't know what the scrutiny value is. Was this anywhere in the documentation? I might have missed it, but I don't see it anywhere and I'm honestly not sure what this value represents. Under most attributes, it seems to directly mirror the "normalized" value, but on certain attributes, it reads "0" despite there being a normalized value.

**Comment by AnalogJ** [comment]
https://github.com/AnalogJ/scrutiny/blob/a3dfce3561bcddcd8b70e4e7f483e22594c8af4d/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#scrutiny-detects-failure-but-smart-passed


Scrutiny values either the normalized or raw data, depending on the thresholds we're using from Backblaze
