### ISSUE TITLE
[FEAT] Grouping disks by host

### ISSUE THREAD

**Issue by maran** [AnalogJ/scrutiny#59]
**Describe the solution you'd like**
I'm debating using Scrutiny to monitor my cluster of bare metal servers. However in this scenario Scrutiny would end up with hundreds of disks to monitor. 

For my specific use-case seeing which disk is on which server would be necessary to make sense of it all. Ideally the disks would even be grouped by their hosts. So that you first select a server and then see the disks available in that server and their status. Perhaps an optional screen with all disks with warnings across the cluster could be added too.

I'm not sure if I'm unique with this requirement but so if you need something similar please let me know :)

**Comment by pieterdevriesch** [comment]
You're not the only one, I'd like it as well, and so would mglubber in his pretty much identical feature request :)

https://github.com/AnalogJ/scrutiny/issues/50

**Comment by AnalogJ** [comment]
Yeah, going to close this as a dupe. 
It's definitely planned.
