### ISSUE TITLE
[FEAT] Mark parameter in hdd as pass until to next change value

### ISSUE THREAD

**Issue by SaraDark** [AnalogJ/scrutiny#590]
Mark parameter in hdd failed as pass until to next change value, eg.
mark failed to eg. new status bypassed until the value change, bypassed status not aletring.
![image](https://github.com/AnalogJ/scrutiny/assets/69405892/d2dd3b48-365e-4d7f-aebb-0e21abb42df8)

thx :)

**Comment by AnalogJ** [comment]
fixed in https://github.com/AnalogJ/scrutiny/pull/547

**Comment by mschout** [comment]
Maybe I missed it, but #547 doesn't include ability to mark the status as bypassed on the device?

**Comment by AnalogJ** [comment]
This isn't a device level setting, its a system level setting. You'll need to set it from the Dashboard
