### ISSUE TITLE
Create multiple docker-compose example files.

### ISSUE THREAD

**Issue by AnalogJ** [AnalogJ/scrutiny#6]
- [ ] all-in-one
- [ ] separate collector/api server

**Comment by boopzz** [comment]
I have this setup, I can do a PR for a couple of compose files for separate collector and api endpoint

**Comment by AnalogJ** [comment]
hey @PHoBwz that would be great!

If you're willing to open a PR, I'd be happy to take a look and merge it.

**Comment by AnalogJ** [comment]
closing, this is documented in https://github.com/AnalogJ/scrutiny/blob/master/docker/example.hubspoke.docker-compose.yml

Thanks!
