### ISSUE TITLE
[BUG] The mobile dashboard shows no hints about running 'scrutiny-collector-metrics run'

### ISSUE THREAD

**Issue by jlasky** [AnalogJ/scrutiny#60]
**Describe the bug**
When loading the WebGUI on mobile before running `scrutiny-collector-metrics run` I am met with a blank screen (screenshot 1)

**Expected behavior**
I expected to see this screen, which I could only see when I changed my phone to "request desktop site" (screenshot 2)

**Screenshots**

![Initial load](https://user-images.githubusercontent.com/50835017/94564284-10924900-0225-11eb-83a2-6d7f8c6c35ea.png)

![Mobile desktop site](https://user-images.githubusercontent.com/50835017/94564506-49cab900-0225-11eb-8d9a-d4063d8f2494.png)

This is on UnRAID 6.8.3, a Pixel 4 XL running Android 11, and the master branch of scrutiny (not sure what version)

**Comment by AnalogJ** [comment]
That's not good, sorry about that. I'll definitely have to fix this, though it might be a while.

**Comment by AnalogJ** [comment]
this shouldn't be an issue any longer since scrutiny automatically runs the collector on startup (in the all-in-one container)

**Comment by vbaros** [comment]
I'm a bit confused. I've used the latest docker image from Linux server and I still had to run collector manually.
