### ISSUE TITLE
It would be nice if we could get the interface to show hours instead of years

### ISSUE THREAD

**Issue by DawnTreader** [AnalogJ/scrutiny#628]
I am an IT guy, I always look at the amount of hours rather than the nice human years

It would be nice if there was a way in the settings to change that output in the dashboard.

**Comment by adprom** [comment]
Having both displayed would be ideal. As well as for "failed drives", mouseover showing the failed metric

**Comment by bauzer714** [comment]
@adprom @DawnTreader this was merged and should be available in docker images.

**Comment by AnalogJ** [comment]
closing now that the PR has been merged.
