### ISSUE TITLE
[FEAT] Is there a way to test if notifications are working?

### ISSUE THREAD

**Issue by ghnp5** [AnalogJ/scrutiny#637]
I set this up:

```
notify:
  urls:
    - "script:///path/to/sendmail.sh"
```

But I've no idea if this will work, until I get my first disk failure.  
And it's hard to debug, in case it doesn't work. (as I need to keep invoking it to troubleshoot)

It would be nice if we could have a button under Settings to "Test Notification" or so.

Unless there's already a way to test? :)

Thank you very much!

**Comment by George-RG** [comment]
check this section out 
https://github.com/AnalogJ/scrutiny?tab=readme-ov-file#testing-notifications

**Comment by ghnp5** [comment]
Ah.. thank you so much!!!

Honestly, the README of this project is one of the best and most useful I've seen so far.

Well done to the contributor(s) !

My fault I skipped that specific section 😁

Thanks again!
