### ISSUE TITLE
Windows defender: Threats found

### ISSUE THREAD

**Issue by Raptime** [AnalogJ/scrutiny#638]
Windows Defender is reporting the following on scrutiny on my system. it started happening today.
![image](https://github.com/AnalogJ/scrutiny/assets/4553932/b4cea63c-483d-41bf-ba93-bf0c60960aca)

I have disabled the scheduled task related to scrutiny just in case.

**Comment by AnalogJ** [comment]
😳 This is the first report like this I've seen. I'm guessing its a false positive but I'll need some more information about your system. 

Where did you get this windows binary from? Did you download it from a release? Which version?

**Comment by Raptime** [comment]
the binary came from this repository, looks like I was using v0.7.2.
I've since moved to v0.8.1 and not getting the warning anymore 🤷‍♂️

**Comment by AnalogJ** [comment]
ran virustotal tests against both windows collectors v0.7.2

- [scrutiny-web-windows-arm64.exe (2🛑 /73)](https://www.virustotal.com/gui/file/4375eab1e2af898b6b46b64ed72bef8bea06314ecb8ac484ba95386be3f2ca6d/detection)
- [scrutiny-web-windows-amd64.exe (1🛑 /73)](https://www.virustotal.com/gui/file/240ba399ef90bd97387b72618bd884c73a5c52d8c1d18d27471bb05c34533cac)

They look like false positives, so I'm going to close this. But if anyone runs into this again please reach out.
