### ISSUE TITLE
[BUG] Missing all SMART data for SATA drives when using SYS_ADMIN

### ISSUE THREAD

**Issue by dr-mcae** [AnalogJ/scrutiny#64]
**Describe the bug**
Scrutiny can't seem to read any data, because the dashboard shows everything set to null / 0 / unix epoch and all drives show as failed. Except for the NVMe drive, which can be read perfectly as far as I can see.

Within the container, I tried some smartctl commands to see what was wrong:

- `smartctl --all /dev/sdX` returned `Probable ATA device behind a SAT layer`
- `smartctl --all -d sat /dev/sdX` returned `Read Device Identity failed: Operation not permitted`
- `smartctl --all -d scsi /dev/sdX` returned some basic drive info like capacity and rotation rate, but most importantly `SMART support is:     Unavailable - device lacks SMART capability.`

When I use `SYS_RAWIO`, smart data can be read from the SATA drives. But as expected, the NVMe drive can't be accessed.

I'm using the analogj/scrutiny image.

**Expected behavior**
Both NVMe and SATA smart data should be accessible and used by Scrutiny when using `SYS_ADMIN`.

**Screenshots**
`SYS_ADMIN`
![afbeelding](https://user-images.githubusercontent.com/43389105/94590624-3ea87500-0287-11eb-881d-b9814a46bbc1.png)

`SYS_RAWIO`
![afbeelding](https://user-images.githubusercontent.com/43389105/94594819-40c00300-028a-11eb-9940-f8ba7e94c3c5.png)

**Log Files**
[collector.log](https://github.com/AnalogJ/scrutiny/files/5300879/collector.log)
[web.log](https://github.com/AnalogJ/scrutiny/files/5300880/web.log)

**Comment by AnalogJ** [comment]
Can you try using both `-cap-add SYS_RAWIO` and `--cap-add SYS_ADMIN` ?

**Comment by dr-mcae** [comment]
This seems to work!
![afbeelding](https://user-images.githubusercontent.com/43389105/94599884-643a7c00-0291-11eb-9b19-cd39a97fd67d.png)

The way I read the readme was that `SYS_ADMIN` superseded `SYS_RAWIO`, but that doesn't (always) seem to be the case. Maybe update the readme a bit?

Thanks!
