### ISSUE TITLE
[BUG] pendencyMissingError: "smartctl binary is missing"

### ISSUE THREAD

**Issue by cybernard** [AnalogJ/scrutiny#641]
**Describe the bug**
pendencyMissingError: "smartctl binary is missing"
For windows vesion

**Expected behavior**
scrunity should use the windows path find the smartctl and work

**Screenshots**
![image](https://github.com/AnalogJ/scrutiny/assets/15042777/ab011840-4f2a-4ac7-9fd8-9dc50e0a4be2)

**Log Files**
If related to missing devices or SMART data, please run the `collector` in DEBUG mode, and attach the log file.
See [/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md](docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md) for other troubleshooting tips. 

```
scrunity.exe run --config e:\download\scrunity\scrunity.yaml --debug

**Comment by dudefoxlive** [comment]
Seems you have to add smartctl to PATH. I just found this out after installing it like normal.

**Comment by vrozaksen** [comment]
Hi, I have same issue in proxmox when running collector in cron

**Comment by AnalogJ** [comment]
scrutiny already checks the PATH for smartctl. If you want to provide an absolute path, you can override it in the collector config:

https://github.com/AnalogJ/scrutiny/blob/master/example.collector.yaml#L80

**Comment by matthiasnm** [comment]
Just wanted to comment I had the same issue with smartctl binary missing, but it wasnt a PATH issue. I noticed this when the dashboard didnt load any results so I ran the scrutiny.exe in powershell and got that error. I noticed smartctl wasnt installed and had to install it from sourceforge. After that everything worked fine.
