### ISSUE TITLE
[BUG] Some drives not showing SMART data and marked as failed

### ISSUE THREAD

**Issue by aravenel** [AnalogJ/scrutiny#65]
**Describe the bug**
Some drives are not showing any SMART data after collector runs. Drives are marked as failed with an update date of 12/31/1969. These drives support SMART and I can view their SMART status manually.

This is running on latest analogj/scrutiny docker image via docker-compose.

**Expected behavior**
All drives should appear with their relevant SMART data. If the drives are not supported, should show a relevant error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/1145897/94605593-5839c480-0267-11eb-8de0-4fa533af1bfd.png)

**Log Files**
[collector.log](https://github.com/AnalogJ/scrutiny/files/5301382/collector.log)
[web.log](https://github.com/AnalogJ/scrutiny/files/5301383/web.log)

docker-compose file:
```  
scrutiny:
    image: analogj/scrutiny
    container_name: scrutiny
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DEBUG=true
      - COLLECTOR_LOG_FILE=/tmp/collector.log
      - SCRUTINY_LOG_FILE=/tmp/scrutiny.log
    volumes:
      - '/run/udev:/run/udev:ro'
    ports:
      - 10400:8080
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/sdf
      - /dev/sdg
      - /dev/sdh
      - /dev/sdi
    cap_add:
        - SYS_ADMIN
    restart: unless-stopped
```

**Comment by AnalogJ** [comment]
Ah, you need to add both `SYS_ADMIN` and `SYS_RAWIO` if you have a mix of NVMe and SATA drives. 
Can you try that?

**Comment by aravenel** [comment]
That worked! Thank you!
