### ISSUE TITLE
Scrutiny not getting the data of all mapped drives

### ISSUE THREAD

**Issue by ManuXD32** [AnalogJ/scrutiny#659]
**Describe the bug**
Some drives just doesn't appear, in my case are /dev/sda /dev/sdb and /dev/nvme0n1
This is my docker compose file:

version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "18080:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/nvme0n1"
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
      - "/dev/sdf"
      - "/dev/sdg"
      - "/dev/sdh"

    environment:
      - COLLECTOR_CRON_SCHEDULE=* 2 * * *

**Expected behavior**
All the drives appearing in the web UI

Is this an error on my end?

Thanks a lot in advance!!

**Comment by InnocentRain** [comment]
to see nvme drives you need to add SYS_ADMIN to your cap_add, also you need to edit your nvme drive to just "nvme0"

**Comment by ManuXD32** [comment]
That was the issue. Thx!!
