### ISSUE TITLE
Is "smartd" daemon running on the Docker container?

### ISSUE THREAD

**Issue by ghnp5** [AnalogJ/scrutiny#661]
The file `/etc/smartd.conf` contains:

```
DEVICESCAN -d removable -n standby -m root -M exec /usr/share/smartmontools/smartd-runner
```

However, from what I can see (with `ps aux` and `service smartd status`), the `smartd` service isn't running and doesn't exist.

Is that correct?

Also, looking at the crons under `/etc/cron.d`, it doesn't appear to be running any `smartctl` tests manually.

I assume the `DEVICESCAN` directive wouldn't run any tests anyway, and would just look at the current attributes/metrics saved, which is what the Scrutiny cron/collector does?

Many thanks!

**Comment by AnalogJ** [comment]
correct. The collector doesnt run the tests itself, it just pulls the SMART attributes.
