### ISSUE TITLE
[FEAT] Display release version along next to logo or commit.

### ISSUE THREAD

**Issue by bcurran3** [AnalogJ/scrutiny#662]
Please add version # to the web UI as the semver # is more easily decipherable than the git commit #.

**Comment by leppa** [comment]
If you use a version tag instead of `master`, e.g. `image: 'ghcr.io/analogj/scrutiny:v0.8.1-omnibus'`, the UI displays that version instead of `master#<commit>`.

**Comment by AnalogJ** [comment]
yep

**Comment by bcurran3** [comment]
(Edit as I think that 2nd comment was directed at me instead of the project.)

<s>Sorry, confused here as the replies are "dry."

Was this request implemented or rejected?</s>

Or am I supposed to do something different? I pull ghcr.io/analogj/scrutiny:master-omnibus. I wish to have the latest most update-to-date version of scrutiny running. (Seems reasonable right?) I don't want to pull a hardcoded version, Ideally I want ":latest".
