### ISSUE TITLE
[FEAT] Add support to FreeBSD

### ISSUE THREAD

**Issue by Itay1787** [AnalogJ/scrutiny#68]
Hi, I'm running several FreeNAS systems and this tool looks great. The problem is that FreeNAS is running on FreeBSD and from what I have seen it is not currently possible to run on FreeBSD. And FreeNAS seems to be among the systems best suited for such a tool. I would love to know if there is an idea in the near future to support FreeBSD systems etc.
Thanks
Itay
By the way, is there a plan for adding Dark Mode?

**Comment by ronron555** [comment]
Dark mode would be nice :)

**Comment by AnalogJ** [comment]
Looks like this should be possible without *much* work: https://golang.org/doc/install/source#environment

I'm assuming you'd like to see `freebsd/amd64` binaries? Or were you looking for:

- `freebsd/arm64`
- freebsd Docker images?

**Comment by Itay1787** [comment]
Hi thanks for the reply
> Looks like this should be possible without _much_ work: https://golang.org/doc/install/source#environment

So I just need to install "Go" on FreeBSD and install manually?

> 
> I'm assuming you'd like to see `freebsd/amd64` binaries? Or were you looking for:
> 
>     * `freebsd/arm64`
> 
>     * freebsd Docker images?

And there is no Docker for FreeBSD and whoever managed to install it is really broken.

**Comment by AnalogJ** [comment]
@Itay1787 I can have the CI system build the freeBSD binary, however, it'll need to be tested on a FreeBSD system before I can include it in official releases. Is that something you can help with?

And just to confirm, you're looking for `freebsd-amd64` builds, right?

**Comment by Itay1787** [comment]
> Is that something you can help with?

Yes, I will happily help you do tests on FreeBSD.

> And just to confirm, you're looking for `freebsd-amd64` builds, right?

Yes.

**Comment by ronron555** [comment]
> Is that something you can help with?

I can also help test it happily :)

**Comment by AnalogJ** [comment]
Awesome, thanks @ronron555  & @Itay1787 

I just added freebsd builds to the CI.

If you're interested in testing it out, you can download the `binaries.zip` file from the latest CI here: https://github.com/AnalogJ/scrutiny/actions/runs/287008586

You'll need to extract the file, `chmod +x scrutiny-collector-metrics-freebsd-amd64`, and then run it via the [manual install instructions](https://github.com/AnalogJ/scrutiny/blob/master/docs/INSTALL_MANUAL.md)

If you could respond to this issue with the results of your testing (either success & failure), that would fantastic, since this is a brand new binary.

**Comment by T-burger** [comment]
Works for me on FreeNAS, FreeNAS-11.3-U3.2
Thanks, selfhosted.show sent me!

**Comment by AnalogJ** [comment]
Thanks for confirming @T-burger 

I'll wait until I have a couple more +1's and then wire up the automation to create freebsd flavors for every release.

**Comment by ThoughtfulDev** [comment]
Works on FreeNAS-11.3-U4.

**Comment by Itay1787** [comment]
> If you could respond to this issue with the results of your testing (either success & failure)

I tested in two FreeNAS systems and in both it works.
But yes, I saw a number of errors in both FreeNAS while scanning.

FreeNAS 1 Version - FreeNAS-11.3-U3.2
FreeNAS 2 Version - FreeNAS-11.3-U4.1

In FreeNAS 1
Errors at the end of the scan:
`ERRO[0004] smartctl returned an error code (2) while processing ses0  type=metrics
ERRO[0004] smartctl could not open device                type=metrics
`

In FreeNAS 2
Errors at the end of the scan:
`ERRO[0005] smartctl returned an error code (2) while processing ses0  type=metrics
ERRO[0005] smartctl could not open device                type=metrics`

**Comment by ronron555** [comment]
I tested the collector on FreeBSD 12.1-RELEASE r354233. 
in the web interface the disks shows fine. but when I ran the command I got the following errors:
```
ERRO[0000] smartctl returned an error code (4) while processing ada0  type=metrics
ERRO[0000] smartctl detected a checksum error            type=metrics
```
and
```
ERRO[0000] smartctl returned an error code (4) while processing ada1  type=metrics
ERRO[0000] smartctl detected a checksum error            type=metrics
```
looks like an error for every disk I have in the system, but again, web ui show just fine.

BTW, add to the documentation `pkg install smartmontools` to install smartctl on FreeBSD :)

**Comment by AnalogJ** [comment]
it looks like the smartctl binary is returning a checksum error. Weird. 
Let me do some reading to see if that's a known issue with smartctl on freebsd.

**Comment by AnalogJ** [comment]
It looks like the checksum error can safely be ignored: https://www.smartmontools.org/ticket/347

Since the dashboard is correctly populated, and you all have your SMART metrics, I'll mark the binary as "working"

**Comment by KenwoodFox** [comment]
I can't seem to find that zip, id like to test it on a FreeBSD system.

Github actions said the binary was completed and uploaded fine but I don't see anything in the artifacts window.

**Comment by AnalogJ** [comment]
@KenwoodFox there's a cleanup job that runs daily. Here's the latest CI run that has the zip file: https://github.com/AnalogJ/scrutiny/actions/runs/287448047

**Comment by FingerlessGlov3s** [comment]
Am I missing something? I can't see the zip files on the run actions

**Comment by FingerlessGlov3s** [comment]
Found it apart of the 0.3.1 release. https://github.com/AnalogJ/scrutiny/releases/tag/0.3.1

**Comment by AnalogJ** [comment]
Hi,
Scrutiny releases will now include a FreeBSD version of the webserver and collector. 

If you have a moment, I'd appreciate it if you could test out the binaries and report back:

https://github.com/AnalogJ/scrutiny/releases/tag/0.3.10

Thanks!
