### ISSUE TITLE
Does Scrutiny use both SQLite and InfluxDB?

### ISSUE THREAD

**Issue by sofakng** [AnalogJ/scrutiny#689]
Does Scrutiny use both SQLite and InfluxDB?

It looks like the configuration settings are stored in scrutiny.yaml/collector.yaml and the data is stored in InfluxDB so what is stored in SQLite?

**Comment by AnalogJ** [comment]
Yep, we use both SQLite and InfluxDB. 
Here's a quick summary of why - https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md

I'm going to close this issue, but if you have any other questions please add them here. I'll make sure to answer them and update the guide.
