### ISSUE TITLE
[BUG] Collector Metrics Windows

### ISSUE THREAD

**Issue by owmsoton** [AnalogJ/scrutiny#691]
**Describe the bug**
ERROR: invalid character '<' looking for beginning of value

**Expected behavior**
collecting metrics and sending them to the endpoint

**Screenshots**
![image](https://github.com/user-attachments/assets/f4c44055-5236-4515-8653-6bb140f17c48)

**Log Files**
[collector.log](https://github.com/user-attachments/files/17004065/collector.log)

**Comment by AnalogJ** [comment]
Looks like the endpoint is returning HTML instead of json. I'm guessing you have a proxy server infront of the webui, or theres a misconfiguration somewhere.

**Comment by owmsoton** [comment]
All the things you said were right, after reading your answer, I started to understand the scenario better and followed the right path, I'm using [UmbrelOS](https://github.com/getumbrel/umbrel-apps) as my docker application server, and the configuration for proxy server was really wrong.

Now everything seems to work correctly. Thanks.

_UmbrelOS: I'm adjusting scrutiny to launch on the platform._
