### ISSUE TITLE
[FEAT] Ability to specify HTTP protocol for connecting to local Gotify server

### ISSUE THREAD

**Issue by OPerepadia** [AnalogJ/scrutiny#692]
**Is your feature request related to a problem? Please describe.**
I am trying to set up notifications to a local Gotify server. It's using http protocol and it is not exposed to the Internet.
However, scrutiny defaults to https, and connection fails.

**Describe the solution you'd like**
An ability to connect to the local Gotify server using http protocol.

**Additional context**

My yaml config is like this

```yaml
notify:
  urls:
    - "gotify://10.0.0.1:8030/BsbtZ6qVwOzOdeu"
```

And here are the errors I see in the logs when it tries to send notification:

```
scrutiny  | time="2024-09-20T08:51:35Z" level=info msg="Sending notifications to gotify://10.0.0.1:8030/BsbtZ6qVwOzOdeu" type=web
scrutiny  | time="2024-09-20T08:51:35Z" level=error msg="One or more errors occurred while sending notifications for gotify://10.0.0.1:8030/BsbtZ6qVwOzOdeu:" type=web
scrutiny  | time="2024-09-20T08:51:35Z" level=error msg="[failed to send notification to Gotify: error sending payload: Post \"https://10.0.0.1:8030/message?token=BsbtZ6qVwOzOdeu\": http: server gave HTTP response to HTTPS client]" type=web
```

I also tried explicitly adding "http" to the url string, but then it starts looking like this: `https://http//10.0.0.1:8030/BsbtZ6qVwOzOdeu` which is wrong
Maybe I missed something and there is already a way to achieve this?

**Comment by AnalogJ** [comment]
we use the shoutrrr library to send notifications. You will want to open an [issue with them](https://github.com/containrrr/shoutrrr) if you need to support the http protocol.

**Comment by shadeMe** [comment]
Sorry to bump this, but the shoutrrr library actually allows for TLS to be disabled via the [`disableTLS` query param/prop](https://containrrr.dev/shoutrrr/v0.8/services/gotify/#queryparam_props).  Unfortunately, it's currently not possible to pass this to scrutiny as `gotify://` URL as it discards any additional parameters apart from the app token.

I was able to workaround this by directly adding the URL as a generic webhook in the config:
```
notify:
  urls:
    - "http://gotify-host:gotify:port/message?token=app-token&disableTls=yes"
```

**Comment by matejkramny** [comment]
if anyone from the future finds this issue, the following worked for me:
```
notify:
  urls:
    - "gotify://gotify-host:gotify-port/gotify-token?disableTls=yes"
```
