### ISSUE TITLE
[FEAT] Docker volume location to keep history?

### ISSUE THREAD

**Issue by seonwoolee** [AnalogJ/scrutiny#70]
**Is your feature request related to a problem? Please describe.**
If I delete the web container for scrutiny, I lose my history of temperature readings. 

**Describe the solution you'd like**
Please document where I need to mount a docker volume inside the web container to retain the history.

**Comment by ronron555** [comment]
DB location inside the docker container is `/scrutiny/config/scrutiny.db`
I just made a volume and mounted `/scrutiny`

**Comment by teambvd** [comment]
This is something of a standard for docker container utilization - anything that requires persistence beyond the life of the container, whatever the container is, needs to be mapped to a directory outside of that array. This has already been documented here:
https://github.com/AnalogJ/scrutiny/blob/master/example.scrutiny.yaml

We're still working on cooking up some broader documentation to cover all the various install types (I say 'we'... It's J's baby, I'm just trying to pitch in where I can :D ), different features and the like, but this at least (persistence) is covered for now.

**Comment by seonwoolee** [comment]
Yes, I'm well aware that it needs to be mapped to a directory outside of the area. I was asking which directory inside the container the actual data is stored. I was looking for it in the README.md and didn't find it.
