### ISSUE TITLE
[FEAT] Group Disks by Collector

### ISSUE THREAD

**Issue by deanfourie1** [AnalogJ/scrutiny#704]
**Is your feature request related to a problem? Please describe.**
Yes kind of, I am unable to identify which disks are part of what server.

Would be nice if there was a way to distinguish what disks are displayed for what collector, rather than just bunching them all together.

Maybe a group of disks, and all those disks are grouped by the collectors IP address, or another way of distinguishing what disks are related to what collector.

**Describe the solution you'd like**
A simple visual grouping or separation of the disks per collector.

**Additional context**

Not really....

**Comment by AnalogJ** [comment]
This should already be possible - https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#hub--spoke-model-with-multiple-hosts

I'll close this issue for now, but feel free to comment/reopen if you still need help
