### ISSUE TITLE
[FEAT] Add notes to disks

### ISSUE THREAD

**Issue by deanfourie1** [AnalogJ/scrutiny#705]
**Is your feature request related to a problem? Please describe.**
A simple ability to add notes to a Disk,

for example, I have a NAS running 4 Disks with 2 LMs, both in a RAID.

I am not sure what disk is in what bay. Would be nice just to be able to add a note saying,

**Bay 4** or **Bay 3** etc.

**Describe the solution you'd like**
Simple feature to add notes to disks, and possibly collectors.

**Additional context**

Nope

**Comment by AnalogJ** [comment]
I you add a disk label in your OS/partition, Scrutiny can retrieve it for display. in the webui

**Comment by deanfourie1** [comment]
Ok thanks.

Resolved with

--host-id
