### ISSUE TITLE
[Request] SQLite DB Support

### ISSUE THREAD

**Issue by zero77** [AnalogJ/scrutiny#709]
**Is your feature request related to a problem? Please describe.**
Installing InfluxDB on a singular device or low powered devices like a raspberry pi or home router seems to much.

**Describe the solution you'd like**
For devices like these could you please support an SQLite DB file instead of InfluxDB

**Additional context**

**Comment by AnalogJ** [comment]
Hey @zero77 I'd be happy to consider a different timeseries database, if you have any suggestions. 
Here's a link explaining why InfluxDB is necessary at the moment - https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md#influxdb-troubleshooting

Closing for now, however feel free to comment if you have feedback

**Comment by zero77** [comment]
Hi @AnalogJ 
i don't have anything against InfluxDB its a good choice. 
But i would like to see a lighter weight option for low powered devices.

Here is some more info about SQLite:
https://dev.to/stephenc222/a-beginners-guide-to-sqlite-the-lightweight-database-solution-c37
https://db-engines.com/en/system/InfluxDB%3BSQLite
https://gosamples.dev/sqlite-intro/

**Comment by AnalogJ** [comment]
We already use sqlite as our database @zero77 
InfluxDB is a timeseries database, and we use it to store (and aggregate) SMART metrics from each device over a long timeframe (years)

**Comment by zero77** [comment]
thanks for your response but unless i am doing something wrong i cannot see a way to run scrutiny without influxdb.
i have commented out all of the influxdb part in the config and get an error

**Comment by AnalogJ** [comment]
That's because both Sqlite and InfluxDB are required, sorry

**Comment by zero77** [comment]
Ok thanks for explaining but, then it goes back to the original request

**Comment by AnalogJ** [comment]
Hey @zero77 I just added some additional context to the InfluxDB page explaining why downsampling is so important - https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md#data-size

Until that functionality is available (or easy to implement) with SQLite, we won't be able to migrate away from InfluxDB. 
Sorry.

**Comment by zero77** [comment]
Thanks for the additional information. I will have a look through
