### ISSUE TITLE
[TESTER] linux-amd64 binary volunteer

### ISSUE THREAD

**Issue by TizzAmmazz** [AnalogJ/scrutiny#711]
I would like to beta-test scrutiny with the manual/binary method.

**Comment by AnalogJ** [comment]
no beta testing required. Many users already do this - https://github.com/AnalogJ/scrutiny/blob/master/docs/INSTALL_MANUAL.md

**Comment by AnalogJ** [comment]
🤦 I'm sorry! I completely misunderstood what you were asking here. I've added you to the testers list:

https://github.com/AnalogJ/scrutiny/blob/master/docs/TESTERS.md

Thanks for volunteering!

**Comment by TizzAmmazz** [comment]
I apologize, my use of "beta-test" was not the most accurate.
