### ISSUE TITLE
[BUG] Scrutiny failure prediction not visible in the Dashboard. 

### ISSUE THREAD

**Issue by alex-phillips** [AnalogJ/scrutiny#72]
**Describe the bug**
Not sure if this is a bug, might be just clarification, but on the extended details for a drive, I have an attribute that is in `WARN` mode but the drive on the main dashboard is listed as green and passed.

**Expected behavior**
At what point does a drive become "not green" or "not passed" on the dashboard?

**Comment by AnalogJ** [comment]
Yeah, the UI needs some tweaks. Basically there's a differences betweeen "SMART" passing and "Scrutiny" passing (since Scrutiny determines predicted failure rates using Backblaze data). 

Once notifications and expanded OS support/documentation is done, I plan on updating the UI.

**Comment by alex-phillips** [comment]
@AnalogJ Ah, makes sense. Since this was clarification, feel free to close the issue unless you would like to keep it open to track the progress. I wouldn't call this a bug, just not implemented yet. Thanks!

**Comment by AnalogJ** [comment]
I'll keep this open until the UI work is complete. Thanks though!
