### ISSUE TITLE
[FEAT] Mark parameter in hdd as pass until to next change value

### ISSUE THREAD

**Issue by retnag** [AnalogJ/scrutiny#720]
I would like to point out that https://github.com/AnalogJ/scrutiny/issues/590 was closed as fixed, when indeed the requested feature was not implemented, and I think it would be a very useful addition. This is a feature request for the same feature. Please reconsider and reopen if possible.

**Comment by AnalogJ** [comment]
This isn't a device level setting, its a system level setting. You'll need to set it from the Dashboard

**Comment by AnalogJ** [comment]
Closing this issue, but happy to reopen if you're still having issues.
