### ISSUE TITLE
[FEAT] scan on startup

### ISSUE THREAD

**Issue by ipkpjersi** [AnalogJ/scrutiny#73]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I start up the Docker omnibus image and it prompts me with "No Devices Detected!". I go to bed, wake up 8 hours later, and I'm still prompted with "No Devices Detected!". Every single time I start up the image, my drives aren't detected.

This should be a high priority issue/feature.

**Describe the solution you'd like**
I believe that scrutiny should automatically scan the drives on startup of the omnibus Docker image so that `docker exec scrutiny /scrutiny/bin/scrutiny-collector-metrics run` is not required to be run manually. At the very least, there should be an option to automatically scan the drives on startup of the omnibus Docker image.

**Comment by AnalogJ** [comment]
Hey,
Yeah, this is a good idea. The fact that you have to trigger the initial collector run manually has definitely confused people. Keep in mind that the default `cron` schedule is for the collector to run every 24h (which I plan on making configurable at some point #66)

**Comment by ipkpjersi** [comment]
~~For now as a workaround, I've tried automating the scanning in a shell script complete with the startup of the Docker image, but since I bind to host port 8090, for some reason `docker exec scrutiny /scrutiny/bin/scrutiny-collector-metrics run` in a shell script doesn't work and throws this error: `2020/10/03 15:32:45 ERROR: Post "http://localhost:8080/api/devices/register": dial tcp 127.0.0.1:8080: connect: connection refused` but if I run `docker exec scrutiny /scrutiny/bin/scrutiny-collector-metrics run` manually outside of a shell script, it works fine.~~

Here is my shell script for automatically scanning if anyone is interested, it's a decent workaround for now ~~it's not particularly useful at the moment due to the issue I mentioned~~:
```bash
#!/bin/bash
docker run -it --rm -d -p 8090:8080 \
-v /run/udev:/run/udev:ro \
--cap-add SYS_RAWIO \
--device=/dev/sda \
--device=/dev/sdb \
--device=/dev/sdc \
--device=/dev/sdd \
--device=/dev/sde \
--device=/dev/sdf \
--device=/dev/sdg \
--name scrutiny \
analogj/scrutiny
sleep 15
docker exec scrutiny /scrutiny/bin/scrutiny-collector-metrics run
```

Edit: I fixed my script by adding a 15 second pause before trying to collect metrics.
