### ISSUE TITLE
[BUG] Media collecter cannot find smartctl when run by cron

### ISSUE THREAD

**Issue by UntouchedWagons** [AnalogJ/scrutiny#76]
**Describe the bug**

scrutiny-collector-metrics-linux-amd64 cannot find smartctl when run by cron.

**Expected behavior**

Collector program to run

**Log Files**
If related to missing devices or SMART data, please run the `collector` in DEBUG mode, and attach the log file.

```
 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                        linux.amd64-0.2.4

time="2020-10-03T18:30:01-04:00" level=info msg="Verifying required tools" type=metrics
2020/10/03 18:30:01 ERROR: DependencyMissingError: "smartctl is missing"
```

Collector is run by cron using

```
*/15 * * * * /bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "https://scrutiny.untouchedwagons.site" > /tmp/scrutiny.log 2>&1
```

**Comment by AnalogJ** [comment]
ah, scrutiny looks for `smartctl` on the path, which is unset (I think) when run by cron.
Can you test the following cron command?

```
*/15 * * * * . /etc/profile; /bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "https://scrutiny.untouchedwagons.site" > /tmp/scrutiny.log 2>&1
```

**Comment by UntouchedWagons** [comment]
Yeah that worked.

**Comment by AnalogJ** [comment]
great. I'll update the docs.

**Comment by TehloWasTaken** [comment]
Sorry to reopen this issue, I'm having the exact same issue and even with your fix I am still getting the 'smartctl is missing' error.
This is my cron command:

(its set to every minute just for testing purposes)

`*/1 * * * * . /etc/profile; /opt/scrutiny/bin/scrutiny-collector-metrics-linux-amd64 run --api-endpoint "http://10.0.1.114:8080" > /tmp/scrutiny.log 2>&1` 

Any help would be appreciated. Thanks!
