### ISSUE TITLE
Change timezone of docker containers

### ISSUE THREAD

**Issue by ronron555** [AnalogJ/scrutiny#78]
The scans not show in the correct time on the web UI, running the collector and the web-ui on two different machines.
I tried to pass the environment variable "TZ" and change the timezone that way but it doesn't work, tried it on both containers..

How I can change the timezone of the containers?

Thanks,
Ron.

**Comment by AnalogJ** [comment]
Thanks for this!
I thought I was using UTC as the timezone for all datetime information sent to the API, but it sounds like I misssed something. I'll take a look.

**Comment by AnalogJ** [comment]
The TZ variable should be supported now, though it is not configured in the UI yet.
