### ISSUE TITLE
[BUG] Blank web page when page width is less than 960px

### ISSUE THREAD

**Issue by arnauos** [AnalogJ/scrutiny#92]
I was trying the web interface on my mobile and tablet and noticed the site was totally blank until I rotated the screen.

I then tested on my laptop and as soon as the page width is less than 960px, nothing is visible (if page was correctly loaded before resizing, a refresh is required to make it fail)

Confirmed using both Safari and Chrome on iOS, iPadOS and macOS

![Screenshot 2020-10-08 at 23 28 14](https://user-images.githubusercontent.com/25105005/95515690-53d77f00-09be-11eb-9ad1-8d97471787bc.png)

**Comment by AnalogJ** [comment]
Thanks for pointing this out @arnauos I definitely have to fix this :(

**Comment by vbaros** [comment]
Just experienced the same bug on mobile on Android. Switching to desktop version shows the dashboard correctly.

**Comment by agneevX** [comment]
This bug makes it unusable on mobile :(

Browser console:

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/19761269/109388536-c4f7de80-792d-11eb-8241-8fe4dff9092d.png">

**Comment by fightforlife** [comment]
Same for me on mobile. Currently I force the desktop mode in my browser.

**Comment by alexbelgium** [comment]
Same here. I've made an add-on for home assistant and put a temporary fix. https://github.com/alexbelgium/hassio-addons/tree/master/scrutiny

By replacing 'content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"' with 'content="width=980, initial-scale=1.0"' in /app/scrutiny-web/index.html, it forces the width at 980 on mobile and prevents the issue 

Here is a pull request : https://github.com/AnalogJ/scrutiny/pull/150

**Comment by alexbelgium** [comment]
Update: the issue seems to be with lt-md.

This code removes the issue on my system by editing the js files.
```
grep -rl '"lt-md":"(max-width:  959px)"' /app | xargs sed -i 's|"lt-md":"(max-width:  959px)"|"lt-md":"(max-width:  100px)"|g'
```

**Comment by vbaros** [comment]
Hi @AnalogJ. This is a long standing issue. Would be nice to fix it.
