### ISSUE TITLE
Add FreeBSD Support

### ISSUE THREAD

**Issue by KenwoodFox** [AnalogJ/scrutiny#99]
**Describe the bug**
Upon trying to excecute `# /opt/scrutiny/bin/scrutiny-web-freebsd-amd64 start --config /opt/scrutiny/config/scrutiny.yaml` after completing the manual install process I receive an error and the software does not start.

**Expected behavior**
I would expect that scrutiny should create the missing database? The manual does not mention anything about this.

```
root@Scrutiny:/opt/scrutiny/web # /opt/scrutiny/bin/scrutiny-web-freebsd-amd64 start --config /opt/scrutiny/config/scrutiny.yaml

2020/10/12 14:01:32 No configuration file found at /scrutiny/config/scrutiny.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                   freebsd.amd64-0.3.1

Start the scrutiny server
2020/10/12 14:01:32 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

Trying to connect to database stored: /opt/scrutiny/config/scrutiny.db

2020/10/12 14:01:32 /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/sqlite3.go:17
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
panic: Failed to connect to database!

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.DatabaseMiddleware(0xe24b60, 0xc0000aac88, 0xe2a5e0, 0xc000360b60, 0xe261e0)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/sqlite3.go:22 +0x5ab
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc000368410, 0xe2a5e0, 0xc000360b60, 0x14)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xcf
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc000368410, 0x0, 0x0)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:90 +0x234
main.main.func2(0xc000337780, 0x4, 0x6)
        /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x198
github.com/urfave/cli/v2.(*Command).Run(0xc00034fb00, 0xc000337600, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4b9
github.com/urfave/cli/v2.(*App).RunContext(0xc000218780, 0xe179c0, 0xc0000b4000, 0xc0000b0040, 0x4, 0x4, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x790
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x703
```

**Comment by KenwoodFox** [comment]
I noticed this `2020/10/12 14:06:01 No configuration file found at /scrutiny/config/scrutiny.yaml. Using Defaults.`
there is no `/scrutiny/config/scrutiny.yaml` should I move config there? I put everything in opt. But does scrutiny want to run in the root?

**Comment by AnalogJ** [comment]
ooof. sorry about this, it's a copy paste error.

**Comment by AnalogJ** [comment]
if you're doing a [manual install](https://github.com/AnalogJ/scrutiny/blob/master/docs/INSTALL_MANUAL.md) the instructions describe how to create a config file, and start the collectoor using the `--config` flag, so the webapp should never look for a config file at `/scrutiny/config/scrutiny.yaml` (that path is checked in the Docker image). 

I don't see that error message in your original post.

**Comment by KenwoodFox** [comment]
> if you're doing a [manual install](https://github.com/AnalogJ/scrutiny/blob/master/docs/INSTALL_MANUAL.md?rgh-link-date=2020-10-14T07%3A41%3A44Z) the instructions describe how to create a config file, and start the collectoor using the `--config` flag, so the webapp should never look for a config file at `/scrutiny/config/scrutiny.yaml` (that path is checked in the Docker image).
> 
> I don't see that error message in your original post.

I'm using --config?
```root@Scrutiny:/opt/scrutiny/web # /opt/scrutiny/bin/scrutiny-web-freebsd-amd64 start --config /opt/scrutiny/config/scrutiny.yaml```
The error message is right here.
```2020/10/12 14:01:32 No configuration file found at /scrutiny/config/scrutiny.yaml. Using Defaults.```

If i create that directory it still does not auto-gen the database.

**Comment by KenwoodFox** [comment]
@AnalogJ Am I missing something in your post? Could you reword it?

**Comment by AnalogJ** [comment]
Hey @KenwoodFox 

Sorry about the confusing, this is all related to the fact that static binaries are not being correctly built for Scrutiny. I'm working on an alternative method to build binaries #101. It seems to be working, but I need to find a proper cross-compiler that works for freebsd. 

Sorry about this. In the meantime, I'll go into the release and delete the freebsd binaries so no one eles gets confused.

**Comment by AnalogJ** [comment]
Yeah, so it looks like FreeBSD support will have to be dropped until I can figure out a way to build FreeBSD binaries using a cross-compiler or a FreeBSD build node :(

Unfortunately, XGO doesn't support FreeBSD out of the box, and Github Actions don't support FreeBSD build nodes.

**Comment by KenwoodFox** [comment]
This is terrible news :c If there's anything I can do to help get this working on FreeBSD id like to do it.

**Comment by AnalogJ** [comment]
Investigating 
- https://hub.docker.com/r/sammcz/docker-build/dockerfile
- https://github.com/smartmontools/docker-build/blob/master/Dockerfile 
- https://smallhacks.wordpress.com/2018/01/08/c-cross-compilation-on-linux-for-the-freebsd-target-using-gcc-or-clang/
- https://www.wezm.net/technical/2019/03/cross-compile-freebsd-rust-binary-with-docker/
- https://github.com/sandvine/freebsd-cross-build

Smartmontools has its own cross compile container with freebsd support.

**Comment by FingerlessGlov3s** [comment]
I've been using the 0.3.1 build of the collector on OPNsense (FreeBSD) ands its been working a treat. Hopefully you can add support for it again in the Packagr.

I actually did a blog post on how to get it working on OPNsense too
https://fingerlessgloves.me/2021/04/14/scrutiny-on-opnsense-smart-monitoring/

**Comment by AnalogJ** [comment]
Hi,
Scrutiny releases will now include a FreeBSD version of the webserver and collector. 

If you have a moment, I'd appreciate it if you could test out the binaries and report back:

https://github.com/AnalogJ/scrutiny/releases/tag/0.3.10

Thanks!

**Comment by FingerlessGlov3s** [comment]
I've now tested the collector on version 0.3.11 on my OPNsense install (FreeBSD based), and it works fine. Can see it reported back ok.

I've not got the web version setup, since I have that running in a Linux docker container, hopefully someone else can test this.

**Comment by AnalogJ** [comment]
awesome, in that case I'll close this (and related) issues. If anyone finds a problem with the FreeBSD web server, they can open a new issue.
